### ISSUE TITLE
github.com/google/cadvisor checksum failing

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#32387] opened 2024-04-15 15:38 UTC
### Describe the issue you're reporting

We're seeing CI failures which appear to be related to https://github.com/google/cadvisor/issues/3508. The earliest failure on `main` appears to be after merging https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32368, though CI passed on that PR.

```
Running target 'moddownload' in module 'receiver/azuremonitorreceiver' as part of group 'all'
make --no-print-directory -C receiver/azuremonitorreceiver moddownload
go: downloading github.com/AzureAD/microsoft-authentication-library-for-go v1.2.2
go: downloading github.com/pkg/browser v0.0.0-20240102092130-5ac0b6a4141c
go: downloading github.com/golang-jwt/jwt/v5 v5.2.1
verifying github.com/google/cadvisor@v0.49.1: checksum mismatch
	downloaded: h1:L9S9Pdb/uu1HA2PGmgBG4q/V3s9Ct3VWsLicarHVvfQ=
	go.sum:     h1:9M++63nWvdq6Oci6wUDuAfQNTZpuz1ZObln0Bhs9xN0=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

[Example](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8680678623/job/23801791375)

**Comment by crobert-1** [comment] 2024-04-15 15:41
I believe this is a duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32381, we can keep the other as the original and add a reference 👍

**Closed by crobert-1** 2024-04-15 15:41 UTC
Labels: needs triage
