### ISSUE TITLE
[processor/k8sattribute] k8sattribute processor occasionally does not append attributes to telemetry data

### ISSUE THREAD

**Issue by fatsheep9146** [open-telemetry/opentelemetry-collector-contrib#18892] opened 2023-02-23 01:20 UTC
### Component

processor/k8sattributes

### What happened

              It's an appropriate remediation for the test flakiness, but it doesn't solve the root cause which is in the k8s attribute processor that doesn't enrich all the traces from the beginning as expected. @fatsheep9146, can you please file an issue so someone can follow up later on?

_Originally posted by @dmitryax in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18876#discussion_r1115136650_

We found a flaky test in #18676, and I solve the flaky test by modifing the test function not to resolve the processor itself.

The problem can be detailed as following

In k8sattribute e2e case, I output all lines of raw trace data and found the data of job workload is like following

line 1, there only exists several attributes not provided by k8sattributeprocessor, like following

```
{  
    "resourceSpans": [
        {
            "resource": {
                "attributes": [
                    {  "key": "k8s.container.name", "value": {} },
                    {  "key": "k8s.container.restart_count", "value": {}},
                    {  "key": "service.name", "value": {}},
                    {  "key": "k8s.pod.ip", "value": {}}
                ]
            },
            "scopeSpans": [...]
        }            
}
```
line 2 and all the others, the attributes are appended by k8sattributeprocessor
```
{  
    "resourceSpans": [
        {
            "resource": {
                "attributes": [
                    {  "key": "k8s.container.name", "value": {} },
                    {  "key": "k8s.container.restart_count", "value": {}},
                    {  "key": "service.name", "value": {}},
                    {  "key": "k8s.pod.ip", "value": {}},
                    {  "key": "k8s.pod.name", "value": {}},
                    {  "key": "k8s.pod.uid", "value": {}},
                    {  "key": "k8s.job.name", "value": {}},
                    {  "key": "k8s.node.name", "value": {}},
                    {  "key": "k8s.labels.app", "value": {}},
                    ....
                ]
            },
            "scopeSpans": [...]
        }            
}
```
I think this may happen when the pod cache is not ready in processor, but the span data is already comming.

We should enhancement the processor, so that all the trace data can be guaranteed to be appended by attributes.

**Comment by swiatekm-sumo** [comment] 2023-04-06 16:00
Looking at the draft PR, the problem is basically a race with API server notifications. We do know about the Pod, as we got the notification about it having been created, but we don't know about its IP address - which it only gets after having been assigned to a Node iirc. By default, we only use the connection IP for association, so we can't find the Pod and don't add metadata to traces before we get the notification containing the IP address.

The immediate fix for the flaky test is to change the processor config to use the Pod name and namespace for association instead.

In the longer term, maybe this should be the default? WDYT @dmitryax ? It's more expensive to always check both, but we'd get universally better reliability.

**Comment by fatsheep9146** [comment] 2023-04-08 06:41
> The immediate fix for the flaky test is to change the processor config to use the Pod name and namespace for association instead.

Thanks for @swiatekm-sumo advise. I pasted my analysis here for convenient. 

## How to reproduce the bug

I just raise the speed of emitting trace datas for telemetrygen from 1 data per second to 100 data per second.

In order to construct an example, I modified the e2e test workload to trigger a telemetrygen-job to emitting traces in 100/s speed, then check about the tracing data and filtered the temporarily added logs.

After those work, I can basically reproduce the bug stably, here is one 
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4401706057/jobs/7708150125

## How to enrich the processor's logs?

I chose two functions to enrich logs

- the `processResource` function: 
   - I logged whether it can fetch the pod metadata from cache, when it tries to process the `Resource`
      - if so, it logs `[TEMPORARY] get the pod from cache xxx`
      - if not, it logs `[TEMPORARY] failed get the pod from cache xxx`
      https://github.com/fatsheep9146/opentelemetry-collector-contrib/blob/cb3550d6172e31cbc4e3fdbe440a7272a227c9cf/processor/k8sattributesprocessor/processor.go#L128-L144

- the `addOrUpdatePod` function: 
   - I logged that when the function is called, what pod info(metadata) can be fetched
      - `[TEMPORARY] watch pod info {xxx}`
https://github.com/fatsheep9146/opentelemetry-collector-contrib/blob/cb3550d6172e31cbc4e3fdbe440a7272a227c9cf/processor/k8sattributesprocessor/internal/kube/client.go#L535
   - I logged that how many pod identifiers can be generated from pod info
      - `[TEMPORARY] added [%d]th pod identifier to cache {xxx}`
      https://github.com/fatsheep9146/opentelemetry-collector-contrib/blob/cb3550d6172e31cbc4e3fdbe440a7272a227c9cf/processor/k8sattributesprocessor/internal/kube/client.go#L544-L551

## What is the root cause?

After parsing the logs in [reproduced case](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4401706057/jobs/7708150125), I found following informations

Note: for readability, I hide some unnecessary fields in log

In timestamp `t1` **2023-03-13T05:34:13**, this is the first time when processor called `processResource` 
```
2023-03-13T05:34:13 [TEMPORARY] failed get the pod from cache { .... "identifier": [
   {"Source":{"From":"connection","Name":""},"Value":"10.244.0.6"},
   {"Source":{"From":"","Name":""},"Value":""},
   {"Source":{"From":"","Name":""},"Value":""},
   {"Source":{"From":"","Name":""},"Value":""}]}
```

We found that processor could not fetch pod metadata from cache through the pod identifier `connection`. Here is the reason why some traces are not appended with pod metadata.

But why can not fetch metadata from cache? This is due to, before processing the resources, the pod info provided to `addOrUpdatePod` does not contain pod ip.

here is the last time call of `addOrUpdatePod` before first call of `processResource`

```
2023-03-13T05:34:11.607Z	[TEMPORARY] watch pod info	{
        "kind": "processor", "name": "k8sattributes", "pipeline": "traces", 
        "info": {
             "Name":"telemetrygen-traces-job-qf47r",
             "Address":"",
             "PodUID":"786409b2-ebeb-4fb9-9d87-2e9619385c79",
              "Attributes":{"k8s.annotations.workload":"job","k8s.job.name":"telemetrygen-traces-job","k8s.job.uid":"27c95649-7206-46cc-97ae-2a17cf6b6c0e","k8s.labels.app":"telemetrygen-traces","k8s.namespace.name":"default","k8s.node.name":"chart-testing-control-plane","k8s.pod.name":"telemetrygen-traces-job-qf47r","k8s.pod.start_time":"2023-03-13 05:34:11 +0000 UTC","k8s.pod.uid":"786409b2-ebeb-4fb9-9d87-2e9619385c79"},
              "StartTime":"2023-03-13T05:34:11Z",
              ....}
```
we found that the `Address` does not has any value. So processor certainly can not fetch pod info through pod ip. I think at that time, the pod was not attached by any pod ip.

But, the pod ip(`Address`) info can be fetched in `addOrUpdatePod` after the first call of `processResource`

```
2023-03-13T05:34:14.303Z	[TEMPORARY] watch pod info	
{"kind": "processor", "name": "k8sattributes", "pipeline": "traces", 
 "info": {
       "Name":"telemetrygen-traces-job-qf47r",
       "Address":"10.244.0.6",
        "PodUID":"786409b2-ebeb-4fb9-9d87-2e9619385c79",
        "Attributes":{"k8s.annotations.workload":"job","k8s.job.name":"telemetrygen-traces-job","k8s.job.uid":"27c95649-7206-46cc-97ae-2a17cf6b6c0e","k8s.labels.app":"telemetrygen-traces","k8s.namespace.name":"default","k8s.node.name":"chart-testing-control-plane","k8s.pod.name":"telemetrygen-traces-job-qf47r","k8s.pod.start_time":"2023-03-13 05:34:11 +0000 UTC","k8s.pod.uid":"786409b2-ebeb-4fb9-9d87-2e9619385c79"},
         "StartTime":"2023-03-13T05:34:11Z",
         ....}
```

So the root cause is that the k8s pod update event, in which the pod ip is attached to pod, maybe watched by processor after the processor started to process the resource, so the pod info can not be attached to the Resource.

If we describe the whole process through picture, it would be like:

![image](https://user-images.githubusercontent.com/11855957/230706314-683b598e-0154-43d0-8bb4-139c61743553.png)

## How to resolve

Since in some cases, the first trace data may come into collector **before** the collector got the updated event from kube-apiserver which has pod ip, I think maybe the `pod.uid` is a more suitable default `podIdentifier` than `connection`?
@dmitryax 

Because no matter how fast the first trace data is produced by pod, the pod uid and all the other info excepted pod ip can all be found in cache. (since assigning the pod  with an IP is basically the last step of a pod lifecycle).

**Comment by dmitryax** [comment] 2023-04-09 17:08
> Since in some cases, the first trace data may come into collector before the collector got the updated event from kube-apiserver which has pod ip, I think maybe the pod.uid is a more suitable default podIdentifier than connection?

The advantage of the k8s processor lies in its ability to extract all the k8s metadata from incoming signals without the need for any pre-set attributes. The impact of this particular behavior is not substantial enough to warrant the removal of this functionality from the default configuration.

I believe it's reasonable to delay attributes enrichment for the `connection` association until the watched pod gets assigned IP address as logs as k8s attributes processor doesn't set **any** attributes in the period between pod creation and IP address assignment.

For the e2e test, we only need to wait for the telemetrygen pod to reach the running state, indicating that an IP has been assigned, before starting the collector. In that can we should have **all** attributes to be set from the very first span/metric/log sent by the telemetrygen. If that is not the case, it means we still have a bug.

**Comment by fatsheep9146** [comment] 2023-04-10 01:50
> For the e2e test, we only need to wait for the telemetrygen pod to reach the running state, indicating that an IP has been assigned, before starting the collector. In that can we should have **all** attributes to be set from the very first span/metric/log sent by the telemetrygen. If that is not the case, it means we still have a bug.

You mean we should switch the order of starting the telemetrygen and collector in 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5fbe4fa1166cfccc09af1afd6a35ef9acac1f072/processor/k8sattributesprocessor/e2e_test.go#L88-L89

first start telemetrygen, wait it until it is in running states, then starts the collector to make sure the pod ip info can by watched by k8sattribute processor?

**Comment by dmitryax** [comment] 2023-04-10 16:11
I don't think the order matter that much. We can keep the existing order, just need to wait for the telemetrygen pods to start before listening for collector's output. Not sure about the k8s job tho, can we make it run longer to make sure it doesn't end until we wait for all telemetrygen pods to start?

**Closed** 2023-05-30 18:04 UTC
Labels: bug, help wanted, processor/k8sattributes
