### ISSUE TITLE
Prometheus Stale NaN Values are Reported with 0 Value

### ISSUE THREAD

**Issue by michaelli321** [open-telemetry/opentelemetry-collector-contrib#26716] opened 2023-09-15 21:37 UTC
### Component(s)

receiver/prometheus

## Description
If [a Stale NaN value](https://github.com/prometheus/prometheus/blob/39d79c3cfb86c47d6bc06a9e9317af582f1833bb/pkg/value/value.go#L28) is returned from the Prometheus job, it is converted to a `NumberDataPoint` with value 0 in the `prometheusreciever`

## Steps to Reproduce
1. Create a prometheus server that doesn't always report a certain metric
2. Have the `prometheusreceiver` scrape that server
3. Observe that on scrapes where the metric disappears, a 0 value is exported for that metric

## Expected Result
The metric should either not be present or that metric should have a value of `NaN`

## Actual Result
A misleading 0 datapoint is exported for the metric

### Collector version

v0.81.0

## Environment
Compiler(if manually compiled): go 1.20.6

### Additional context

When the prometheusreceiver is converting the prometheus values to OTLP, it never sets a value on the NumberDataPoint ([ref](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto//#L342-L378)).

- A new NumberDataPoint is created [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/internal/metricfamily.go#L219) ([ref](https://github.com/open-telemetry/opentelemetry-collector/blob/2ebe1e501f9a206237de1009a127f1a419ab3696/pdata/pmetric/generated_numberdatapointslice.go#L81-L84))
- When we encounter a stale NaN [this block](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/internal/metricfamily.go#L230-L232) is hit which sets a flag on the NumberDataPoint
- The [value](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto//#L366-L369) field is never set so I believe we just serialize a 0 value since value is not marked as optional in the protobuf definition
  - [protobuf default values](https://protobuf.dev/programming-guides/proto3/#default)
  - [protobuf oneof semantics](https://protobuf.dev/programming-guides/proto3/#oneof)
- [When the Metrics are then passed to the](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/internal/transaction.go#L293-L304) MetricsAdjuster, [nothing happens for gauges](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/internal/metrics_adjuster.go#L277C1-L278C1), whereas other metric types will act upon the NoRecordedValue flag e.g. see [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/internal/metrics_adjuster.go#L410-L414)
- Another example of properly handling this case: The prometheusremotewrite [exporter will detect the](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1db5684daf6ac040ac81d97ea15f490b0e6c36a6/pkg/translator/prometheusremotewrite/number_data_points.go#L45-L47) NoRecordedValue flag and set the value itself

**Comment by dashpole** [comment] 2023-09-18 13:51
The receiver uses the `DATA_POINT_FLAGS_NO_RECORDED_VALUE` data point flag to indicate that the point has no value. https://github.com/open-telemetry/opentelemetry-proto/blob/ac3242b03157295e4ee9e616af53b81517b06559/opentelemetry/proto/metrics/v1/metrics.proto#L332-L335

It seems like correct behavior to not record a value when setting the NO_RECORDED_VALUE flag, right?

> The metric should either not be present or that metric should have a value of NaN

We need the metric to be present to allow prometheus exporters to work correctly.  Setting the value to `NaN` is a possibility, and we used to do that IIRC, but it was much more confusing for exporters that didn't check the data point flag.   I remember at least one case where an exporter was converting the value to an Int, and got a large negative number, which messed up graphs and rates.

I'll see if @Aneurysm9 has any thoughts, but I'm leaning towards keeping the current behavior.

**Comment by sirianni** [comment] 2023-09-18 14:09
Thanks @dashpole!

> to allow prometheus exporters to work correctly.

Right, this makes sense. I think the issue is that when using the `prometheusreceiver` with the `otlpexporter` a datapoint with a value of `0` is emitted.  This is causing incorrect behavior in our backend since when doing aggregations like average, etc.

**Comment by mx-psi** [comment] 2023-09-18 14:11
> Thanks @dashpole!
> 
> > to allow prometheus exporters to work correctly.
> 
> Right, this makes sense. I think the issue is that when using the `prometheusreceiver` with the `otlpexporter` a datapoint with a value of `0` is emitted. This is causing incorrect behavior in our backend when doing aggregations like average, etc.

The OTLP exporter should also be exporting the `NO_RECORDED_VALUE`. Maybe your backend does not support `NO_RECORDED_VALUE`?

**Comment by sirianni** [comment] 2023-09-18 14:16
> Maybe your backend does not support NO_RECORDED_VALUE?

Ah, that's likely what is happening.  Still, would it be better for the OTLP exporter to be emitting `NaN` instead of `0`?

**Comment by michaelli321** [comment] 2023-09-20 18:10
@mx-psi @dashpole Do you have any updates here? It may take sometime for the backends to implement the functionality to support `NO_RECORDED_VALUE`. Would the best option here be to write a custom processor for these metrics? OTTL doesn't work here since it doesn't support the bitwise `&` operator

**Comment by dashpole** [comment] 2023-09-20 18:18
You could certainly write a custom processor.  I don't know if it would be accepted in the contrib repo, but you could build it into your own collector to work around the issue until the backend handles the flag.

**Comment by crobert-1** [comment] 2023-11-01 21:07
It seems like the conclusion of this issue is that everything collector-related is functioning as intended, but some backends do not yet support the `NO_RECORDED_VALUE` flag. Am I following this properly? If so, I believe we can close this issue.

**Comment by dashpole** [comment] 2023-11-01 21:10
Agreed

**Closed by dashpole** 2023-11-01 21:10 UTC
Labels: bug, receiver/prometheus
