### ISSUE TITLE
SIGSEGV in awsxray receiver

### ISSUE THREAD

**Issue by mkielar** [open-telemetry/opentelemetry-collector-contrib#8271] opened 2022-03-07 12:44 UTC
**Describe the bug**
OpenTelemetry 

**Steps to reproduce**
1. We have an AWS ECS FARGATE Service, running `otel` sidecar, `envoy` sidecar (for AppMesh) and a .NET Application.
2. We've ran the application and it worked correctly for ~1h, after which it started failing with SIGSEGV error from `awsxray` receiver.
3. The ECS Tried to start new tasks, which were failing in a similar way after some time of running properly.

**What did you expect to see?**
Nothing ;) I expected it to work.

**What did you see instead?**
Following log in Cloudwatch for OTEL Sidecar:
```
2022-03-07T10:05:33.391Z	warn	awsemfexporter@v0.43.0/grouped_metric.go:91	Duplicate metric found	
{
    "kind": "exporter",
    "name": "awsemf/statsd/envoy_metrics",
    "Name": "envoy.appmesh.TargetResponseTime",
    "Labels": {
        "Mesh": "perf",
        "TargetVirtualNode": "[svc1, MASKED]",
        "TargetVirtualService": "[svc1, MASKED].perf.local",
        "VirtualNode": "[svc2, MASKED]",
        "appmesh.mesh": "perf",
        "appmesh.virtual_node": "[svc2, MASKED]"
    }
}
2022-03-07T10:05:33.439Z	warn	cwlogs@v0.43.0/cwlog_client.go:84	cwlog_client: Error occurs in PutLogEvents, will search the next token and retry the request	
{
    "kind": "exporter",
    "name": "awsemf/statsd/envoy_metrics",
    "error": "InvalidSequenceTokenException: The given sequenceToken is invalid. The next expected sequenceToken is: 49626189108498028449043455519612405404976381845984773650\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"a24432dd-4d17-44ae-b245-3877cfffabb7\"\n  },\n  ExpectedSequenceToken: \"49626189108498028449043455519612405404976381845984773650\",\n  Message_: \"The given sequenceToken is invalid. The next expected sequenceToken is: 49626189108498028449043455519612405404976381845984773650\"\n}"
}
2022-03-07T10:05:33.492Z	info	cwlogs@v0.43.0/pusher.go:298	logpusher: publish log events successfully.	
{
    "kind": "exporter",
    "name": "awsemf/statsd/envoy_metrics",
    "NumOfLogEvents": 538,
    "LogEventsSize": 255.5673828125,
    "Time": 95
}
2022-03-07T10:05:33.637Z	info	cwlogs@v0.43.0/pusher.go:298	logpusher: publish log events successfully.	
{
    "kind": "exporter",
    "name": "awsemf/statsd/envoy_metrics",
    "NumOfLogEvents": 378,
    "LogEventsSize": 179.69921875,
    "Time": 36
}
2022-03-07T10:05:33.801Z	info	awsemfexporter@v0.43.0/emf_exporter.go:185	Finish processing resource metrics	
{
    "kind": "exporter",
    "name": "awsemf/statsd/envoy_metrics",
    "labels": {}
}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x21346bc]
goroutine 99 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver/internal/translator.convertStackFramesToStackTraceStr({0xc001b211c0, 0xc001b211e0, 0xc001b211f0, 0xc0022ca00c, 0xc0022ca1f0, 0x0, 0xc001b215d0, {0xc0004bc600, 0x32, 0x3f}})
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver@v0.43.0/internal/translator/cause.go:103 +0x4dc
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver/internal/translator.addCause(0xc000f37c58, 0xc00183e010)
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver@v0.43.0/internal/translator/cause.go:82 +0x525
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver/internal/translator.populateSpan(0xc000f37c58, 0xc000185900, 0x0, 0xc00183e010)
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver@v0.43.0/internal/translator/translator.go:187 +0x468
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver/internal/translator.segToSpans({0xc001b20db0, 0xc001b20d90, 0xc00213dd28, 0xc0022970b0, 0x0, 0x0, 0x0, 0xc001b20d80, 0xc00213dd50, 0x0, ...}, ...)
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver@v0.43.0/internal/translator/translator.go:89 +0x151
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver/internal/translator.ToTraces({0xc000803000, 0x2b5a, 0x2b5a})
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver@v0.43.0/internal/translator/translator.go:75 +0x4ea
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver.(*xrayReceiver).start(0xc0002bdbc0)
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver@v0.43.0/receiver.go:123 +0x13e
created by github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver.(*xrayReceiver).Start
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver@v0.43.0/receiver.go:96 +0x7b
```

**What version did you use?**
Version: `AWS OTel Collector version: v0.16.1`

**What config did you use?**
The `otel` sidecar is configured as follows:
```
"exporters":
  "awsemf/statsd/envoy_metrics":
    "dimension_rollup_option": "NoDimensionRollup"
    "log_group_name": "/aws/ecs/perf/[svc-2, MASKED]"
    "log_stream_name": "emf/otel/statsd/envoy_metrics"
    "namespace": "perf/AppMeshEnvoy"
  "awsxray": 
{}
"processors":
  "batch/statsd/envoy_metrics":
    "timeout": "60s"
  "filter/statsd/envoy_metrics":
    "metrics":
      "include":
        "match_type": "regexp"
        "metric_names":
        - "^envoy\\.http\\.rq_total$"
        - "^envoy\\.http\\.downstream_rq_xx$"
        - "^envoy\\.http\\.downstream_rq_total$"
        - "^envoy\\.http\\.downstream_rq_time$"
        - "^envoy\\.cluster\\.upstream_cx_connect_timeout$"
        - "^envoy\\.cluster\\.upstream_rq_timeout$"
        - "^envoy\\.appmesh\\.RequestCountPerTarget$"
        - "^envoy\\.appmesh\\.TargetResponseTime$"
        - "^envoy\\.appmesh\\.HTTPCode_.+$"
"receivers":
  "awsxray":
    "endpoint": "0.0.0.0:2000"
    "transport": "udp"
  "statsd/envoy_metrics":
    "aggregation_interval": "60s"
    "endpoint": "0.0.0.0:8125"
"service":
  "pipelines":
    "metrics/statsd/envoy_metrics":
      "exporters":
      - "awsemf/statsd/envoy_metrics"
      "processors":
      - "batch/statsd/envoy_metrics"
      - "filter/statsd/envoy_metrics"
      "receivers":
      - "statsd/envoy_metrics"
    "traces/awsxray":
      "exporters":
      - "awsxray"
      "receivers":
      - "awsxray"
```

**Environment**
Docker.
Here's the source of our `Dockerfile`:
```
FROM amazonlinux

RUN yum install -y \
    procps \
    shadow-utils \
    https://aws-otel-collector.s3.amazonaws.com/amazon_linux/amd64/latest/aws-otel-collector.rpm

RUN useradd -m --uid 1337 sidecar && \
    echo "sidecar ALL=NOPASSWD: ALL" >> /etc/sudoers && \
    chown -R sidecar /opt/aws/aws-otel-collector

USER sidecar
ENV RUN_IN_CONTAINER="True"
ENV HOME="/home/sidecar"
ENTRYPOINT ["/opt/aws/aws-otel-collector/bin/aws-otel-collector"]
```

**Additional context**
- Two of the ECS Tasks failed about 1h16m after starting (I observed this on two separate tasks, one started at 8:50am and terminated at 10:06), the other started at 9:50am and terminated at 11:06. 
- Third tasks we observed failed much earlier (9:50 - 10:22).
- They all utilized around 50% of CPU and around 26% or Memory (that's according ECS Metrics in Cloudwatch) at the time of the SIGSEGV.

**Comment by jpkrohling** [comment] 2022-03-07 18:36
cc @anuraaga

**Comment by Aneurysm9** [comment] 2022-03-08 16:47
This appears to result from a [missing label or path in a stack trace frame](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/awsxrayreceiver/internal/translator/cause.go#L103).  We should add defaults for those fields when they are nil.

**Comment by willarmiros** [comment] 2022-03-09 18:18
Thanks for bringing this to our attention! We will prioritize a fix to the receiver as soon as we can. Curious @mkielar, how did you generate your X-Ray trace data? Was it with the X-Ray .NET Agent, X-Ray .NET SDK, or something else?

**Comment by mkielar** [comment] 2022-03-10 08:24
@willarmiros, the setup in the ECS Service in question was as follows:
1. Envoy Sidecar configured with `ENABLE_ENVOY_XRAY_TRACING=1` (this should make Envoy write trace segments to `localhost:2000`)
2. OTEL Sidecar configured as shown above
3. A .NET Application using X-Ray SDK.

The ECS Service was accessed like this:
```
Locust (Performance Testing Tool) 
  => Public AWS API GW (this is where X-Ray Trace ID was generated)
    => VPC Link to NLB
      => Virtual Gateway (Envoy + X-Ray Sidecar + Cloudwatch Agent Sidecar)
        => Intermediate ECS Service (Envoy + X-Ray Sidecar + Cloudwatch Agent Sidecar + .NET App)
          => The ECS Service in question (Envoy + OTEL Sidecar + .NET App)
```
A lot of there requests were completed fine, and we can see traces in X-Ray for 200 HTTP Responses, that report everything correctly. I'd expect that at some point of the load test the .NET App started failing with exceptions and the trace may have contained that information. However, the X-Ray SDK i .NET Apps is not configured to write to `localhost:2000`, so I'd expect any segments generated by the .NET App went straight to AWS X-Ray API, and not to OTEL Sidecar. Thus, the only thing that writes segments to OTEL Sidecar would be the Envoy itself, IMO.

**Comment by steven-aerts** [comment] 2022-03-11 06:42
We are also seeing this for traces send from a java app with aws xray integration to the AWS OTel Collector version: v0.16.1 and v0.17.0.

We have opened an internal support case with AWS (9741719221) where we provide debug traces with examples of traces which which trigger this issue.  So it can easily be reproduced.  The content is just a little too sensitive to put here in the open.  But feel free to contact me if you need it, we can work something out.

**Comment by mkielar** [comment] 2022-03-31 07:59
Looks like this has been released in 0.48.0, but the CHANGELOG.md edit refers to 0.47.0, and as an effect this is not mentioned either in 0.47.0 or 0.48.0 release notes:

See: 
- 0.48.0 vs 0.47.0 diff: https://github.com/open-telemetry/opentelemetry-collector-contrib/compare/v0.47.0...v0.48.0
- https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.47.0
- https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.48.0

**Comment by willarmiros** [comment] 2022-04-12 13:48
@Aneurysm9 I believe this is patched and can be closed from #8790, but it might need to be included in the above release notes

**Comment by willarmiros** [comment] 2022-05-23 13:16
@mx-psi any chance this can be closed & CHANGELOG updated since the fix was merged?

**Comment by mx-psi** [comment] 2022-05-23 13:33
Closing as completed per the comment above

**Closed by mx-psi** 2022-05-23 13:33 UTC
Labels: bug, comp:aws-xray
