### ISSUE TITLE
container image for v.0.41.0 is missing on docker hub

### ISSUE THREAD

**Issue by grzn** [open-telemetry/opentelemetry-collector-contrib#6947] opened 2021-12-25 19:06 UTC
**Describe the bug**

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by jpkrohling** [comment] 2021-12-27 09:21
This is a duplicate of #6714.

**Closed by jpkrohling** 2021-12-27 09:21 UTC
Labels: bug
