### ISSUE TITLE
[processor/metricstransform] support of regex group in new_value of label operations (e.g. add_label)

### ISSUE THREAD

**Issue by howardyoo** [open-telemetry/opentelemetry-collector-contrib#9746] opened 2022-05-05 03:41 UTC
**Problem**
I have a requirement that I need to convert a part of my metrics name to be added as a label. For example, let's say I have a metric that has a name of xyz.abc.efg. The part xyz is a prefix of the metric name, and thus I would like to convert that part into a new label called 'prefix'. Currently the rule does not proper convert the $${1} into the value, but I see `_1` as the value when the transform happens.

**Describe the solution you'd like**
In the otel config, I'd like to define a metricstransform rule that looks something like this:
```
    processors:
      metricstransform:
        transforms:
          - include: ^(\w*)\.(.*)$$
            match_type: regexp
            action: update
            new_name: $${2}
            operations:
              - action: add_label
                new_label: prefix
                new_value: $${1}
```
This will convert the metrics having the name `xyz.abc.def` into metric that has the name `abc.def` and label `prefix=xyz`

**Describe alternatives you've considered**
There is no alternatives to convert the metric names in this way, other than that you have to do it outside of otel collector.

**Additional context**
N/A

**Comment by dmitryax** [comment] 2022-05-06 17:14
Ideally it should go to transform processor, but that can take time. We don't want to introduce more feature to the processors that will be replaced by transform processor

**Comment by howardyoo** [comment] 2022-05-06 20:38
Cool, I didn’t know about the transform processor - will definitely check it out.

Howard

**Comment by dmitryax** [comment] 2022-06-24 23:06
This issue looks like a duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8121. @howardyoo feel free to reopen if I'm wrong

**Closed by dmitryax** 2022-06-24 23:06 UTC
Labels: priority:p3, proc: metricstransformprocessor
