### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference in otlpjsonconnector unmarshalling slightly incorrect OTLPJSON

### ISSUE THREAD

**Issue by gburek-fastly** [open-telemetry/opentelemetry-collector-contrib#34782] opened 2024-08-20 23:55 UTC
### Component(s)

connector/otlpjson

## Description

The otlpjson connector appears to improperly ignore an error when unmarshalling traces/log/metrics: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/otlpjsonconnector/traces.go#L55
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/otlpjsonconnector/logs.go#L54
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/otlpjsonconnector/metrics.go#L55

If the OTLP JSON data is incorrect, ie `"spans":[{"traceId":"inmyB8/qrDAAP6cV5ZFR9A==","spanId":"FcpNz02EdAs="` where the traceId and spanId are not in a hex format, the unmarshall function returns an empty trace object and error: 
```
s: "readSpan.traceId: parse trace_id:invalid length for ID, error found in #10 byte of ...|V5ZFR9A==\",\"spanId\":|..., bigger context ...|:0},\"spans\":[{\"traceId\":\"inmyB8/qrDAAP6cV5ZFR9A==\",\"spanId\":\"FcpNz02EdAs=\",\"traceState\":\"\",\"parentSp|...",}
```
Attempting to consume the empty trace object in `c.tracesConsumer.ConsumeTraces(ctx, t)` triggers a panic. 

## Steps to Reproduce

`trace.jsonl`:
```
{"resourceSpans":[{"resource":{"attributes":[{"key":"resource-attr","value":{"stringValue":"0"}},{"key":"service.name","value":{"stringValue":"starter-otel"}},{"key":"service.version","value":{"stringValue":"52"}}],"droppedAttributesCount":0},"scopeSpans":[{"scope":{"name":"go.opentelemetry.io/otel/sdk/tracer","version":"","attributes":[],"droppedAttributesCount":0},"spans":[{"traceId":"inmyB8/qrDAAP6cV5ZFR9A==","spanId":"FcpNz02EdAs=","traceState":"","parentSpanId":"","flags":256,"name":"serve","kind":"SPAN_KIND_INTERNAL","startTimeUnixNan
o":"1723610203654164405","endTimeUnixNano":"1723610203654483065","attributes":[],"droppedAttributesCount":0,"events":[],"droppedEventsCount":0,"links":[],"droppedLinksCount":0,"status":{"message":"","code":"STATUS_CODE_UNSET"}}],"schemaUrl":""}],"schemaUrl":"https://opentelemetry.io/schemas/1.7.0"}]}
```

`otel.yaml`: as below

run: 
```
$ docker run --rm --mount type=bind,source="$(pwd)",target=/etc/otelcol/ otel/opentelemetry-collector-contrib:latest --config /etc/otelcol/otel.yaml
```

## Expected Result

No panic from the otlpjson connector and a warning logged when presented with a OTLPJSON trace that cannot be unmarshalled. 

## Actual Result

```
2024-08-20T23:40:13.544Z        info    fileconsumer/file.go:256        Started watching file   {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "/etc/otelcol/trace.jsonl"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6e61ac]
```

### Collector version

v0.107.0

## Environment
OS: MacOS 14.6.1 M1 Max
colima version HEAD-9b0809d
Docker version 26.0.1, build d260a54c81
INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: aarch64
INFO[0000] runtime: docker

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    start_at: beginning
    include:
      - "/etc/otelcol/trace.jsonl"

exporters:
  debug:
    verbosity: detailed

connectors:
  otlpjson:

service:
  pipelines:
    logs/filelog:
      receivers: [filelog]
      exporters: [debug, otlpjson]
    traces/filelog:
      receivers: [otlpjson]
      exporters: [debug]
```

### Log output

```shell
2024-08-20T23:40:13.341Z        info    service@v0.107.0/service.go:116 Setting up own telemetry...
2024-08-20T23:40:13.341Z        info    service@v0.107.0/telemetry.go:96        Serving metrics {"address": ":8988", "metrics level": "Normal"}
2024-08-20T23:40:13.341Z        info    exporter@v0.107.0/builder.go:85 Development component. May change in the future.        {"kind": "exporter", "data_type": "logs", "name": "debug"}
2024-08-20T23:40:13.341Z        info    exporter@v0.107.0/builder.go:85 Development component. May change in the future.        {"kind": "exporter", "data_type": "traces", "name": "debug"}
2024-08-20T23:40:13.341Z        info    otlpjsonconnector@v0.107.0/traces.go:28 Building otlpjson connector for traces  {"kind": "connector", "name": "otlpjson", "exporter_in_pipeline": "logs", "receiver_in_pipeline": "traces"}
2024-08-20T23:40:13.342Z        info    service@v0.107.0/service.go:195 Starting otelcol-contrib...     {"Version": "0.107.0", "NumCPU": 8}
2024-08-20T23:40:13.342Z        info    extensions/extensions.go:36     Starting extensions...
2024-08-20T23:40:13.342Z        info    extensions/extensions.go:39     Extension is starting...        {"kind": "extension", "name": "pprof"}
2024-08-20T23:40:13.342Z        info    pprofextension@v0.107.0/pprofextension.go:60    Starting net/http/pprof server  {"kind": "extension", "name": "pprof", "config": {"TCPAddr":{"Endpoint":":1777","DialerConfig":{"Timeout":0}},"BlockProfileFraction":0,"MutexProfileFraction":0,"SaveToFile":""}}
2024-08-20T23:40:13.342Z        info    extensions/extensions.go:56     Extension started.      {"kind": "extension", "name": "pprof"}
2024-08-20T23:40:13.342Z        info    adapter/receiver.go:46  Starting stanza receiver        {"kind": "receiver", "name": "filelog", "data_type": "logs"}
2024-08-20T23:40:13.342Z        info    service@v0.107.0/service.go:221 Everything is ready. Begin running and processing data.
2024-08-20T23:40:13.342Z        info    localhostgate/featuregate.go:63 The default endpoints for all servers in components have changed to use localhost instead of 0.0.0.0. Disable the feature gate to temporarily revert to the previous default.   {"feature gate ID": "component.UseLocalHostAsDefaultHost"}
2024-08-20T23:40:13.544Z        info    fileconsumer/file.go:256        Started watching file   {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "/etc/otelcol/bad_trace.jsonl"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6e61ac]

goroutine 105 [running]:
go.opentelemetry.io/collector/pdata/ptrace.Traces.ResourceSpans(...)
        go.opentelemetry.io/collector/pdata@v1.13.0/ptrace/traces.go:59
go.opentelemetry.io/collector/pdata/ptrace.Traces.SpanCount({0x0?, 0x0?})
        go.opentelemetry.io/collector/pdata@v1.13.0/ptrace/traces.go:46 +0xc
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesRequest).ItemsCount(0x4002a41440?)
        go.opentelemetry.io/collector/exporter@v0.107.0/exporterhelper/traces.go:63 +0x28
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send(0x4002b53b00, {0x9412990?, 0x400023c960?}, {0x93bd498, 0x4002cd2360})
        go.opentelemetry.io/collector/exporter@v0.107.0/exporterhelper/traces.go:158 +0x50
go.opentelemetry.io/collector/exporter/exporterhelper.(*baseRequestSender).send(0x4002ce7138?, {0x9412990?, 0x400023c960?}, {0x93bd498?, 0x4002cd2360?})
        go.opentelemetry.io/collector/exporter@v0.107.0/exporterhelper/common.go:37 +0x38
go.opentelemetry.io/collector/exporter/exporterhelper.(*baseRequestSender).send(0x1?, {0x9412990?, 0x400023c960?}, {0x93bd498?, 0x4002cd2360?})
        go.opentelemetry.io/collector/exporter@v0.107.0/exporterhelper/common.go:37 +0x38
go.opentelemetry.io/collector/exporter/exporterhelper.(*baseExporter).send(0x40026e94a0, {0x9412990?, 0x400023c960?}, {0x93bd498, 0x4002cd2360})
        go.opentelemetry.io/collector/exporter@v0.107.0/exporterhelper/common.go:294 +0x48
go.opentelemetry.io/collector/exporter/exporterhelper.NewTracesRequestExporter.func1({0x9412990, 0x400023c960}, {0x0?, 0x0?})
        go.opentelemetry.io/collector/exporter@v0.107.0/exporterhelper/traces.go:134 +0x24c
go.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces(...)
        go.opentelemetry.io/collector/consumer@v0.107.0/traces.go:26
go.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces(...)
        go.opentelemetry.io/collector/consumer@v0.107.0/traces.go:26
github.com/open-telemetry/opentelemetry-collector-contrib/connector/otlpjsonconnector.(*connectorTraces).ConsumeLogs(0x4002b53c80, {0x9412990, 0x400023c960}, {0x4002cd2330?, 0x4002ce03f0?})
        github.com/open-telemetry/opentelemetry-collector-contrib/connector/otlpjsonconnector@v0.107.0/traces.go:56 +0x164
go.opentelemetry.io/collector/internal/fanoutconsumer.(*logsConsumer).ConsumeLogs(0x0?, {0x9412990, 0x400023c960}, {0x4002cd2330?, 0x4002ce03f0?})
        go.opentelemetry.io/collector@v0.107.0/internal/fanoutconsumer/logs.go:73 +0xa8
go.opentelemetry.io/collector/consumer.ConsumeLogsFunc.ConsumeLogs(...)
        go.opentelemetry.io/collector/consumer@v0.107.0/logs.go:26
github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal/consumerretry.(*logsConsumer).ConsumeLogs(0x4002b54d80, {0x9412990?, 0x400023c960?}, {0x4002cd2330?, 0x4002ce03f0?})
        github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal@v0.107.0/consumerretry/logs.go:37 +0x134
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*receiver).consumerLoop(0x4002a57d40, {0x9412990, 0x400023c960})
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.107.0/adapter/receiver.go:126 +0x140
created by github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*receiver).Start in goroutine 1
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.107.0/adapter/receiver.go:69 +0x23c
```

### Additional context

The otlpjsonfile receiver appears to silently discard the trace with badly formatted traceId and spanId when consuming the same data: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/otlpjsonfilereceiver/file.go#L157-L159 

This is more desirable behavior than a panic.

**Comment by rogercoll** [comment] 2024-08-21 10:43
I can confirm that if an error occurs when unmarshalling the log a panic occurs because the error is unhandled, see: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/otlpjsonconnector/traces.go#L55

The following PR triggers the error: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34784 (I will include the fix in the same PR)

**Comment by rogercoll** [comment] 2024-08-21 14:08
Fix: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34784

**Comment by rogercoll** [comment] 2024-09-04 15:27
@gburek-fastly Can we close this issue? It should be fixed with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34784 (main, still not released)

Let us know if the issue persisted

**Closed** 2024-09-04 15:42 UTC
Labels: bug, needs triage, connector/otlpjson
