### ISSUE TITLE
PrometheusRemoteWrite Exporter dropping metrics with empty label value

### ISSUE THREAD

**Issue by atibdialpad** [open-telemetry/opentelemetry-collector-contrib#14787] opened 2022-10-10 07:25 UTC
### What happened?

While Prometheus supports metrics with an empty label value, it seems the otel-collector PRW exporter is dropping such metrics

https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
"_A label with an empty label value is considered equivalent to a label that does not exist._"

LOG:
```
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/queued_retry.go:183
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
        go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/metrics.go:132
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
        go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/queued_retry_inmemory.go:119
go.opentelemetry.io/collector/exporter/exporterhelper/internal.consumerFunc.consume
        go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/internal/bounded_memory_queue.go:82
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func2
        go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/internal/bounded_memory_queue.go:69
2022-10-10T06:57:03.829Z        error   exporterhelper/queued_retry.go:183      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite/coordinator", "error": "Permanent error: Permanent error: remote write returned HTTP status 400 Bad Request; err = %!w(<nil>): {\"status\":\"error\",\"error\":\"bad_request_errors: count=2, last=tag value empty: index=10, name=net_host_name\"}\n", "dropped_items": 10835}
```

For the time being I can handle this via an attribute processor but would want PRW to fix this on the exporter side as well.

### Collector version

0.56

### Environment information

GKE

**Comment by atibdialpad** [comment] 2022-10-10 10:56
@bertysentry @djaglowski Perhaps we need to take care of this as  well in here  https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheus/normalize_label.go ?

**Comment by bertysentry** [comment] 2022-10-10 11:02
`normalize_label.go` handles the names of the labels only, it doesn't process their values IIRC. The issue here is about labels with empty values, and not with an empty name. `normalize_label.go` is therefore not affected by this issue. We need to look into the PRW exporter itself.

**Comment by atibdialpad** [comment] 2022-10-10 11:11
hmm fair enough. Seems  this needs to be taken  care of  while converting OTLP metrics to Prometheus Metrics. In addition to normalising the  name, we also need to  make sure that we are compatible with the other prometheus standard. i,e. treating metric labels with  empty value as non existent labels here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheusremotewrite/helper.go

**Comment by bertysentry** [comment] 2022-10-10 11:15
You're right, and actually some of the logic in `pkg/translator/prometheusremotewrite/helper.go` should be moved to `pkg/translator/prometheus`, which is common to both Prometheus exporter (**prometheusexporter** and **prometheusremotewriteexporter**). Both exporters should behave exactly the same when it comes to metrics and labels names normalization, and filtering out certain labels or not (as in this issue).

**Comment by bertysentry** [comment] 2022-10-10 11:17
Did you find where the labels with empty values were filtered out?

**Comment by atibdialpad** [comment] 2022-10-10 12:54
so the prw exporter is not dropping date. Rather the PRW destination (M3 in this case) fails and returns 400. otel prw exporter does what is expected, to not retry on 400 errors and drop the date. I think we are good here.

**Comment by bertysentry** [comment] 2022-10-10 22:21
Thank you for the update, @atibdialpad !
If confirmed, please close this issue 😉

**Closed** 2022-10-10 22:56 UTC
Labels: bug, wontfix, comp:prometheus, exporter/prometheusremotewrite, pkg/translator

**Comment by qgervacio** [comment] 2022-12-30 04:37
Hi All,

Question. This part of the log...

`"dropped_items": 10835`

should we be concerned? It looks like a lot of info are being discarded.

Thank you

**Comment by bertysentry** [comment] 2022-12-30 12:17
@qgervacio Items are dropped because they have been refused by the backend. There's nothing the exporter can do about it, we can't keep these in memory, and keep retrying forever. On 400 errors, we don't retry, which is the expected behavior.
