### ISSUE TITLE
[exporter/datadog] Datadog exporter incorrectly setting span name

### ISSUE THREAD

**Issue by bohlander** [open-telemetry/opentelemetry-collector-contrib#5261] opened 2021-09-16 22:34 UTC
**Describe the bug**
The datadog exporter is incorrectly setting the span name before sending traces to datadog. The issue is here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ac26625c2eea420d6703a15e9bd81d686fb5b8af/exporter/datadogexporter/translate_traces.go#L528

The python code it is based on returns name, not the kind, when instrumentation and kind are not initialized.  The code above defaults to kind always.

This means that in the datadog UI all spans have the operationName 'opentelemetry.unknown' if there is no span kind initialized vs. seeing the correct span name.

**Steps to reproduce**
Any code creating spans without setting kind or intstrumentation, then send to datadog

**What config did you use?**
Default datadog config

**Environment**
OS: aws otel image

**Additional context**

**Comment by gfonseca-tc** [comment] 2021-11-26 19:29
I'm facing the same issue here and it looks to me that it should always be set to the span name. I don't see how this could be set to the instrumentation library name according to the [OTel specifications](https://github.com/open-telemetry/opentelemetry-proto/blob/b43e9b18b76abf3ee040164b55b9c355217151f3/opentelemetry/proto/trace/v1/trace.proto#L125). Is this a good first issue? I can give it a try next week.

**Comment by mx-psi** [comment] 2022-07-08 15:25
AIUI this is a duplicate of #1909, so let's keep further discussion there. The default behavior can be overriden by using the `traces::span_name_as_resource_name` option https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4d5ee4a1b9ec41b182cd4bd6990e3e26a6ebb535/exporter/datadogexporter/example/config.yaml#L217-L222

**Closed by mx-psi** 2022-07-08 15:25 UTC
Labels: bug, exporter/datadog, data:traces
