### ISSUE TITLE
Windows 2008R2 Installation of otel-0.91.0

### ISSUE THREAD

**Issue by Nannymeta** [open-telemetry/opentelemetry-collector-contrib#30327] opened 2024-01-08 18:39 UTC
## Description
Hello,

I've tried to install otel-0.91.0 on a Windows 2008R2

Error : Exception 0xc0000005 0x8 0x0 0x0 PC=0x0 runtime.asmstdcall()

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/103997330/a2f10801-912b-4d83-a2ed-905f381d3dca)

I've been looking in documentation it seems all windows are compatible , no requirements needed

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/103997330/fa03c789-0c36-4dcc-b85e-898e6793cb1e)

If anybody has an idea it would be great thanks

### Collector version

0.91.0

## Environment
OS: Windows 2008R2

### Log output

```shell
Exception 0xc0000005 0x8 0x0 0x0 PC=0x0 runtime.asmstdcall()
```

**Comment by crobert-1** [comment] 2024-01-08 22:39
It looks like from our [platform support page](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/platform-support.md#platform-support) we are tied to golang's versioning for support, and `go 1.20` still [supports this version of Windows](https://go.dev/wiki/MinimumRequirements#windowswindows), from what I can tell ([another source](https://go.dev/doc/go1.20#windows)).

From a bit of google searching this may be a `go` related issue, or even environment, not necessarily the collector. 

_I don't have access to a Windows 2008R2 environment at this time to try to reproduce._

**Comment by mx-psi** [comment] 2024-01-09 15:45
@Nannymeta are you using the pre-built binaries or building from source yourself? Our prebuilt binaries are built with Go 1.21, so they don't support Windows 2008R2, as noted in the Go 1.20 release notes:

> Go 1.20 is the last release that will run on any release of Windows 7, 8, Server 2008 and Server 2012. Go 1.21 will require at least Windows 10 or Server 2016.

You can build the Collector from source with a Go 1.20 compiler and this should make it work. Note that once Go 1.22 is released, we will drop support for Go 1.20 and thus running the Collector on Windows 2008R2 will become much harder.

**Comment by crobert-1** [comment] 2024-01-09 16:31
Adding more context to @mx-psi's comment, [here's the reference](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/832f85c5f7c85ada0da7cfab8cc48ea456bb8a4e/go.mod#L3) to the go version the collector is built using. I was only looking at contrib's [go version](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f8df25297f6908657b40cad14baeaac15363b150/go.mod#L3), which is the [minimum supported version](https://go.dev/doc/modules/gomod-ref#go), not necessarily what version is being used.

**Comment by pjanotti** [comment] 2024-01-22 22:40
[Windows 2008 reached end of Extended Security Update on 01/09/2024](https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2008), given that I recommend closing the issue since there is already a grace period until Go 1.22 is released and users should be encouraged to move away from Windows 2008.

**Comment by mx-psi** [comment] 2024-01-23 11:33
I am going to close as not planned as indeed we will be dropping support for this soon. Nonetheless, I would be okay with accepting PRs related to this if they e.g. add some build-tag-guarded code that re-adds support, with the expectation that we won't be able to test this or support it.

**Closed by mx-psi** 2024-01-23 11:33 UTC
Labels: question, waiting for author, os:windows

**Comment by mx-psi** [comment] 2024-02-07 08:48
#31105 will drop support for this
