### ISSUE TITLE
[processor/k8sattributes] Retrieve pods at the namespace scope

### ISSUE THREAD

**Issue by edenkoveshi** [open-telemetry/opentelemetry-collector-contrib#14742] opened 2022-10-06 08:39 UTC
### Is your feature request related to a problem? Please describe.

I want to extract attributes from pods in a single namespace, and I don't really need a cluster role binding for that
What I want is to extract pods attributes with a namespace RoleBinding
Should be quite easy
I can help implementing this if needed

### Describe the solution you'd like

Change the Kubernetes client to fetch items at the namespace level if namespace is defined

**Comment by geukhan** [comment] 2022-11-17 21:12
Hi @edenkoveshi, I have a few questions if you don't mind:

- What attributes do you want to extract?
- Do you mean you want to extract "attributes" of a pod within a specific namespace, a namespace name being "RoleBinding"? I am not sure if I got that.
- What do you mean by not needing a cluster role binding, why would you need a role binding in the first place?

I appreciate if you can elaborate a little bit. I am recently getting into OpenTelemetry, and would like to start contributing, it would help me if you can explain me what you need with more details.

**Comment by edenkoveshi** [comment] 2022-11-17 21:30
From the documentation 
`The processor uses the kubernetes API to discover all pods running in a cluster, keeps a record of their IP addresses, pod UIDs and interesting metadata.`
It queries the API for pods within the entire cluster, which requires ClusterRoleBinding

I want to achieve the same thing but not for pods in the entire cluster (I only want some labels actually but it doesn't really matter), but for selected namespaces, and use namespaced RoleBindings to avoid over-priveliging

**Comment by geukhan** [comment] 2022-11-17 21:37
@edenkoveshi thanks, this explains everything I needed to understand. I will fiddle with it and will let you know if I end up creating a PR to address this (unless someone who is already member picks it up before that). Cheers!

**Comment by fatsheep9146** [comment] 2022-11-18 01:57
I think this is also block by #15651, we should solve that first. cc @dmitryax

**Comment by gouslu** [comment] 2022-12-09 17:24
I have been getting myself familiarized with otel collector, I have been debugging it in my local kind cluster. However, I can't seem to figure this one thing out, I tried different configs and it didn't help. When I am debugging .../processor/k8sattributesprocessor/processor.go and hit line 151, the "attrs" does not have "k8s.container.name" and container name is empty.  I tried different configurations and could not find a solution, maybe someone here can help?

Like I mentioned, I am still new to go and Open Telemetry and working on getting up to speed and becoming a contributor, so I appreciate your patience and help!

values when debugging:
![image](https://user-images.githubusercontent.com/7251174/206757954-9ede7603-9956-4951-85a2-f167efffea6a.png)

current collector config:
![image](https://user-images.githubusercontent.com/7251174/206757984-f2e30319-4861-4698-bc6a-407826f1ec90.png)

**Comment by fatsheep9146** [comment] 2023-02-15 03:35
I think is issue is ready to be implemented, since k8sattributeprocessor e2e is enabled? 
@dmitryax

**Comment by dmitryax** [comment] 2023-02-15 06:38
Yes, I think it should be good to go with this enhancement

**Comment by dmitryax** [comment] 2023-06-22 16:30
@pgoringe, thanks for your comment. @fatsheep9146, do you interest in implementing this by chance? Otherwise, any help is appreciated.

**Comment by Exactol** [comment] 2023-10-25 18:46
I was able to run the Collector within a namespace on an older release ([v0.74.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.74.0)), but after upgrading to the latest version I'm seeing errors in the log about: "failed to list \*v1.Namespace: namespaces "kube-system" is forbidden. User "***" cannot list resource "namespaces" in API group "" at the cluster scope

I think there is a regression in [v0.83.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.83.0), possibly caused by the change to add [k8s.cluster.uid](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21974)

**Comment by jinja2** [comment] 2023-10-26 22:42
Yeah, the `k8s.cluster.uid` change introduces namespace lookup even when the attribute is not enabled (it is disabled by default). I think the processor will still work but there'll be a bunch of errors complaining about not able to list namespace. Let me try a PR to fix this.

Regarding the original ask, once the aforementioned issue is fixed, users can indeed use the processor with Rolebinding to extract labels/annotations for pods running in the collector's namespace only. You need to set the namespace filter for this.
```
      k8sattributes:
        filter:
          namespace: COLLECTOR_NAMESPACE
```

One caveat here, even with the namespace filter set, the processor currently cannot extract metadata from the namespace (doesn't seem to pass the filter when ns is queried). I think the issue should be updated to fix this. Ideally, the processor when run with the `filter.namespace` set to the namespace it is running in, should be able to handle extracting labels/annotations from the namespace and pods within the ns without needing any cluster-scoped access.

**Comment by jinja2** [comment] 2024-02-08 23:19
@hkailantzis this one fell off my radar, but I should be able to look into this next week

**Comment by samuellvicente** [comment] 2024-03-08 16:01
Adding interest in this, I have the same issue where my cluster is shared between teams and we use namespaces to isolate things, it would be great if we could scope the processor to just a namespace.

**Comment by hkailantzis** [comment] 2024-03-12 15:17
Hi @jinja2 , are there any updates on this ? Is there something else blocking it ? Thanks in advance. :).

**Comment by jinja2** [comment] 2024-03-12 16:45
There is a PR open, hopefully it'll make it in in 0.97 release.

**Comment by atoulme** [comment] 2024-03-26 20:26
OK to close as the PR is now merged?

**Closed** 2024-03-26 21:22 UTC
Labels: enhancement, help wanted, priority:p2, processor/k8sattributes
