### ISSUE TITLE
k8sclusterreceiver unit test fails

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#1049] opened 2020-09-17 23:35 UTC
Test fails with the following (see https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/4063/workflows/bd3d5f91-9f94-4749-acdf-df16fcf264c9/jobs/28477):
```
running go unit test ./... + coverage in /home/circleci/project/receiver/k8sclusterreceiver
E0917 18:06:36.434122   11164 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 85 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x228f040, 0x36a6cb0)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.19.1/pkg/util/runtime/runtime.go:74 +0xc4
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.19.1/pkg/util/runtime/runtime.go:48 +0xbe
panic(0x228f040, 0x36a6cb0)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0001c8340, 0xc000610090, 0xc0006e8060, 0xc000253a60, 0x0, 0x0)
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.19.1/tools/cache/reflector.go:307 +0xf65
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001c8340, 0xc0006e8060, 0x0, 0x0)
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.19.1/tools/cache/reflector.go:348 +0x257
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.19.1/tools/cache/reflector.go:209 +0x54
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00049d698)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.19.1/pkg/util/wait/wait.go:155 +0x76
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000253e98, 0x27d2e80, 0xc00034c000, 0x1, 0xc0006e8060)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.19.1/pkg/util/wait/wait.go:156 +0xb4
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001c8340, 0xc0006e8060)
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.19.1/tools/cache/reflector.go:208 +0x21b
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.19.1/pkg/util/wait/wait.go:56 +0x46
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0005f8160, 0xc0002e40a0)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.19.1/pkg/util/wait/wait.go:73 +0x6b
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.19.1/pkg/util/wait/wait.go:71 +0x70
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference

goroutine 85 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.19.1/pkg/util/runtime/runtime.go:55 +0x169
panic(0x228f040, 0x36a6cb0)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0001c8340, 0xc000610090, 0xc0006e8060, 0xc000253a60, 0x0, 0x0)
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.19.1/tools/cache/reflector.go:307 +0xf65
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001c8340, 0xc0006e8060, 0x0, 0x0)
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.19.1/tools/cache/reflector.go:348 +0x257
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.19.1/tools/cache/reflector.go:209 +0x54
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00049d698)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.19.1/pkg/util/wait/wait.go:155 +0x76
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000253e98, 0x27d2e80, 0xc00034c000, 0x1, 0xc0006e8060)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.19.1/pkg/util/wait/wait.go:156 +0xb4
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001c8340, 0xc0006e8060)
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.19.1/tools/cache/reflector.go:208 +0x21b
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.19.1/pkg/util/wait/wait.go:56 +0x46
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0005f8160, 0xc0002e40a0)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.19.1/pkg/util/wait/wait.go:73 +0x6b
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.19.1/pkg/util/wait/wait.go:71 +0x70
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver	0.171s
```

**Comment by tigrannajaryan** [comment] 2020-09-17 23:36
@asuresh4 can you please have a look?

**Comment by asuresh4** [comment] 2020-09-18 02:54
@tigrannajaryan - I believe this was caused by this line https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/receiver/k8sclusterreceiver/watcher.go#L103, where `ctx.Done()` returns `nil`. I was not able to reproduce this as is though. I passed in `nil` to the above line and was able to get the same stack trace. Based on go docs `ctx.Done` returns `nil` only when ctx can never be cancelled. Do you know of other cases where this could happen?

**Comment by tigrannajaryan** [comment] 2020-09-18 13:43
>Based on go docs `ctx.Done` returns `nil` only when ctx can never be cancelled. Do you know of other cases where this could happen?

No, I don't.

**Comment by asuresh4** [comment] 2020-11-04 21:34
I've not been able to reproduce this error locally and also it appears like this failure was a one off (I was not able to find other occurrences on CircleCI). We've also upgraded the k8s API to `1.19.3`, if at all this error had something to do with the specific version of the API. 

@tigrannajaryan - can we close this issue for now? I will address if we see this again in the future.

**Closed** 2020-11-05 02:59 UTC
Labels: bug
