### ISSUE TITLE
receivercreator passing `endpoint` to receiver config even if not specified

### ISSUE THREAD

**Issue by andreas-ahman** [open-telemetry/opentelemetry-collector-contrib#5081] opened 2021-09-06 07:23 UTC
When using receivercreator to create a prometheusreceiver, the prometheus receiver crashes during startup complaining that it cannot parse config, invalid keys endpoint

```
prometheus receiver failed to parse config: 1 error(s) decoding:\n\n* '' has invalid keys: endpoint"}
```

This even if endpoint is not configured in the prometheus config section

```
receivers:
  receiver_creator:
    watch_observers: [k8s_observer]
    receivers:
      prometheus:
        rule: type == "pod" && labels["agent.signalfx.com/scrape"] == "true"
        config:
          scrape_configs:
          - job_name: k8s
            scrape_interval: 10s
            static_configs:
            - targets:
              - '`endpoint`:`"agent.signalfx.com/port" in labels ? labels["agent.signalfx.com/port"] : 9090`'
```

**Steps to reproduce**
Try to start a prometheusreceiver

**What did you expect to see?**
Endpoint not passed into prometheus config

**What did you see instead?**
`prometheus receiver failed to parse config: 1 error(s) decoding:\n\n* '' has invalid keys: endpoint"}`

**What version did you use?**
Version: v0.34.0

**What config did you use?**
Config:

```
receivers:
  receiver_creator:
    watch_observers: [k8s_observer]
    receivers:
      prometheus:
        rule: type == "pod" && labels["agent.signalfx.com/scrape"] == "true"
        config:
          scrape_configs:
          - job_name: k8s
            scrape_interval: 10s
            static_configs:
            - targets:
              - '`endpoint`:`"agent.signalfx.com/port" in labels ? labels["agent.signalfx.com/port"] : 9090`'
```

**Environment**
OS: GKE

**Comment by CoderPoet** [comment] 2022-07-13 07:46
+1

**Comment by sirianni** [comment] 2023-02-27 20:08
This seems like a dupe of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7381 which was fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18641

**Comment by atoulme** [comment] 2023-03-04 07:24
Thanks @sirianni closing as duplicate.

**Closed by atoulme** 2023-03-04 07:24 UTC
Labels: bug, receiver/receivercreator
