### ISSUE TITLE
Library instrumentation stays as Datadog in operation name (or Primary Operation). 

### ISSUE THREAD

**Issue by nicoroms** [open-telemetry/opentelemetry-collector-contrib#30812] opened 2024-01-28 09:30 UTC
### Component(s)

exporter/datadog, receiver/datadog

## Description
Traces receiver comes with InstrumentationScope Datadog 4.20.0 causing that datadog exporter create traces with Datadog instead of original library (like express, http, netty, etc). This change causes that backend recognize as original operation name.
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/57744706/d1ef255c-7638-43e1-9daa-8b7c06fae043)

And this happen in datadog traces view:
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/57744706/f1f479ef-3022-4f8c-8243-bb00c6f778fe)

Metrics created in datadog are called with Datadog.server too
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/57744706/3116dfdc-dbe5-4026-b3ac-1ec32fb64b0f)

** span_name_as_resource_name on the exporter side seems to fix this behaviour on the traces, but metrics generated (like trace.express.request.hits)  stay with the name trace.Datadog.server.hits, which is wrong.

## Steps to Reproduce
Instrument app with datadog sdk and otlp collector with datadog receiver, any export to datadog will cause this

## Expected Result
Instrumentation Scope should be the same as origin and not one created by datadog receiver or a config to keep the same behaviour of traces.span_name_as_resource_name in metrics.

### Collector version

0.93.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  datadog:
    endpoint: ${POD_IP}:8126
    read_timeout: 60s
exporters:
  datadog:
    traces:
#      span_name_as_resource_name: true
    api:
      key: 

processors:
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s


extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [datadog]
      processors: [ batch]
      exporters: [datadog]
```

**Comment by mx-psi** [comment] 2024-03-08 10:19
Thanks for filing this @nicoroms. This is probably related to #1909 but I will keep this open until we verify this.

**Comment by mx-psi** [comment] 2024-03-08 11:49
I am going to close this as a duplicate of #1909 indeed. This

> ** span_name_as_resource_name on the exporter side seems to fix this behaviour on the traces, but metrics generated (like trace.express.request.hits) stay with the name trace.Datadog.server.hits, which is wrong.

is not mentioned already on the original issue so I will highlight it in our internal tracking for this issue, but otherwise this is a particular manifestation of the general issue on #1909

**Closed by mx-psi** 2024-03-08 11:49 UTC
Labels: bug, exporter/datadog, data:traces, needs triage, receiver/datadog
