### ISSUE TITLE
Add CircleCI check that all modules depends on the same collector version

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#576] opened 2020-07-29 03:08 UTC
**Is your feature request related to a problem? Please describe.**
When merging new PRs they can have a different version for the collector which causes inconsistencies.

**Describe the solution you'd like**
A small script that ensures all versions of the collector are the same.

**Additional context**
Discovered during merging old PRs.

**Comment by mx-psi** [comment] 2022-05-13 11:37
This is a duplicate of #8546, which was fixed by #9112

**Closed by mx-psi** 2022-05-13 11:37 UTC
Labels: enhancement, ci-cd
