### ISSUE TITLE
Resource 'global' with Prometheus receiver and Stackdriver exporter

### ISSUE THREAD

**Issue by ocervell** [open-telemetry/opentelemetry-collector-contrib#709] opened 2020-08-13 19:53 UTC
Here is the OTEL agent config:
```
    receivers:
        opencensus:
        prometheus:
            config:
                scrape_configs:
                - job_name: 'kubernetes-pods'
                  scrape_interval: 10s
                  kubernetes_sd_configs:
                  - role: pod
                    # select only pods on the same host as the agent to prevent
                    # duplication of metrics
                    selectors:
                      - role: pod
                        field: "spec.nodeName=${NODE_NAME}"
                  relabel_configs:
                    - source_labels: [__meta_kubernetes_pod_container_port_name]
                      action: keep
                      regex: (.*-metrics)
                    - source_labels: [__meta_kubernetes_namespace]
                      action: replace
                      target_label: kubernetes_namespace
                    - source_labels: [__meta_kubernetes_pod_name]
                      action: replace
                      target_label: kubernetes_pod_name
                    - source_labels: [__meta_kubernetes_pod_container_name]
                      action: replace
                      target_label: kubernetes_container_name
                    - source_labels: [__meta_kubernetes_pod_host_ip]
                      action: replace
                      target_label: kubernetes_pod_host_ip
                    - source_labels: [__meta_kubernetes_pod_label_name]
                      action: replace
                      target_label: app

                    # Converts all pod labels to metric labels.
                    # Warning: can increase number of labels significantly !
                    # - action: labelmap
                    #   regex: __meta_kubernetes_pod_label_(.+)

    exporters:
        logging:
            loglevel: info
        stackdriver:
          resource_mappings:
          - source_type: global
            target_type: k8s_container
            label_mappings:
              - source_key: contrib.opencensus.io/exporter/stackdriver/project_id
                target_key: project_id
                optional: true

              - source_key: contrib.opencensus.io/exporter/stackdriver/location
                target_key: location
                optional: true

              - source_key: contrib.opencensus.io/exporter/stackdriver/cluster_name
                target_key: cluster_name
                optional: true

              - source_key: contrib.opencensus.io/exporter/stackdriver/generic_task/namespace
                target_key: namespace_name
                optional: true

    processors:
        batch:
        queued_retry:
        memory_limiter:
          ballast_size_mib: 165 # Same as --mem-ballast-size-mib CLI argument
          limit_mib: 400        # 80% of maximum memory up to 2G
          spike_limit_mib: 20   # 25% of limit up to 2G
          check_interval: 5s
        filter:
          metrics:
            include:
              match_type: regexp
              metric_names:
                - otelcol_.*            # allow metrics from the OpenTelemetry collector
                - flask_app.*           # allow metrics from Flask app
                - custom_metric_example # allow metric from custom-metrics-example
    extensions:
        health_check:
    service:
        extensions: [health_check]
        pipelines:
            traces:
                receivers: [opencensus]
                processors: [memory_limiter, batch, queued_retry]
                exporters: [stackdriver, logging]
            metrics:
                receivers: [prometheus, opencensus]
                processors: [memory_limiter, filter]
                exporters: [stackdriver, logging]
```

I'm receiving the error from the Stackdriver exporter, which fails to convert the resource 'global' to 'k8s_container':
```
{"level":"info","ts":1597348238.9033852,"caller":"scrape/scrape.go:972","msg":"","component_kind":"receiver","component_type":"prometheus","component_name":"prometheus","level":"
debug","scrape_pool":"kubernetes-pods","target":"http://10.52.1.62:8888/metrics","msg":"Append failed","err":"rpc error: code = InvalidArgument desc = One or more TimeSeries coul
d not be written: The set of resource labels is incomplete. Missing labels: (cluster_name container_name location namespace_name pod_name).: timeSeries[0-42]"}
```

I think we might need a way to turn metric labels into resource labels in the Stackdriver exporter.

**Comment by nilebox** [comment] 2020-12-10 03:50
The error clearly says that you're missing labels: 
```
Missing labels: (cluster_name container_name location namespace_name pod_name)
```

Let's have a look at the "cluster_name" for example.
You have a mapping in the config:
```
              - source_key: contrib.opencensus.io/exporter/stackdriver/cluster_name
                target_key: cluster_name
                optional: true
```

But where is the `contrib.opencensus.io/exporter/stackdriver/cluster_name` source resource attribute being produced?
Does it get produced by the OpenCensus receiver?
I'd suggest to use the [Logging exporter ](https://github.com/open-telemetry/opentelemetry-collector/tree/master/exporter/loggingexporter)for debugging (instead or alongside the Stackdriver exporter), to see which attributes are present in scraped metrics.

**Comment by nilebox** [comment] 2020-12-10 07:09
I'm closing the issue since it doesn't have enough details on what is the exact issue and how to reproduce it.

Feel free to reopen it and add missing details.

**Closed by nilebox** 2020-12-10 07:09 UTC
Labels: bug, priority:p2, spec:metrics
