### ISSUE TITLE
Make gendependabot causes removal of components when adding a new component

### ISSUE THREAD

**Issue by adrielp** [open-telemetry/opentelemetry-collector-contrib#24363] opened 2023-07-18 03:25 UTC
## Description
I was adding a new receiver component and my pr showed up as removing the ssh receiver from the dependebot.yaml after running `make gendependabot`. The question as to why was brought up in [this pull request](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23225#discussion_r1264020532). This command is something I have to run to be able to pass all the checks and merge the PR. So I investigated why. 

Quote from my original findings:

> Looking at this more, it looks to have been removed as a sideeffect of having placed a limit on [make gendependabot](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/Makefile#L144-L169)
> As I understand, it's going to iterate through all the mod dirs, and it's going to stop appending to the generate file once you've got 220 entries. Looks like the addition of this component is bumping the other component out of place.
> The [build and test workflow](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/workflows/build-and-test.yml#L209-L212) is going to run make gendependabot every time and error out if the diff is different. That's why the checks pass with the removal of that component, but don't pass if I haven't run the command & committed the change.

I couldn't find any specific reference in GitHub's docs about a limit to 220 entries though. We should be able to add all components managed by dependabot. I do wonder if Renovate has a similar limit.

## Steps to Reproduce
* add a new component that being with a letter earlier in the alphabet
* run make gendependabot
* look at the diff

## Expected Result
* does not remove a component from the dependabot.yaml on regeneration

## Actual Result
* removes a component from the dependabot.yaml on regeneration

### Collector version

v0.81.0

### Environment information

This is a make issue

### OpenTelemetry Collector configuration

```yaml
n/a
```

### Log output

```shell
n/a
```

### Additional context

See this comment: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23225#discussion_r1264291324

**Comment by mx-psi** [comment] 2023-07-18 13:30
Closing this as a duplicate of #19410

**Closed by mx-psi** 2023-07-18 13:30 UTC
Labels: bug, needs triage
