### ISSUE TITLE
[chore] Fix new lint issues with golangci-lint v1.56.1

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector-contrib#31240] opened 2024-02-13 20:57 UTC
### Describe the issue you're reporting

The version upgrade of golangci https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31216 surfaced lots of new lint errors, e.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7892240476/job/21538478567?pr=31216. Need to fix these lint errors to unblock https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31216.

**Comment by songy23** [comment] 2024-02-13 20:58
To reproduce: checkout branch `renovate/github.com-golangci-golangci-lint-1.x` then run `make lint`.

**Comment by crobert-1** [comment] 2024-02-26 20:51
_Removing `needs triage` as it's been worked on by a project maintainer._

**Comment by led0nk** [comment] 2024-03-25 12:20
@songy23 i cannot reproduce any other linting errors, so it seems like it's solved for now

**Comment by songy23** [comment] 2024-03-25 12:34
There are still linter failures, see https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8341482938/job/22827781178?pr=31830

**Comment by mx-psi** [comment] 2024-03-25 16:32
One more error to go: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8423315275/job/23064935533

**Comment by songy23** [comment] 2024-03-25 16:41
^ the one in opampsupervisor is expected to be fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30237.

**Comment by led0nk** [comment] 2024-03-25 17:00
> ^ the one in opampsupervisor is expected to be fixed in #30237.

actually the one won't be fixed through #30237 (as you can see line 243 isn't touched)


There were other one's which would've been obsolete.
Should've seen this one earlier, sorry for that - just opened PR to quickly fix this

**Comment by led0nk** [comment] 2024-03-25 20:06
@songy23 is there any way to preproduce linting with the updated linter in  #31830 ?

I think it should be more efficient to run this locally one by one , so we can solve this in a single PR.

**Comment by songy23** [comment] 2024-03-26 00:43
@led0nk Looks like I had a typo in my previous comment. You can run `make golint` after checkout the branch
```
git checkout renovate/github.com-golangci-golangci-lint-1.x
make golint
```

The command takes long and you'll need to run it after each fix. Here's what I got with running ^
```
INFO [runner] linters took 988.335125ms with stages: goanalysis_metalinter: 987.281709ms 
chronyreceiver/factory.go:41:32: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
		scraperhelper.WithStart(func(ctx context.Context, host component.Host) error {
		                             ^

```

And thanks for helping out here!

**Comment by led0nk** [comment] 2024-03-27 17:24
hopefully this should fix the remaning errors for PR #31830 

i don't get any more errors from linting

**Comment by led0nk** [comment] 2024-03-27 18:23
Okay i fixed this with recent PRs and no more linting errors on updated renovate-branch.
I hope there are no PRs in the meantime and #31830 won't get any errors.. :smiling_face_with_tear:

**Comment by songy23** [comment] 2024-03-27 19:59
All good, cheers @led0nk

**Comment by dmitryax** [comment] 2024-03-27 20:16
Thank you, @led0nk!

**Closed** 2024-03-27 20:15 UTC
Labels: help wanted, good first issue, ci-cd
