### ISSUE TITLE
Please enable use of  k8sclusterreceiver without a ClusterRole/Binding

### ISSUE THREAD

**Issue by lakamsani** [open-telemetry/opentelemetry-collector-contrib#29010] opened 2023-11-07 20:29 UTC
### Component(s)

processor/k8sattributes, receiver/k8scluster

### Is your feature request related to a problem? Please describe.

ref: https://cloud-native.slack.com/archives/C01N6P7KR6W/p1690863359759259

k8s workload teams don't always have cluster-level permissions. They do have namespace-level permissions. 

### Describe the solution you'd like

Similar to how https://github.com/kubernetes/kube-state-metrics#limited-privileges-environment works, it would be great to have both  [receiver/k8sclusterreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver#rbac) and `processor/k8sattributesprocessor`  work without a ClusterRole.  The data they collect will be limited to the namespace and that is ok. 

### Describe alternatives you've considered

buy the k8s cluster admin some beer and get that ClusterRole 🙂

**Comment by crobert-1** [comment] 2023-11-07 21:53
Hello @lakamsani, I believe this is a duplicate of #9401. Please let me know if I've misunderstood, otherwise feel free to add more information there.

**Closed by crobert-1** 2023-11-07 21:53 UTC
Labels: enhancement, processor/k8sattributes, receiver/k8scluster, needs triage
