### ISSUE TITLE
Support byte stream log collection

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#3267] opened 2021-04-28 13:52 UTC
Logs are today assumed to be UTF text, which is split into records using some delimiter pattern. In some cases it is useful to treat the logs files simply as byte streams with unspecified encoding. It would be useful to have this capability added.

To enable it we need the following:
1. Support binary data type (byte slice). It needs to be added to OTLP as one of the data types for AnyValue.
1. For `filelog` when `encoding=nop` populate the `Body` with binary data type instead of string data type (which according to OTLP's Protobuf requirements is limited to valid UTF-8 strings.
1. Allow disabling splitting of log entires (via `multiline` setting?). Split into chunks by honouring `max_log_size` setting to limit the size of each individual record.
1. Optionally: store the starting position of the chunk in the stream so that the stream can be reconstructed correctly if log records are delivered to the final destination out of order.

**Comment by tigrannajaryan** [comment] 2021-04-28 13:53
@djaglowski what do you think, are requirements 2 and 3 possible to implement?

**Comment by djaglowski** [comment] 2021-05-03 17:40
@tigrannajaryan This should be possible. 

> 1. Support binary data type (byte slice). It needs to be added to OTLP as one of the data types for AnyValue.

👍 `entry.Entry.Body`is of type `interface{}`, so will be ready once OTLP is updated.

> 2. For filelog when encoding=nop populate the Body with binary data type instead of string data type (which according to OTLP's Protobuf requirements is limited to valid UTF-8 strings.

`encoding=nop` is currently the default, so we need to be clear on whether this will be an additive change, a change to default behavior, or even a removal of current behavior. I think the current default behavior (including newline splitting) is the best for new users because it yields easily understandable results with minimum configuration. That said, it all depends on how they are likely to view the logs downstream, and whether those logs are rendered in a human readable fashion. 

My initial thought here is that we should leave `encoding=nop` alone, and add a new setting (i.e. `encoding=raw` or `encoding=bytes`) for this use case. 

> 3. Allow disabling splitting of log entires (via multiline setting?). Split into chunks by honouring max_log_size setting to limit the size of each individual record.

I like the `max_log_size` idea. There is at least one additional consideration here, which is what the expected behavior would be if the final bytes of a file do not reach `max_log_size`. As a starting point, I think we should just consume any available bytes. However, this may be a little too greedy in the common case where the log is still active.

In any case, we'll need to implement a new `bufio.SplitFunc`, but this should not be too difficult. Several custom implementations are already present in [line_splitter.go](https://github.com/open-telemetry/opentelemetry-log-collection/blob/9326d62e131aa529423a6c75c4a8b68259cb7f7a/operator/builtin/input/file/line_splitter.go#L27). 

> 4. Optionally: store the starting position of the chunk in the stream so that the stream can be reconstructed correctly if log records are delivered to the final destination out of order.

Makes sense. Should be easy enough - probably just add an `offset` attribute.

**Comment by tigrannajaryan** [comment] 2021-05-03 17:57
@djaglowski  Great, thanks for validating the idea. 

> `encoding=nop` is currently the default, so we need to be clear on whether this will be an additive change, a change to default behavior, or even a removal of current behavior.

What happens currently when `encoding=nop` and if the file contains a byte sequence that is not a valid UTF8? Do we just put the bytes as is in the Body's `StringValue`? If so I think it is not a correct approach since Protobuf requires strings to be UTF8. So, we may need to rethink this anyway. Perhaps make UTF8 the default? What does `encoding=utf-8` do? Does it attempt to validate or anything?

**Comment by maxgolov** [comment] 2021-05-06 23:53
I like the proposal of `encoding=raw` or `encoding=bytes` . Would there be a practical limit on how big the data should be, i.e. `max_log_size` - does it impose an upper boundary? Can this boundary be at least `64KB` and preferably within megabytes range? For bigger-sized blobs the clients should probably use some form of alternate blob storage / blob collector...

**Comment by djaglowski** [comment] 2021-09-16 21:29
This functionality has now been added to the log-collection library, and will be included in the next release.

**Closed by djaglowski** 2021-09-16 21:29 UTC
