### ISSUE TITLE
[processor/tailsamplingprocessor] move it to a stable component

### ISSUE THREAD

**Issue by alexfdz** [open-telemetry/opentelemetry-collector-contrib#10832] opened 2022-06-08 05:34 UTC
**Is your feature request related to a problem? Please describe.**
`tailsamplingprocessor` has been in beta for a while, is there any issue or missing feature we can help with?

It probably won't be included in distributions like aws-otel-collector if is not considered stable.

**Describe the solution you'd like**
`tailsamplingprocessor` to be considered a stable component. 

**Describe alternatives you've considered**

**Additional context**
Probably related to #1797

**Comment by djaglowski** [comment] 2022-06-10 17:28
cc: @jpkrohling as code owner

**Comment by jpkrohling** [comment] 2022-07-05 11:59
I'm aware of a potential minimal leak I found while putting this under extreme pressure. Unfortunately, I wasn't able to find the cause of this potential leak. Despite that, I think we can indeed move it to stable, as I'm aware of people using it in production and haven't experienced this potential problem.

**Comment by jpkrohling** [comment] 2022-07-13 21:02
We are currently having discussions on what it means to be "stable". Given that "stable" might mean strict rules on the configuration properties, we might not want to move this to stable.

**Comment by jpkrohling** [comment] 2022-08-08 16:45
I'm closing this as I don't think we are ready to declare this stable.

**Closed by jpkrohling** 2022-08-08 16:45 UTC
Labels: processor/tailsampling
