### ISSUE TITLE
Unable to get process details for CPU and memory usage

### ISSUE THREAD

**Issue by bhupenbisht** [open-telemetry/opentelemetry-collector-contrib#31177] opened 2024-02-11 11:53 UTC
### Component(s)

cmd/otelcontribcol

### Describe the issue you're reporting

Hi,

I am using otel contrib for window host. Getting all host metrics i.e CPU,disk. But Unable to get process details for CPU and memory usage.
Please advise
Regards
Bhupender

**Comment by astencel-sumo** [comment] 2024-02-13 23:37
Can you please share your collector configuration that you use?

**Comment by bhupenbisht** [comment] 2024-02-14 06:06
Hi astencel i am using otel contrib0. 94 version for my windows and linux maching. Using below configuration for both machine.

exporters:
  prometheus:
    endpoint: "https://xxxx.cloud.example.myoffice
    headers: {"auth:xxxxxxxx"}

  logging:
   verbosity: detailed

extension:
  health_check:

receivers:

  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
        metrics:
          system.cpu.time:
            enabled: true
          system.cpu.utilization:
            enabled: true

    disk:
      metrics:
        system.disk.io:
          enabled: true
        system.disk.operation:
          enabled: true

    filesystem:
      metrics:
        system.filesystem.usage:
          enabled: true
        system.filesystem.utilization:
         enabled: true

    memory:
      metrics:
        system.memory.usage:
          enabled: true
        system.memory.utilization:
          enabled: true

    network:
      metrics:
        system.network.packets:
          enabled: true

    process:
      metrics:
        process.cpu.time:
          enabled: true
        process.cpu.utilization:
          enabled: true
        process.memory.usage:
          enabled: true
        process.disk.io:
          enabled: true
        process.threads:
          enabled: true
        process.handles:
          enabled: true
        process.disk.operations:
          enabled: true
     
    processes:
      metrics:
        system.processes.created:
          enabled: true

processors:

  attributes:
    actions:
     - key: host_id
       value: "${host.name}"
       action: insert

       - key: os_name
        value: "${os.type}"
        action: insert
   

service:
  pipelines:
    metrics:
      receivers: 
        - hostmetrics

      processors:
        - batch
        - attributes
      exporters: 
        - logging
        - otlphttp
      extensions:
        - health_check

**Comment by astencel-sumo** [comment] 2024-02-19 10:58
In the configuration you pasted (it would help to format the Yaml correctly), you define `logging` and `prometheus` exporters, but in the `service.pipelines` you use `logging` and `otlphttp`. This configuration is incorrect.

Is this issue the same as https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31290 or is this a different problem?

**Comment by bhupenbisht** [comment] 2024-02-19 11:29
aah its same issue.. Thanks

**Comment by astencel-sumo** [comment] 2024-02-19 11:42
Duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31290

**Closed by astencel-sumo** 2024-02-19 11:42 UTC
Labels: needs triage
