### ISSUE TITLE
[Prometheus Compliance Tests] TestRemoteWrite/otelcollector/Counter failed on main

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector-contrib#35119] opened 2024-09-10 13:41 UTC
### Describe the issue you're reporting

E.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/10791551495/job/29929199424?pr=35112

```
=== NAME  TestRemoteWrite/otelcollector/Counter
    counter.go:35: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/compliance/remotewrite/sender/cases/counter.go:35
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/compliance/remotewrite/sender/main_test.go:108
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/compliance/remotewrite/sender/main_test.go:72
        	Error:      	Should be true
        	Test:       	TestRemoteWrite/otelcollector/Counter
        	Messages:   	found zero samples for {__name__="counter"}
```

**Comment by VihasMakwana** [comment] 2024-09-10 17:29
Not able to reproduce this on my darwin arm64...

**Comment by atoulme** [comment] 2024-09-12 00:11
This is breaking on main and all PRs.

**Comment by dashpole** [comment] 2024-09-17 15:27
I'll try to take a look.  cc @jmichalek132 @ArthurSens since this is related to the PRW exporter.

**Comment by dmitryax** [comment] 2024-09-19 21:29
Marking as a release block so we don't release with broken CI

**Comment by dashpole** [comment] 2024-09-20 01:16
Tested against older versions of the prometheus/compliance repo and confirmed it was not a recent regression there

**Comment by dashpole** [comment] 2024-09-20 01:25
In this run, the test actually failed, but the compliance test step passed: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/10495822874/job/29075112350

**Comment by dashpole** [comment] 2024-09-20 01:27
So prior to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35071, the test was failing, but the step itself was not failing.  The PR added `set -o pipefail && \`, which seems to have made the failure fail the test.

**Comment by dashpole** [comment] 2024-09-20 01:45
I took a wild guess and was correct!  The compliance test needs to set `add_metric_suffixes: false` on the prometheusremotewrite exporter for tests to pass.  I assume the counter was being renamed to `counter_total`...

**Comment by dashpole** [comment] 2024-09-20 01:49
https://github.com/prometheus/compliance/pull/106 fixes tests for me locally

**Comment by ArthurSens** [comment] 2024-09-20 07:37
Merged, could we try again?

**Comment by djaglowski** [comment] 2024-09-20 13:10
I updated https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35026 and it worked there! Thanks @dashpole for getting to the bottom of this.

**Closed by djaglowski** 2024-09-20 13:10 UTC
Labels: priority:p1, ci-cd, comp:prometheus, release:blocker

**Comment by crobert-1** [comment] 2024-09-20 15:13
Thanks again @dashpole, really appreciate the fix!
