### ISSUE TITLE
Flaky tests loadbalancingexporter on windows golang 1.16 

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#4043] opened 2021-06-30 16:46 UTC
```
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerthrifthttpexporter	0.056s
--- FAIL: TestRollingUpdatesWhenConsumeTraces (0.04s)
    assertion_compare.go:313: 
        	Error Trace:	trace_exporter_test.go:486
        	Error:      	"0" is not greater than "0"
        	Test:       	TestRollingUpdatesWhenConsumeTraces
        	Messages:   	[]
FAIL
```

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/16109/workflows/81fec083-22e5-47a7-bda2-ab0c7b83a948/jobs/140344

**Comment by mx-psi** [comment] 2021-07-01 10:50
Fixed by #4039. Likely root cause of this is golang/go#44343

**Closed by mx-psi** 2021-07-01 10:50 UTC
Labels: bug
