### ISSUE TITLE
[Lightstep/OTLPExporter]  Does not show the metric description when exported from OpenTelemetry collector

### ISSUE THREAD

**Issue by MacNale** [open-telemetry/opentelemetry-collector-contrib#15356] opened 2022-10-20 18:15 UTC
## Description
Does not show the metric description when metrics exported from OpenTelemetry collector

## Steps to Reproduce
1) Setup a opentelemetry collector with OTLP metrics exporter.
2) Grab the endpoint and token from your account in Lightstep
3) Read the metrics from using Kafka receiver. Use batch processor
4) Check the metrics in Lightstep. Metric data is seen as expected.  However metrics description is missing in UI

## Expected Result
Metric description and unit is respected and visible in lightstep when opentelemetry collector is used

## Actual Result
<img width="373" alt="image" src="https://user-images.githubusercontent.com/14235758/197026197-f4709dd4-b745-4c30-b095-f649e85d1499.png">

### Collector version

0.62.1

## Environment
Open telemetry collector v0.62.1 running as container

### OpenTelemetry Collector configuration

```yaml
processors:
  batch:
    send_batch_max_size: 8192
    send_batch_size: 8192 
    timeout: 10s

exporters:
  otlp/lightstep:
    endpoint: xxx.lightstep.com:xxx
    headers: {"lightstep-access-token": xxx}

service:
  pipelines:
    metrics:
      receivers: [kafka]
      processors: [batch]
      exporters: [otlp/lightstep]
```

**Comment by evan-bradley** [comment] 2022-10-24 19:30
@codeboten Do you have any insights here?

**Comment by codeboten** [comment] 2022-10-24 19:53
Thanks for the report @MacNale, this is currently a limitation on the Lightstep ingest side. There is work planned to address this in the near future. Closing this as it is not a bug in the otel collector.

**Closed by codeboten** 2022-10-24 19:53 UTC
Labels: bug, needs triage
