### ISSUE TITLE
datadog backend treats all traces as errors

### ISSUE THREAD

**Issue by dustyhorizon** [open-telemetry/opentelemetry-collector-contrib#1684] opened 2020-11-23 19:15 UTC
**Describe the bug**
I am getting `CANCELLED: HTTP status code: 200` trace errors on datadog

**Steps to reproduce**
Unknown

**What did you expect to see?**
Traces should not be logged as errors if they completed successfully

**What did you see instead?**
Traces logged as errors on datadog

**What version did you use?**
Version: OTEL Collector Contrib v0.15.0, OTEL-go v0.14.0

otel-collector with debug logging shows the following:
```
otel_collector_1                | InstrumentationLibrarySpans #0
otel_collector_1                | Span #0
otel_collector_1                |     Trace ID       : a3aac419e4db94410e0205b36b7e75cd
otel_collector_1                |     Parent ID      :
otel_collector_1                |     ID             : b75fd023d8527acc
otel_collector_1                |     Name           : <redacted>
otel_collector_1                |     Kind           : SPAN_KIND_SERVER
otel_collector_1                |     Start time     : 2020-11-23 19:09:57.5026383 +0000 UTC
otel_collector_1                |     End time       : 2020-11-23 19:09:57.5483264 +0000 UTC
otel_collector_1                |     Status code    : STATUS_CODE_OK
otel_collector_1                |     Status message : HTTP status code: 200
```

Tried exporting to honeycomb, no errors were being logged there.

**Comment by ericmustin** [comment] 2020-11-23 20:59
@dustyhorizon Hey there, thanks for reaching out on this.

So, to be clear, the issue is that you see these traces in datadog's backend but they are marked as errors, is that correct? Could you share the full debug log output? If possible, Can you install the logging exporter and copy-paste the output for one of the traces?

Additionally, any context you have on how these traces are generated would be very helpful

**Comment by ericmustin** [comment] 2020-11-23 20:59
@bogdandrutu 👋 would you mind assigning this to me as well? cheers

**Comment by dustyhorizon** [comment] 2020-11-24 08:38
> @dustyhorizon Hey there, thanks for reaching out on this.
> 
> So, to be clear, the issue is that you see these traces in datadog's backend but they are marked as errors, is that correct? Could you share the full debug log output? If possible, Can you install the logging exporter and copy-paste the output for one of the traces?
> 
> Additionally, any context you have on how these traces are generated would be very helpful
> 
> Still digging into things but I notice a similar issue with OpenTelemetry-Go [open-telemetry/opentelemetry-go#1342 (comment)](https://github.com/open-telemetry/opentelemetry-go/issues/1342#issue-743710384)

From which service do you require the full debug log output? I am only aware of exporting the debug log through the `logging` exporter

Attached is the full debug log as requested

```
otel_collector_1                | 2020-11-24T08:17:40.207Z      INFO    loggingexporter/logging_exporter.go:339 TracesExporter  {"#spans": 9}
otel_collector_1                | 2020-11-24T08:17:40.208Z      DEBUG   loggingexporter/logging_exporter.go:394 ResourceSpans #0
otel_collector_1                | Resource labels:
otel_collector_1                |      -> host.name: STRING(49b32ea2f1c2)
otel_collector_1                |      -> service.name: STRING(<REDACTED>)
otel_collector_1                |      -> service.namespace: STRING(<REDACTED>)
otel_collector_1                |      -> service.version: STRING(0.0.1)
otel_collector_1                | InstrumentationLibrarySpans #0
otel_collector_1                | Span #0
otel_collector_1                |     Trace ID       : 88699036ed545caf9f61e61ab0f55141
otel_collector_1                |     Parent ID      : b23e579bcb3c7d9c
otel_collector_1                |     ID             : 77cb5cdbcfdc4d12
otel_collector_1                |     Name           : <REDACTED>
otel_collector_1                |     Kind           : SPAN_KIND_CLIENT
otel_collector_1                |     Start time     : 2020-11-24 08:17:08.2252846 +0000 UTC
otel_collector_1                |     End time       : 2020-11-24 08:17:08.2287633 +0000 UTC
otel_collector_1                |     Status code    : STATUS_CODE_OK
otel_collector_1                |     Status message :
otel_collector_1                | Attributes:
otel_collector_1                |      -> rpc.system: STRING(grpc)
otel_collector_1                |      -> rpc.service: STRING(<REDACTED>)
otel_collector_1                |      -> rpc.method: STRING(<REDACTED>)
otel_collector_1                |      -> net.peer.ip: STRING(<REDACTED>)
otel_collector_1                |      -> net.peer.port: STRING(8443)
otel_collector_1                |      -> rpc.grpc.status_code: INT(0)
otel_collector_1                | Events:
otel_collector_1                | SpanEvent #0
otel_collector_1                |      -> Name: message
otel_collector_1                |      -> Timestamp: 1606205828225390400
otel_collector_1                |      -> DroppedAttributesCount: 0
otel_collector_1                |      -> Attributes:
otel_collector_1                |          -> message.type: STRING(SENT)
otel_collector_1                |          -> message.id: INT(1)
otel_collector_1                |          -> message.uncompressed_size: INT(514)
otel_collector_1                | SpanEvent #1
otel_collector_1                |      -> Name: message
otel_collector_1                |      -> Timestamp: 1606205828228749000
otel_collector_1                |      -> DroppedAttributesCount: 0
otel_collector_1                |      -> Attributes:
otel_collector_1                |          -> message.type: STRING(RECEIVED)
otel_collector_1                |          -> message.id: INT(1)
otel_collector_1                |          -> message.uncompressed_size: INT(135)
otel_collector_1                | ResourceSpans #1
otel_collector_1                | Resource labels:
otel_collector_1                |      -> host.name: STRING(49b32ea2f1c2)
otel_collector_1                |      -> service.name: STRING(<REDACTED>)
otel_collector_1                |      -> service.namespace: STRING(<REDACTED>)
otel_collector_1                |      -> service.version: STRING(0.0.1)
otel_collector_1                | InstrumentationLibrarySpans #0
otel_collector_1                | Span #0
otel_collector_1                |     Trace ID       : 88699036ed545caf9f61e61ab0f55141
otel_collector_1                |     Parent ID      : b23e579bcb3c7d9c
otel_collector_1                |     ID             : d083499027157dd4
otel_collector_1                |     Name           : <REDACTED>
otel_collector_1                |     Kind           : SPAN_KIND_CLIENT
otel_collector_1                |     Start time     : 2020-11-24 08:17:08.2313654 +0000 UTC
otel_collector_1                |     End time       : 2020-11-24 08:17:08.2344311 +0000 UTC
otel_collector_1                |     Status code    : STATUS_CODE_OK
otel_collector_1                |     Status message :
otel_collector_1                | Attributes:
otel_collector_1                |      -> rpc.system: STRING(grpc)
otel_collector_1                |      -> rpc.service: STRING(<REDACTED>)
otel_collector_1                |      -> rpc.method: STRING(<REDACTED>)
otel_collector_1                |      -> net.peer.ip: STRING(<REDACTED>)
otel_collector_1                |      -> net.peer.port: STRING(8443)
otel_collector_1                |      -> rpc.grpc.status_code: INT(0)
otel_collector_1                | Events:
otel_collector_1                | SpanEvent #0
otel_collector_1                |      -> Name: message
otel_collector_1                |      -> Timestamp: 1606205828231437600
otel_collector_1                |      -> DroppedAttributesCount: 0
otel_collector_1                |      -> Attributes:
otel_collector_1                |          -> message.type: STRING(SENT)
otel_collector_1                |          -> message.id: INT(1)
otel_collector_1                |          -> message.uncompressed_size: INT(27)
otel_collector_1                | SpanEvent #1
otel_collector_1                |      -> Name: message
otel_collector_1                |      -> Timestamp: 1606205828234416800
otel_collector_1                |      -> DroppedAttributesCount: 0
otel_collector_1                |      -> Attributes:
otel_collector_1                |          -> message.type: STRING(RECEIVED)
otel_collector_1                |          -> message.id: INT(1)
otel_collector_1                |          -> message.uncompressed_size: INT(97)
otel_collector_1                | ResourceSpans #2
otel_collector_1                | Resource labels:
otel_collector_1                |      -> host.name: STRING(49b32ea2f1c2)
otel_collector_1                |      -> service.name: STRING(<REDACTED>)
otel_collector_1                |      -> service.namespace: STRING(<REDACTED>)
otel_collector_1                |      -> service.version: STRING(0.0.1)
otel_collector_1                | InstrumentationLibrarySpans #0
otel_collector_1                | Span #0
otel_collector_1                |     Trace ID       : 88699036ed545caf9f61e61ab0f55141
otel_collector_1                |     Parent ID      :
otel_collector_1                |     ID             : b23e579bcb3c7d9c
otel_collector_1                |     Name           : /graphql
otel_collector_1                |     Kind           : SPAN_KIND_SERVER
otel_collector_1                |     Start time     : 2020-11-24 08:17:08.2251967 +0000 UTC
otel_collector_1                |     End time       : 2020-11-24 08:17:08.2412689 +0000 UTC
otel_collector_1                |     Status code    : STATUS_CODE_OK
otel_collector_1                |     Status message : HTTP status code: 200
otel_collector_1                | Attributes:
otel_collector_1                |      -> net.transport: STRING(IP.TCP)
otel_collector_1                |      -> net.peer.ip: STRING(192.168.112.1)
otel_collector_1                |      -> net.peer.port: INT(47530)
otel_collector_1                |      -> net.host.name: STRING(localhost)
otel_collector_1                |      -> net.host.port: INT(8001)
otel_collector_1                |      -> http.method: STRING(POST)
otel_collector_1                |      -> http.target: STRING(/graphql)
otel_collector_1                |      -> http.server_name: STRING(/graphql)
otel_collector_1                |      -> http.user_agent: STRING(Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36)
otel_collector_1                |      -> http.request_content_length: INT(1468)
otel_collector_1                |      -> http.scheme: STRING(http)
otel_collector_1                |      -> http.host: STRING(localhost:8001)
otel_collector_1                |      -> http.flavor: STRING(1.1)
otel_collector_1                |      -> enduser.id: STRING(<REDACTED>)
otel_collector_1                |      -> enduser.role: STRING(<REDACTED>)
otel_collector_1                |      -> http.read_bytes: INT(1468)
otel_collector_1                |      -> http.wrote_bytes: INT(21809)
otel_collector_1                |      -> http.status_code: INT(200)
otel_collector_1                | ResourceSpans #3
otel_collector_1                | Resource labels:
otel_collector_1                |      -> host.name: STRING(49b32ea2f1c2)
otel_collector_1                |      -> service.name: STRING(<REDACTED>)
otel_collector_1                |      -> service.namespace: STRING(<REDACTED>)
otel_collector_1                |      -> service.version: STRING(0.0.1)
otel_collector_1                | InstrumentationLibrarySpans #0
otel_collector_1                | Span #0
otel_collector_1                |     Trace ID       : 25a0000fcc4d278bfa32db2129dafa78
otel_collector_1                |     Parent ID      : b1e5800986f64c40
otel_collector_1                |     ID             : 769e054626e2bb98
otel_collector_1                |     Name           : <REDACTED>
otel_collector_1                |     Kind           : SPAN_KIND_CLIENT
otel_collector_1                |     Start time     : 2020-11-24 08:17:10.2665547 +0000 UTC
otel_collector_1                |     End time       : 2020-11-24 08:17:10.2812647 +0000 UTC
otel_collector_1                |     Status code    : STATUS_CODE_OK
otel_collector_1                |     Status message :
otel_collector_1                | Attributes:
otel_collector_1                |      -> rpc.system: STRING(grpc)
otel_collector_1                |      -> rpc.service: STRING(<REDACTED>)
otel_collector_1                |      -> rpc.method: STRING(<REDACTED>)
otel_collector_1                |      -> net.peer.ip: STRING(<REDACTED>)
otel_collector_1                |      -> net.peer.port: STRING(8443)
otel_collector_1                |      -> rpc.grpc.status_code: INT(0)
otel_collector_1                | Events:
otel_collector_1                | SpanEvent #0
otel_collector_1                |      -> Name: message
otel_collector_1                |      -> Timestamp: 1606205830266589700
otel_collector_1                |      -> DroppedAttributesCount: 0
otel_collector_1                |      -> Attributes:
otel_collector_1                |          -> message.type: STRING(SENT)
otel_collector_1                |          -> message.id: INT(1)
otel_collector_1                |          -> message.uncompressed_size: INT(514)
otel_collector_1                | SpanEvent #1
otel_collector_1                |      -> Name: message
otel_collector_1                |      -> Timestamp: 1606205830281256600
otel_collector_1                |      -> DroppedAttributesCount: 0
otel_collector_1                |      -> Attributes:
otel_collector_1                |          -> message.type: STRING(RECEIVED)
otel_collector_1                |          -> message.id: INT(1)
otel_collector_1                |          -> message.uncompressed_size: INT(135)
otel_collector_1                | ResourceSpans #4
otel_collector_1                | Resource labels:
otel_collector_1                |      -> host.name: STRING(49b32ea2f1c2)
otel_collector_1                |      -> service.name: STRING(<REDACTED>)
otel_collector_1                |      -> service.namespace: STRING(<REDACTED>)
otel_collector_1                |      -> service.version: STRING(0.0.1)
otel_collector_1                | InstrumentationLibrarySpans #0
otel_collector_1                | Span #0
otel_collector_1                |     Trace ID       : 25a0000fcc4d278bfa32db2129dafa78
otel_collector_1                |     Parent ID      : b1e5800986f64c40
otel_collector_1                |     ID             : abc4314e98957d5f
otel_collector_1                |     Name           : <REDACTED>
otel_collector_1                |     Kind           : SPAN_KIND_CLIENT
otel_collector_1                |     Start time     : 2020-11-24 08:17:10.2833462 +0000 UTC
otel_collector_1                |     End time       : 2020-11-24 08:17:10.2880093 +0000 UTC
otel_collector_1                |     Status code    : STATUS_CODE_OK
otel_collector_1                |     Status message :
otel_collector_1                | Attributes:
otel_collector_1                |      -> rpc.system: STRING(grpc)
otel_collector_1                |      -> rpc.service: STRING(<REDACTED>)
otel_collector_1                |      -> rpc.method: STRING(<REDACTED>)
otel_collector_1                |      -> net.peer.ip: STRING(<REDACTED>)
otel_collector_1                |      -> net.peer.port: STRING(8443)
otel_collector_1                |      -> rpc.grpc.status_code: INT(0)
otel_collector_1                | Events:
otel_collector_1                | SpanEvent #0
otel_collector_1                |      -> Name: message
otel_collector_1                |      -> Timestamp: 1606205830283398900
otel_collector_1                |      -> DroppedAttributesCount: 0
otel_collector_1                |      -> Attributes:
otel_collector_1                |          -> message.type: STRING(SENT)
otel_collector_1                |          -> message.id: INT(1)
otel_collector_1                |          -> message.uncompressed_size: INT(27)
otel_collector_1                | SpanEvent #1
otel_collector_1                |      -> Name: message
otel_collector_1                |      -> Timestamp: 1606205830287969600
otel_collector_1                |      -> DroppedAttributesCount: 0
otel_collector_1                |      -> Attributes:
otel_collector_1                |          -> message.type: STRING(RECEIVED)
otel_collector_1                |          -> message.id: INT(1)
otel_collector_1                |          -> message.uncompressed_size: INT(97)
otel_collector_1                | ResourceSpans #5
otel_collector_1                | Resource labels:
otel_collector_1                |      -> host.name: STRING(49b32ea2f1c2)
otel_collector_1                |      -> service.name: STRING(<REDACTED>)
otel_collector_1                |      -> service.namespace: STRING(<REDACTED>)
otel_collector_1                |      -> service.version: STRING(0.0.1)
otel_collector_1                | InstrumentationLibrarySpans #0
otel_collector_1                | Span #0
otel_collector_1                |     Trace ID       : 25a0000fcc4d278bfa32db2129dafa78
otel_collector_1                |     Parent ID      :
otel_collector_1                |     ID             : b1e5800986f64c40
otel_collector_1                |     Name           : /graphql
otel_collector_1                |     Kind           : SPAN_KIND_SERVER
otel_collector_1                |     Start time     : 2020-11-24 08:17:10.2664188 +0000 UTC
otel_collector_1                |     End time       : 2020-11-24 08:17:10.2937205 +0000 UTC
otel_collector_1                |     Status code    : STATUS_CODE_OK
otel_collector_1                |     Status message : HTTP status code: 200
otel_collector_1                | Attributes:
otel_collector_1                |      -> net.transport: STRING(IP.TCP)
otel_collector_1                |      -> net.peer.ip: STRING(192.168.112.1)
otel_collector_1                |      -> net.peer.port: INT(47530)
otel_collector_1                |      -> net.host.name: STRING(localhost)
otel_collector_1                |      -> net.host.port: INT(8001)
otel_collector_1                |      -> http.method: STRING(POST)
otel_collector_1                |      -> http.target: STRING(/graphql)
otel_collector_1                |      -> http.server_name: STRING(/graphql)
otel_collector_1                |      -> http.user_agent: STRING(Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36)
otel_collector_1                |      -> http.request_content_length: INT(1468)
otel_collector_1                |      -> http.scheme: STRING(http)
otel_collector_1                |      -> http.host: STRING(localhost:8001)
otel_collector_1                |      -> http.flavor: STRING(1.1)
otel_collector_1                |      -> enduser.id: STRING(<REDACTED>)
otel_collector_1                |      -> enduser.role: STRING(<REDACTED>)
otel_collector_1                |      -> http.read_bytes: INT(1468)
otel_collector_1                |      -> http.wrote_bytes: INT(21809)
otel_collector_1                |      -> http.status_code: INT(200)
otel_collector_1                | ResourceSpans #6
otel_collector_1                | Resource labels:
otel_collector_1                |      -> host.name: STRING(49b32ea2f1c2)
otel_collector_1                |      -> service.name: STRING(<REDACTED>)
otel_collector_1                |      -> service.namespace: STRING(<REDACTED>)
otel_collector_1                |      -> service.version: STRING(0.0.1)
otel_collector_1                | InstrumentationLibrarySpans #0
otel_collector_1                | Span #0
otel_collector_1                |     Trace ID       : bbf6455f82f8ec8b12f484ce22533492
otel_collector_1                |     Parent ID      : 4192af0c00e8e8c0
otel_collector_1                |     ID             : b2d08c48456e4947
otel_collector_1                |     Name           : <REDACTED>
otel_collector_1                |     Kind           : SPAN_KIND_CLIENT
otel_collector_1                |     Start time     : 2020-11-24 08:17:12.2890411 +0000 UTC
otel_collector_1                |     End time       : 2020-11-24 08:17:12.292667 +0000 UTC
otel_collector_1                |     Status code    : STATUS_CODE_OK
otel_collector_1                |     Status message :
otel_collector_1                | Attributes:
otel_collector_1                |      -> rpc.system: STRING(grpc)
otel_collector_1                |      -> rpc.service: STRING(<REDACTED>)
otel_collector_1                |      -> rpc.method: STRING(<REDACTED>)
otel_collector_1                |      -> net.peer.ip: STRING(<REDACTED>)
otel_collector_1                |      -> net.peer.port: STRING(8443)
otel_collector_1                |      -> rpc.grpc.status_code: INT(0)
otel_collector_1                | Events:
otel_collector_1                | SpanEvent #0
otel_collector_1                |      -> Name: message
otel_collector_1                |      -> Timestamp: 1606205832289078800
otel_collector_1                |      -> DroppedAttributesCount: 0
otel_collector_1                |      -> Attributes:
otel_collector_1                |          -> message.type: STRING(SENT)
otel_collector_1                |          -> message.id: INT(1)
otel_collector_1                |          -> message.uncompressed_size: INT(514)
otel_collector_1                | SpanEvent #1
otel_collector_1                |      -> Name: message
otel_collector_1                |      -> Timestamp: 1606205832292660800
otel_collector_1                |      -> DroppedAttributesCount: 0
otel_collector_1                |      -> Attributes:
otel_collector_1                |          -> message.type: STRING(RECEIVED)
otel_collector_1                |          -> message.id: INT(1)
otel_collector_1                |          -> message.uncompressed_size: INT(135)
otel_collector_1                | ResourceSpans #7
otel_collector_1                | Resource labels:
otel_collector_1                |      -> host.name: STRING(49b32ea2f1c2)
otel_collector_1                |      -> service.name: STRING(<REDACTED>)
otel_collector_1                |      -> service.namespace: STRING(<REDACTED>)
otel_collector_1                |      -> service.version: STRING(0.0.1)
otel_collector_1                | InstrumentationLibrarySpans #0
otel_collector_1                | Span #0
otel_collector_1                |     Trace ID       : bbf6455f82f8ec8b12f484ce22533492
otel_collector_1                |     Parent ID      : 4192af0c00e8e8c0
otel_collector_1                |     ID             : 6c3de3a757f0b699
otel_collector_1                |     Name           : <REDACTED>
otel_collector_1                |     Kind           : SPAN_KIND_CLIENT
otel_collector_1                |     Start time     : 2020-11-24 08:17:12.2952756 +0000 UTC
otel_collector_1                |     End time       : 2020-11-24 08:17:12.2986567 +0000 UTC
otel_collector_1                |     Status code    : STATUS_CODE_OK
otel_collector_1                |     Status message :
otel_collector_1                | Attributes:
otel_collector_1                |      -> rpc.system: STRING(grpc)
otel_collector_1                |      -> rpc.service: STRING(<REDACTED>)
otel_collector_1                |      -> rpc.method: STRING(<REDACTED>)
otel_collector_1                |      -> net.peer.ip: STRING(<REDACTED>)
otel_collector_1                |      -> net.peer.port: STRING(8443)
otel_collector_1                |      -> rpc.grpc.status_code: INT(0)
otel_collector_1                | Events:
otel_collector_1                | SpanEvent #0
otel_collector_1                |      -> Name: message
otel_collector_1                |      -> Timestamp: 1606205832295308300
otel_collector_1                |      -> DroppedAttributesCount: 0
otel_collector_1                |      -> Attributes:
otel_collector_1                |          -> message.type: STRING(SENT)
otel_collector_1                |          -> message.id: INT(1)
otel_collector_1                |          -> message.uncompressed_size: INT(27)
otel_collector_1                | SpanEvent #1
otel_collector_1                |      -> Name: message
otel_collector_1                |      -> Timestamp: 1606205832298645500
otel_collector_1                |      -> DroppedAttributesCount: 0
otel_collector_1                |      -> Attributes:
otel_collector_1                |          -> message.type: STRING(RECEIVED)
otel_collector_1                |          -> message.id: INT(1)
otel_collector_1                |          -> message.uncompressed_size: INT(97)
otel_collector_1                | ResourceSpans #8
otel_collector_1                | Resource labels:
otel_collector_1                |      -> host.name: STRING(49b32ea2f1c2)
otel_collector_1                |      -> service.name: STRING(<REDACTED>)
otel_collector_1                |      -> service.namespace: STRING(<REDACTED>)
otel_collector_1                |      -> service.version: STRING(0.0.1)
otel_collector_1                | InstrumentationLibrarySpans #0
otel_collector_1                | Span #0
otel_collector_1                |     Trace ID       : bbf6455f82f8ec8b12f484ce22533492
otel_collector_1                |     Parent ID      :
otel_collector_1                |     ID             : 4192af0c00e8e8c0
otel_collector_1                |     Name           : /graphql
otel_collector_1                |     Kind           : SPAN_KIND_SERVER
otel_collector_1                |     Start time     : 2020-11-24 08:17:12.2888937 +0000 UTC
otel_collector_1                |     End time       : 2020-11-24 08:17:12.3041821 +0000 UTC
otel_collector_1                |     Status code    : STATUS_CODE_OK
otel_collector_1                |     Status message : HTTP status code: 200
otel_collector_1                | Attributes:
otel_collector_1                |      -> net.transport: STRING(IP.TCP)
otel_collector_1                |      -> net.peer.ip: STRING(192.168.112.1)
otel_collector_1                |      -> net.peer.port: INT(47530)
otel_collector_1                |      -> net.host.name: STRING(localhost)
otel_collector_1                |      -> net.host.port: INT(8001)
otel_collector_1                |      -> http.method: STRING(POST)
otel_collector_1                |      -> http.target: STRING(/graphql)
otel_collector_1                |      -> http.server_name: STRING(/graphql)
otel_collector_1                |      -> http.user_agent: STRING(Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36)
otel_collector_1                |      -> http.request_content_length: INT(1468)
otel_collector_1                |      -> http.scheme: STRING(http)
otel_collector_1                |      -> http.host: STRING(localhost:8001)
otel_collector_1                |      -> http.flavor: STRING(1.1)
otel_collector_1                |      -> enduser.id: STRING(<REDACTED>)
otel_collector_1                |      -> enduser.role: STRING(<REDACTED>)
otel_collector_1                |      -> http.read_bytes: INT(1468)
otel_collector_1                |      -> http.wrote_bytes: INT(21809)
otel_collector_1                |      -> http.status_code: INT(200)
```

Currently the requests are fronted by a graphQL and instrumented by otelhttp which will then be propagated to otelgrpc.

Datadog backend is showing this trace as an error

![image](https://user-images.githubusercontent.com/4987132/100069123-54937a00-2e73-11eb-9807-26d3b719c59d.png)

**Comment by ericmustin** [comment] 2020-11-24 09:08
@dustyhorizon thank you, that's helpful. I am relatively sure the issue is related to the change made here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1489

Either OpenTelemetry-Go needs to be updated to account for the new status code settings, or the datadogexporter does. I'm going to attempt to reproduce this today and hopefully narrow down the root cause here, and if on the datadogexporter end, push up a fix for you.

Will keep you updated, thanks again for the report and prompt reply.

**Comment by dustyhorizon** [comment] 2020-11-24 09:14
Yes I am using the OTLP exporter to otel-collector-contrib v0.15.0. 

I forgot to mention but I was on the previous version of opentelemetry-go v0.13.0 and opentelemetry-go-contrib v0.13.0 and the datadog UI was functioning fine then. 

Thanks for the help!

**Comment by ericmustin** [comment] 2020-11-24 09:25
@dustyhorizon ah, that's super helpful! ty ty. will try to update here by EOD with some more clarity

**Comment by ericmustin** [comment] 2020-11-25 10:48
@dustyhorizon I put up a PR that fixes things, tl;dr there were updates made to the way span status code works this specific vendor exporter didn't get updated to account for that due to some unusual timing issues around when this work got merged. Tested the above PR locally and it resolves the issue you were seeing

**Comment by dustyhorizon** [comment] 2020-11-25 11:00
Haha thats great! Thanks for the fixes @ericmustin

**Closed** 2020-12-02 13:58 UTC
Labels: bug

**Comment by ericmustin** [comment] 2020-12-02 15:24
we're still waiting for a release here i believe
