### ISSUE TITLE
Failed to create containerd task: Exec: "/otelcontribcol": permission denied: unknown - when running the container as non root 

### ISSUE THREAD

**Issue by arundathi-nirmata** [open-telemetry/opentelemetry-collector-contrib#6238] opened 2021-11-11 19:05 UTC
We are running otel-collector deployment on cluster v1.21.1  with nonroot specific security context.

Facing issue of runContainerError and eventually pod goes to CrashLoopBackOff with the below error

`Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/otelcontribcol": permission denied: unknown`

Below is the deployment I am using 

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-agent
  labels:
    app: opentelemetry
    component: otel-agent
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-agent
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-agent
    spec:
      containers:
      - name: otel-agent
        image: otel/opentelemetry-collector-contrib:0.37.1
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
        livenessProbe:
          exec:
            command:
            - cat
            - /etc/otel/config.yaml
        readinessProbe:
          exec:
            command:
            - cat
            - /etc/otel/config.yaml
        volumeMounts:
        - mountPath: /var/log
          name: varlog
          readOnly: true
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /etc/otel/config.yaml
          name: data
          subPath: config.yaml
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: data
        configMap:
          name: otel-agent-config
```

**Comment by rmtobin** [comment] 2021-11-11 23:33
This also is an issue when attempting to run the demo locally as provided in the [documentation](https://opentelemetry.io/docs/collector/getting-started/).

Running the demo command as written in the docs errors out with `ERROR: for otel-collector  Cannot start service otel-collector: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/otelcontribcol": permission denied: unknown`.

**Comment by jcadavez** [comment] 2021-11-15 14:00
Same here, having trouble running it on Github Actions on an Ubuntu runner.

What's the latest version of this container I can use temporarily?

**Comment by kw7oe** [comment] 2021-11-16 02:29
> Same here, having trouble running it on Github Actions on an Ubuntu runner.
> 
> What's the latest version of this Docker image I can use temporarily?

@jcadavez  I think the latest working version is: [`otel/opentelemetry-collector-contrib-dev:93a9885459c9406db8ac446f77f290b02542e8d5`](https://hub.docker.com/layers/otel/opentelemetry-collector-contrib-dev/93a9885459c9406db8ac446f77f290b02542e8d5/images/sha256-50d17a221bd252bdca9727415024409fbacb3961cd404ad42dd88a272e5b91c9?context=explore)

**Comment by indrekj** [comment] 2021-11-16 10:12
We were fine with: `0.37.1` and `0.38.0`, but when we changed to `v0.39.0` we started getting:
```
Error: failed to start container "otc-container": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/otelcontribcol": permission denied: unknown
```

**Comment by indrekj** [comment] 2021-11-16 11:47
Inspected the filesystems of both docker images `0.38.0` and `v0.39.0`.

In `0.38.0`:
```
-rwxr-xr-x  1 indrek indrek 143172784 Nov  1 21:41 otelcontribcol
```

In `v0.39.0`:
```
-rw-r--r-- 1 indrek indrek 143808977 Nov 16 02:54 otelcontribcol
```

So it looks that otelcontribcol is not marked as executable in `v0.39.0` docker image.

Running `make docker-otelcontribcol` on main branch seemed to build a docker image with executable file correctly, so not sure what happened with the `v0.39.0` build.

**Comment by NathanielRN** [comment] 2021-11-16 23:54
Should probably be closed as a duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6343

**Closed** 2021-11-17 20:30 UTC
Labels: bug
