### ISSUE TITLE
[k8s] The k8s integration tests are failing

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#33520] opened 2024-06-12 20:17 UTC
### Component(s)

processor/k8sattributes, receiver/k8scluster, receiver/k8sobjects, receiver/kubeletstats

### Describe the issue you're reporting

The k8s integration tests have started failing. See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/workflows/e2e-tests.yml?query=branch%3Amain.

**Comment by TylerHelmuth** [comment] 2024-06-12 20:18
I have been unable to reproduce the issues locally

**Comment by TylerHelmuth** [comment] 2024-06-12 20:22
@jinja2 @fatsheep9146 any guesses?

**Comment by axw** [comment] 2024-06-13 08:18
I had reproduced the error locally yesterday (or at least something that looked the same), but had to switch focus before I could find the root cause. Now I can't reproduce it :(

One thing I did notice was in the collector logs there were errors about not being able to connect to kind-control-plane. Perhaps the e2e workflow should capture the pod logs before tearing down, to make debugging easier.

**Comment by fatsheep9146** [comment] 2024-06-13 08:33
> I had reproduced the error locally yesterday (or at least something that looked the same), but had to switch focus before I could find the root cause. Now I can't reproduce it :(
> 
> One thing I did notice was in the collector logs there were errors about not being able to connect to kind-control-plane. Perhaps the e2e workflow should capture the pod logs before tearing down, to make debugging easier.

I also could not reproduce the same error like github action, it's really weird. But your advise is really good to capture the logs of pod (no matter collector or telemetrygen) in workflow to help debugging. @axw

**Comment by ChrsMark** [comment] 2024-06-13 09:31
Tried sth dirty to capture the logs of the Pods: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33538.
Let's see if this can provide us some insights here.

**Comment by ChrsMark** [comment] 2024-06-13 10:03
Got some interesting "connection refused" errors: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9497224255/job/26173693278?pr=33538#step:11:225

```console
2024-06-13T09:44:56.953Z	info	exporterhelper/retry_sender.go:118	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "traces", "name": "otlp", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:4317: connect: connection refused\"", "interval": "7.546970563s"}
2024-06-13T09:44:57.064Z	info	exporterhelper/retry_sender.go:118	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "logs", "name": "otlp", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:4317: connect: connection refused\"", "interval": "7.612004411s"}
2024-06-13T09:44:57.486Z	info	exporterhelper/retry_sender.go:118	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "traces", "name": "otlp", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:4317: connect: connection refused\"", "interval": "6.403460654s"}
```

**Comment by fatsheep9146** [comment] 2024-06-13 11:07
@ChrsMark 
Seems that the logic of getting `hostEndpoint` is the root cause, and this logic is different between mac and linux.

**Comment by fatsheep9146** [comment] 2024-06-13 11:12
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/11855957/45264882-2b18-43a9-808c-f270f9922c0e)
@ChrsMark In your latest pr, the hostEndpoint is empty, I think this is the root cause.
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9498361987/job/26177138997?pr=33538

**Comment by fatsheep9146** [comment] 2024-06-13 11:47
I suspect the reason is due to the https://github.com/actions/runner-images/pull/10039/files.
The os `ubuntu-latest` we use in github action updated with new version of docker.

**Comment by ChrsMark** [comment] 2024-06-13 12:38
Sounds possible @fatsheep9146, I will try to upgrade docker on my machine to `26.x.x` as well and see if I can reproduce it.

**Comment by fatsheep9146** [comment] 2024-06-13 13:02
@ChrsMark I'm trying to update the sdk version docker to see if it can fix the problem.

**Comment by ChrsMark** [comment] 2024-06-13 13:11
@fatsheep9146 thank's! FYI debugging this, I spot that https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6b1d3dd2c0c0812ebf5d973cda27f3817c68d038/internal/k8stest/k8s_data_helpers.go#L28 is failing with `context deadline exceeded`, but the weird thing is that this error is for some reason "muted".

Hopefully the lib upgrade can solve this.

**Comment by ChrsMark** [comment] 2024-06-13 14:20
I had a [successful run](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9501110285/job/26186347623?pr=33548) at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33548. I'm going to enable the rest of the tests and check again.

**Comment by fatsheep9146** [comment] 2024-06-13 14:41
> I had a [successful run](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9501110285/job/26186347623?pr=33548) at #33548. I'm going to enable the rest of the tests and check again.
@ChrsMark 

Yes, I found update docker sdk library is blocked by for some reasons.
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32614
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31989

So I also try to use another way to get the right host endpoint
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9501492668/job/26187569925?pr=33542

I think we can try in both ways and get more opnions from others.

**Comment by ChrsMark** [comment] 2024-06-13 15:06
I hit an additional error at `k8scluster` receiver. It seems that some image names have also changed as well: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9501435003/job/26187307997?pr=33548#step:11:35

potential fix: [c87a639](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33548/commits/c87a6395539db2ba7547c980222ba46af3254ad1)

**Comment by fatsheep9146** [comment] 2024-06-13 15:08
> I hit an additional error at `k8scluster` receiver. It seems that some image names have also changed as well: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9501435003/job/26187307997?pr=33548#step:11:35
> 
> potential fix: [c87a639](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33548/commits/c87a6395539db2ba7547c980222ba46af3254ad1)

I think this maybe due to the newer version of kind

**Comment by ChrsMark** [comment] 2024-06-13 15:45
@fatsheep9146 [e2e tests](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9502371326/job/26190842695?pr=33548) passed at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33548. I'm opening that one for review since it offers a fix anyways. I'll be out tomorrow (Friday) so feel free to pick the [gateway check](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33548/files#diff-20847433220c5b8e090deb88480eae8380cfd38f428e4a718a5206948a3a4515R31-R33) and proceed with [yours](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33542) if people find the approach more suitable. I'm fine either way as soon as we solve the issue :).

**Comment by crobert-1** [comment] 2024-06-13 20:49
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33548

**Closed by crobert-1** 2024-06-13 20:49 UTC
Labels: help wanted, ci-cd, processor/k8sattributes, flaky test, release:blocker, receiver/kubeletstats, receiver/k8scluster, receiver/k8sobjects, internal/k8stest

**Comment by crobert-1** [comment] 2024-06-13 21:28
Thanks for addressing and fixing so quickly @ChrsMark and @fatsheep9146!
