### ISSUE TITLE
influxdbreceiver: Unexpected response status code

### ISSUE THREAD

**Issue by codebien** [open-telemetry/opentelemetry-collector-contrib#5582] opened 2021-10-04 17:20 UTC
**Describe the bug**
The `influxdbreceiver` endpoint returns a `202 Accepted` status code instead of the expected `204 No Content` as defined from the [InfluxDB API reference](https://docs.influxdata.com/influxdb/v1.8/tools/api/#summary-table-1). 

**What version did you use?**
Version: `v0.36.0`

**Comment by jacobmarble** [comment] 2022-03-11 21:22
Duplicate of #6506
Fixed in #6530

This issue can be closed.

**Closed** 2022-03-14 14:30 UTC
Labels: bug
