### ISSUE TITLE
Assets for release 0.41.0

### ISSUE THREAD

**Issue by lchayoun** [open-telemetry/opentelemetry-collector-contrib#6714] opened 2021-12-11 16:25 UTC
Please add the missing assets

**Comment by KingJ** [comment] 2021-12-11 20:21
I've been trying to trace back why they weren't published automatically.

[Here's the build output for the v0.41.0 tag](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4474550370?check_suite_focus=true). The "Push Docker Image" and "Create Github Release" steps were skipped, as the "Verify Distribution Files Exist" step output the following error;

```
Run ./.github/workflows/scripts/verify-dist-files-exist.sh
dist/otel-contrib-collector-*.arm64.rpm does not exist.
```

The earlier "Download Packages" step did work, and reports that 5 packages were downloaded. This matches the number of packages [produced by the build-and-test workflow](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/1560023799) (specifically, the number of files in the "collector-packages" artifact).

The [verify-dist-files-exist.sh script](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/7c50549d136eb790d0ff045847646bb9f0dbff12/.github/workflows/scripts/verify-dist-files-exist.sh) expects there to be a package file with a suffix of `.arm64.rpm` - however the actual ARM architecture RPM package in the artifact collection is `otel-contrib-collector-0.41.0-1.aarch64.rpm`.

ARM RPM packages were renamed to have an `aarch64` suffix rather than an `arm64` suffix in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6635 due to issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6508. I suspect that all that needs to be done to get artifact publishing working again is to change the `verify-dist-files-exist.sh` script to expect a package with an `.aarch64.rpm` suffix rather than a `.arm64.rpm` suffix.

I'll get a PR raised shortly to correct this to save some time just in case that is the root cause! This is likely also why no dev builds have been published to the [otel/opentelemetry-collector-contrib-dev Docker Hub repo](https://hub.docker.com/r/otel/opentelemetry-collector-contrib-dev/tags) for the last 3 days.

**Comment by lchayoun** [comment] 2021-12-14 08:29
I think this issue should be reopened.
The issue is fixed for future versions, but not for 0.41.0

**Comment by arminru** [comment] 2021-12-14 12:17
@jpkrohling v0.41.0 is the latest release and it's not available on Docker Hub (https://hub.docker.com/r/otel/opentelemetry-collector-contrib/tags), for example. Would it be possible to trigger the workflow manually or would one need to wait for the v0.42.0 release?

**Comment by lchayoun** [comment] 2021-12-14 12:25
Also in the releases page, all the assets are missing

**Comment by jpkrohling** [comment] 2021-12-14 12:28
I understand that, but my question is if you need anything that is *only* available as part of 0.41.0, or if you can wait for 0.42.0. I'm not sure the workflows can be triggered manually from the main branch outside of the release tag (0.41.0). I would rather create 0.41.1 instead, but that does involve some work which I would try to avoid unless absolutely necessary.

Once we start producing the assets from the -releases repo, this should not be a big problem anymore.

**Comment by arminru** [comment] 2021-12-14 16:58
I see. We don't intend to use that particular version but pull in all releases from Docker Hub for our integration tests. If the assets for 0.41.0 are not available anywhere though we can skip that one as likely no one will be using that particular version unless they build it themselves, so it should be fine. No need from our end to put extra work into publishing it properly then.

**Comment by lchayoun** [comment] 2021-12-15 08:40
Any reason not to create the assets for version 0.41.0?

**Comment by jpkrohling** [comment] 2021-12-15 10:27
> Any reason not to create the assets for version 0.41.0?

The assets are created during the release process, out of a tag (0.41.0). We'd need a new tag, 0.41.1, and go through the regular release process, which takes a couple of approvals on a couple of PRs.

Generating them manually and attaching them manually to the release *might* work, but I need to do some investigation. Doing that prevents me from doing other work, hence the question about the criticality of this.

In time: my current task is to [create a contrib distribution in the -releases](https://github.com/open-telemetry/opentelemetry-collector-releases/issues/37) repository. I should be able to generate an "alternative" 0.41.0 version of contrib out of it, publishing the artifacts elsewhere (likely as part of my fork of the -releases repository).

**Comment by lchayoun** [comment] 2021-12-16 07:59
We waited for this version to test a fix done by @mx-psi

**Comment by jpkrohling** [comment] 2021-12-16 09:11
Got it. Do you need a binary or a container image? For which os and platform? I can generate one for you.

We discussed this issue yesterday during the SIG meeting and @tigrannajaryan was vocal in that we shouldn't do a manual release of this. So, we have the following options if we need all assets here (as opposed to a single binary/container that I can generate for you):

- Use the builder, once open-telemetry/opentelemetry-collector-releases#37 is merged to produce a 0.41.1 based on the 0.41.0 tag
- Wait for 0.42.0 (Jan 5)
- Release 0.41.1 off of the releases/0.41.x branch, cherry-picking the fix to the release script

I'm currently working on the first option.

**Comment by lchayoun** [comment] 2021-12-16 09:32
We are using the `otel-contrib-collector_<version>_amd64.deb` asset

So basically we just need `otel-contrib-collector_0.41.0_amd64.deb`

**Comment by jpkrohling** [comment] 2021-12-16 09:51
Here it is, uploaded to a release on my fork: https://github.com/jpkrohling/opentelemetry-collector-contrib/releases/download/v0.41.0/otel-contrib-collector_0.41.0_amd64.deb 

For those who prefer to build themselves instead of trusting someone on a GitHub issue, here are the instructions:

```
git checkout v0.41.0
make otelcontribcol-linux_amd64 deb-package
```

The package will be available under the `dist` directory.

**Comment by jpkrohling** [comment] 2021-12-16 18:37
I'm reopening, as this wasn't solved yet.

**Comment by pellared** [comment] 2022-01-14 14:04
It would be good to publish the assets as we have some bug in `0.42.0` and it would be faster to check where the issue has been introduced.

**Comment by jpkrohling** [comment] 2022-01-14 20:25
Which bug are you experiencing? Which asset do you need specifically?

**Comment by pellared** [comment] 2022-01-17 11:50
@jpkrohling

@Kielek found what caused the issue. We were relying on the `config.yaml` path used in the container image entry-point which changed from `/etc/otelcol/config.yaml` to `/etc/otelcol-contrib/config.yaml`.  I have created an issue here https://github.com/open-telemetry/opentelemetry-collector-releases/issues/59

I have also lost a lot of time not understanding why executing `make docker-otelcontribcol` created something different than published to the Docker registry. I have created an issue here https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7184

**Comment by jpkrohling** [comment] 2022-01-17 12:13
I'm closing this, as we are likely not going to publish 0.41.0 given that 0.42.0 was successfully published. If you feel differently, let me know and I'll reopen this.

**Closed by jpkrohling** 2022-01-17 12:13 UTC

**Comment by lchayoun** [comment] 2022-01-30 09:18
@jpkrohling It happened again with the latest version (0.43.0)

**Comment by KingJ** [comment] 2022-01-30 10:01
@lchayoun Looking over the [0.43.0 build output](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4957206437?check_suite_focus=true), the Publish Github Release step was skipped. I think this has already been identified in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7399 and fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7401.

If you scroll down on the [0.43.0 build summary though](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/1752486406), you can download the binaries and packages that would have been put on the GitHub release. It also looks like @jpkrohling has pushed up the [0.43.0 container image to Docker Hub](https://hub.docker.com/r/otel/opentelemetry-collector-contrib/tags).

**Comment by mx-psi** [comment] 2022-01-31 08:44
Hey all, I believe starting on this releases artifacts will be available on the [`opentelemetry-collector-releases` repo](https://github.com/open-telemetry/opentelemetry-collector-releases). For example, you can find the assets for 0.43 [here](https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.43.0). If I am not mistaken, all future assets will be available there.

cc @KingJ @lchayoun

**Comment by lchayoun** [comment] 2022-01-31 08:52
Thanks @mx-psi!
