### ISSUE TITLE
Prometheus Receiver - honor_labels set to true doesnt work with federation

### ISSUE THREAD

**Issue by rashmichandrashekar** [open-telemetry/opentelemetry-collector-contrib#5757] opened 2021-10-14 20:58 UTC
**Describe the bug**
When using federation, honor_labels set to true doesnt work since the source prometheus server's job name is not found in the list of targets in the destination prometheus config

**Steps to reproduce**
Using federation, try to scrape metrics from another prometheus server with honor_labels set to true. 

**What did you expect to see?**
Metrics collected correctly by the otel collector with the labels from the source prometheus server honored

**What did you see instead?**
An error that says "job or instance cannot be found from labels"

**What version did you use?**
Version: v0.27.0

**What config did you use?**
Config: (e.g. the yaml config file)

    global:
      evaluation_interval: 5s
      scrape_interval: 5s
    scrape_configs:
    - job_name: federate
      honor_labels: true
      metrics_path: '/federate'
      params:
        'match[]': ['job:my_job_name']
      static_configs:
        - targets:
          - 'prometheus-prometheus-oper-prometheus.monitoring:9090'

**Environment**
OS: Ubuntu 20.04
Compiler(if manually compiled): go 1.14

**Additional context**
This seems to be related to the way targets are looked up based on job/instance labels. Related to #5663

**Comment by edude03** [comment] 2021-11-13 19:15
Running into the same issue, is anyone facing this aware of a workaround?

**Comment by alolita** [comment] 2022-02-28 18:46
@dashpole are you looking at this issue? We can also help so let me know.

**Comment by dashpole** [comment] 2022-02-28 18:53
I am not currently working on it, but am happy to help if someone else wants to take it on

**Comment by Aneurysm9** [comment] 2022-02-28 19:56
AFAICT, the issue is that the metric metadata is associated only with target labels, prior to merging them with individual metric labels, and the receiver, when it is given a metric to append, doesn't have access to the original value of `instance` and `job` if they have been overridden by labels in the exposition that are honored.

I think we might be able to do something with automatically appending relabeling rules that would put the original target `job` and `instance` label values in a new label with a name constructed to avoid conflicts.  We could then use that value to look up the metadata and drop the label when converting to pdata.  This might run into issues if label limits are set up, though.

**Comment by dashpole** [comment] 2022-02-28 20:40
There is a different google project that uses a fork of the prometheus server.  They dealt with this by [embedding a metadata fetcher](https://github.com/GoogleCloudPlatform/prometheus/commit/655bb3301b9a93d8bc4490c345ecd81135fc5e50#diff-4535d6172e0a9ab4e0879d71ef67ab69023f6eda9b44100343a6afa04fc8925fR299) in the context passed to Appender ([which be here in the prom receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/17306946fc08283f98b472809e22c2ab1a5d4c68/receiver/prometheusreceiver/internal/ocastore.go#L92)).  I wonder if upstream prometheus maintainers would be amenable to such a solution...

**Comment by gouthamve** [comment] 2022-03-15 14:28
I've run into this while trying to test my fix for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8355 and sent an upstream PR: https://github.com/prometheus/prometheus/pull/10450

If the upstream PR is merged it should remove a lot of complexity from the collector codebase :)

**Closed** 2022-04-05 13:27 UTC
Labels: bug, comp:prometheus, comp: receiver

**Comment by Utwo** [comment] 2023-06-21 16:21
I think this issue is still happening on helm version 0.60.0

**Comment by shacharSirotkin** [comment] 2024-01-31 13:50
> I think this issue is still happening on helm version 0.60.0

Hii, did you find a workaround?

**Comment by Utwo** [comment] 2024-01-31 21:07
> > I think this issue is still happening on helm version 0.60.0
> 
> Hii, did you find a workaround?

No, not yet. I'm using open-telemetry exclusively for collecting traces. For metrics, I moved to a different solution.
