### ISSUE TITLE
Splunk HEC exporter sends empty log messages, which are disregarded with an error message

### ISSUE THREAD

**Issue by rohits-splunk** [open-telemetry/opentelemetry-collector-contrib#20290] opened 2023-03-23 16:05 UTC
### Describe the issue you're reporting

I am trying to export logs from a window server using OTEL collector and HEC exporter , but getting the below error in windows event logs ::

`1.6795869182428775e+09	error	exporterhelper/queued_retry.go:401	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "data_type": "logs", "name": "splunk_hec", "error": "Permanent error: \"HTTP/1.1 400 Bad Request\\r\\nContent-Length: 27\\r\\nConnection: Keep-Alive\\r\\nContent-Type: application/json; charset=UTF-8\\r\\nDate: Thu, 23 Mar 2023 15:55:18 GMT\\r\\nServer: Splunkd\\r\\nVary: Authorization\\r\\nX-Content-Type-Options: nosniff\\r\\nX-Frame-Options: SAMEORIGIN\\r\\n\\r\\n{\\\"text\\\":\\\"No data\\\",\\\"code\\\":5}\"", "dropped_items": 1}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector@v0.71.0/exporter/exporterhelper/queued_retry.go:401
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send
	go.opentelemetry.io/collector@v0.71.0/exporter/exporterhelper/logs.go:135
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
	go.opentelemetry.io/collector@v0.71.0/exporter/exporterhelper/queued_retry.go:205
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
	go.opentelemetry.io/collector@v0.71.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61
`

In the hec endpoint i am using the same endpoint which i tried for sending the events through curl which worked perfectly. Not sure why the exporter is failing.

**Comment by atoulme** [comment] 2023-03-23 16:31
Is Splunk also running on Windows?

**Comment by rohits-splunk** [comment] 2023-03-23 17:48
No this is the Splunk cloud endpoint. Nothing running locally.

**Comment by atoulme** [comment] 2023-03-23 19:11
Understood. We had that report - the "No data" error means that the log record itself is empty. This is a bug ; we should probably drop empty log records.

**Comment by rohits-splunk** [comment] 2023-03-23 19:38
No the log record is not empty, i am sending the same log to signalfx endpoint and its reaching there fine. Just not on Splunk

**Comment by atoulme** [comment] 2023-03-23 20:52
The error specifically says `{"text":"No data","code":5}` which points to absence of data in the log record event being sent, per https://docs.splunk.com/Documentation/SplunkCloud/latest/Data/TroubleshootHTTPEventCollector.

**Comment by vihas-splunk** [comment] 2023-03-25 12:32
@rohits-splunk can you attach the configurations you're using for splunk hec exporter? Are they default?

**Comment by rohits-splunk** [comment] 2023-03-25 16:30
Hi @vihas-splunk  , This is my splunk_hec exporter configuration ::
`exporters:
  # Traces
  sapm:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: "${SPLUNK_TRACE_URL}"
  # Metrics + Events
  signalfx:
    access_token: "XXXX"
    api_url: http://ip-172-XX.us-west-1.compute.internal:6060/
    ingest_url: http://ip-172-XX.us-west-1.compute.internal:9943/
    # Use instead when sending to gateway
    #api_url: http://${SPLUNK_GATEWAY_URL}:6060
    #ingest_url: http://${SPLUNK_GATEWAY_URL}:9943
    sync_host_metadata: true
    correlation:
  # Logs
  splunk_hec:
    token: "bc48819e-41d2-XXX"
    endpoint: "https://XXXX.splunkcloud.com:8088/services/collector/event"
    tls:
      insecure_skip_verify: true
    source: "otel"
    sourcetype: "otel"
    index: main
    health_check_enabled : true
    export_raw: true`

**Comment by vihas-splunk** [comment] 2023-03-25 17:30
is there any chance you can share the logs that you're ingesting?

**Comment by rohits-splunk** [comment] 2023-03-25 19:20
@vihas-splunk  Here you go ::
{"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "nonprod: some other log data"} {"message": "prod: some log data"} {"message": "prod: some log data"} "hec.log" 169L, 7223B                  {"message": "prod: some log data"} {"message": "prod: some log data"}

**Comment by vihas-splunk** [comment] 2023-03-26 09:25
@atoulme can you please assign this to me, I have found the root cause.

**Comment by atoulme** [comment] 2023-03-26 16:17
It’s yours!

**Closed** 2023-04-03 23:07 UTC
Labels: bug, priority:p2, exporter/splunkhec
