### ISSUE TITLE
[recievers/filelog] - key_value_parser not registered

### ISSUE THREAD

**Issue by crobertson-conga** [open-telemetry/opentelemetry-collector-contrib#13631] opened 2022-08-25 19:21 UTC
**Describe the bug**
The key value parser from stanza was merged in response to https://github.com/open-telemetry/opentelemetry-log-collection/issues/455

However, it was never registered, so cannot be used as an operator in the filelog parser receiver. 

**Steps to reproduce**
Have a operator step in a filelog receiver that uses type key_value_parser

in your filelog reciever

**What did you expect to see?**
key=value logs being parsed

**What did you see instead?**
An error upon startup:

Error: cannot build pipelines: failed to create "filelog" receiver, in pipeline "logs": unsupported type 'key_value_parser

**What version did you use?**
Version: 0.58.0

**What config did you use?**
```
config:
  receivers:
    filelog:
      include:
        - /var/log/pods/*/*/*.log
      exclude: []
      operators:
        - type: key_value_parser
          id: general-body-logfmt
          output: severity-parser-0
          parse_from: body
```

**Environment**
Doesn't matter

**Additional context**
Should be a matter of adding a new registration at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/7e14323b53770700e54e1edaa2a0ecb91378bb3e/pkg/stanza/adapter/register.go#L21 and updating the documentation accordingly

**Comment by rehanpfmr** [comment] 2022-08-27 05:57
Hi, Can this be assigned to me?

**Comment by evan-bradley** [comment] 2022-09-01 20:59
@rehanpfmr It's yours.

**Comment by rehanpfmr** [comment] 2022-09-02 05:55
Thanks @evan-bradley

**Comment by djaglowski** [comment] 2022-10-20 16:02
Resolved by #14094

**Closed by djaglowski** 2022-10-20 16:02 UTC
Labels: bug, priority:p2, receiver/filelog

**Comment by jangaraj** [comment] 2023-09-03 00:52
@djaglowski I don't see syslog parser in current [register.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.84.0/pkg/stanza/adapter/register.go). Is it possible that is a root cause of `unsupported type 'syslog_parser'` error, when `ocb` is used? 
Ref: https://stackoverflow.com/questions/77026536/custom-build-of-opentelemetry-collector-is-missing-operator-used-by-receiver

**Comment by djaglowski** [comment] 2023-09-05 15:16
@jangaraj, yes I agree. Thanks for the PR.
