### ISSUE TITLE
frequently prints startup error messages

### ISSUE THREAD

**Issue by mike9421** [open-telemetry/opentelemetry-collector-contrib#32213] opened 2024-04-07 09:24 UTC
### Component(s)

cmd/opampsupervisor

## Description
When I input incorrect OTEL configurations in the remote configuration, `opampsupervisor` frequently prints restart error messages instead of printing according to the `restartTimer` settings. As shown in the picture below: 

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/37992936/df586ef1-1310-4dcf-92ac-52d8c5590c20)

## Steps to Reproduce
1. Fill in the correct configuration to ensure that the opampsupervisor can connect to the backend normally
2. Start the backend OpAMP sample server
3. Start opampsupervisor
4. Providing incorrect remote configurations via the OpAMP UI.
5. View the stdout of opampsupervisor

## Expected Result
Printing error messages according to the time set by the `restartTimer`.

## Actual Result
Continuously printing error messages.

### Collector version

all

### Environment information

OS: Darwin
Compiler: go 1.21

### OpenTelemetry Collector configuration

```yaml
Any wrong configuration, for example:

exporters:
    logging: null
extensions:
    health_check:
        endpoint: 0.0.0.0:13133
receivers:
    otlp:
        protocols:
            https:
                endpoint: localhost:64509
service:
    extensions:
        - health_check
    pipelines:
        logs:
            exporters:
                - logging
            receivers:
                - otlp
```

### Log output

```shell
2024-04-07T17:25:08.990+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.991+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.991+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.991+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.991+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.991+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.991+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.991+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.992+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.992+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.992+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.992+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.992+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.992+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.993+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.993+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.993+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.993+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.993+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}
2024-04-07T17:25:08.993+0800    DEBUG   supervisor/supervisor.go:758    Agent process exited unexpectedly. Will restart in a bit...     {"pid": 19071, "exit_code": 1}

```

### Additional context

Frequently printing error messages is due to the problem of [source code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/191c2c9f5060d961c2faba34687e57c0a5fd5e82/cmd/opampsupervisor/supervisor/commander/commander.go#L104), which can be solved by changing it to `c.doneCh <- struct{}{}`.

But I don't know why to use `close(c.doneCh)`, is there any other consideration?

**Comment by srikanthccv** [comment] 2024-04-07 12:45
This is a duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27891. Will be fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32150

**Comment by crobert-1** [comment] 2024-04-08 16:10
Closing as duplicate

**Closed by crobert-1** 2024-04-08 16:10 UTC
Labels: bug, cmd/opampsupervisor
