### ISSUE TITLE
To create load test case the exporter must have a matching receiver  

### ISSUE THREAD

**Issue by darwhs** [open-telemetry/opentelemetry-collector-contrib#372] opened 2020-06-28 06:58 UTC
**Describe the bug**
Right now I can see that if someone wants to make use of the testbed and create a load tests, for some exporter it is mandatory to have a receiver to mack the backend and receive the traces or data while the work of the mocked backend is to just receive the data and count the number of spans 

**Steps to reproduce**
create simple testcase using awsxray exporter and the otlp receiver.

**What did you expect to see?**
I want to make mockbackend more generic and just work like a receptor and accept data in any format.

**What did you see instead?**
get the cpu and memory consumption but the test cases are getting failed 

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)
v0.4.0

**What config did you use?**
Config: (e.g. the yaml config file)
```

eceivers:
  otlp:
    endpoint: "localhost:61356"
exporters:
  awsxray:
    local_mode: true
    endpoint: "localhost:61357"
    region: "us-west-2"
processors:

  batch:



extensions:
  pprof:
    save_to_file: /Volumes/unix/opentelemetry-collector-contrib/testbed/tests/results/TestTrace10kSPS/AwsXray/cpu.prof

service:
  extensions: [pprof]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray]

```

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
os macos 14.1

**Additional context**

**Comment by darwhs** [comment] 2020-06-29 13:44
Do we have any update on this?

**Comment by tigrannajaryan** [comment] 2020-06-29 18:11
This is by design and is the intended way to use the testbed. It may be possible to improve the testbed to make it easier to add support for new exporters but it is not a roadmap item for maintainers and we do not plan to work on this.

I am closing this issue, please feel free to reopen if you would like to contribute an improvement yourself or know a contributor who may want to work on this.

**Closed by tigrannajaryan** 2020-06-29 18:11 UTC
Labels: enhancement

**Comment by darwhs** [comment] 2020-07-08 07:00
you can assign it to me, I am working on it.
