### ISSUE TITLE
Splunk HEC Exporter Transmission to HEC Endpoint Fails With Missing Body

### ISSUE THREAD

**Issue by bdschaap** [open-telemetry/opentelemetry-collector-contrib#29693] opened 2023-12-07 19:43 UTC
### Component(s)

exporter/splunkhec

## Description
Splunk HEC Exporter transmission to HEC endpoint fails when there is a missing `body` field.  The otel logs data model lists body as an optional field.  I'm using Faro Web SDK which has a log type (measurement) that does not contain a `body` field.

## Steps to Reproduce
Transmit a log without a `body` field.

## Expected Result
OTLP logs received and exported with a missing body field should not fail transmission to a HEC endpoint.  Perhaps a default value should be set.  Alternative is that the HEC endpoint (ie Splunk Forwarder, Splunk Enterprise, Splunk Cloud, etc) should accept a missing body field.  I have encountered this behavior with a Splunk Forwarder.

## Actual Result
400 response code is returned stating bad data format.

### Collector version

opentelemetry-collector-contrib:0.88.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
  splunk_hec/dev:
	token: "<guid>"
	endpoint: "https://splunkforwarder.mydomain.local:8088/services/collector/event"
	source: "otel"
	hec_metadata_to_otel_attrs:
	  source: "service.name"        
	sourcetype: "faro"
	index: "dev"
```

**Comment by crobert-1** [comment] 2023-12-07 20:07
Agreed that the body of a log is optional, as stated in the spec [here.](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-body)

Can you share the full error message you're receiving? I'm wondering if this is possibly a duplicate of #29551.

**Comment by bdschaap** [comment] 2023-12-12 15:05
I tried v0.91.0 and no longer receive an error but I can't find the log in Splunk.  The log is still only transmitted and found in Splunk if I manually supply the body field in the log.  I reverted to v0.88.0 to capture the error message below.

```
2023-12-12T14:41:22.416Z        error   exporterhelper/retry_sender.go:145      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "logs", "name": "splunk_hec", "error": "Permanent error: \"HTTP/1.1 400 Bad Request\\r\\n
Content-Length: 64\\r\\nConnection: Keep-Alive\\r\\nContent-Type: application/json; charset=UTF-8\\r\\nDate: Tue, 12 Dec 2023 14:41:21 GMT\\r\\nServer: Splunkd\\r\\nVary: Authorization\\r\\nX-Content-Type-Options: nosniff\\r\\nX-Frame-Options: SAMEORIGIN\\r\\n\\r\\n{
\\\"text\\\":\\\"Invalid data format\\\",\\\"code\\\":6,\\\"invalid-event-number\\\":0}\"", "dropped_items": 1}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector/exporter@v0.88.0/exporterhelper/retry_sender.go:145
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send
        go.opentelemetry.io/collector/exporter@v0.88.0/exporterhelper/logs.go:176
go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).start.func1
        go.opentelemetry.io/collector/exporter@v0.88.0/exporterhelper/queue_sender.go:126
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).Start.func1
        go.opentelemetry.io/collector/exporter@v0.88.0/exporterhelper/internal/bounded_memory_queue.go:52
```

**Comment by atoulme** [comment] 2023-12-12 16:44
"I can't find the log in Splunk" - how are you looking for it? Can you elaborate? Please open a support case with Splunk to follow up.

**Comment by bdschaap** [comment] 2023-12-12 19:16
My Otel Collector sends logs to a Splunk Heavy Forwarder which then sends them to Splunk Cloud.  I'm searching for the logs in Splunk Cloud.  The logs with the missing body field cannot be found in the specified index and sourcetype on v0.91.0.  If I manually edit the json to add the body field and then retransmit the log to my Otel Collector then I find that log in Splunk Cloud.

I'll open a support case with Splunk.

**Comment by bdschaap** [comment] 2023-12-12 20:15
Makes sense.  I'm referring to the name of the field in [Otel log data model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-body).  I believe the log is transformed to a HEC event by the Splunk HEC Exporter.

**Comment by atoulme** [comment] 2024-01-05 01:42
This is resolved with https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29551. Closing.

**Closed by atoulme** 2024-01-05 01:42 UTC
Labels: bug, exporter/splunkhec
