### ISSUE TITLE
[receiver/hostmetrics] Add an uptime scraper

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#35932] opened 2024-10-22 16:59 UTC
### Component(s)

receiver/hostmetrics

### Is your feature request related to a problem? Please describe.

The uptime of the system can be reported by the hostmetrics receiver.

### Describe the solution you'd like

We would like to define an additional scraper. It would report periodically the uptime of the machine as reported by gopsutil.

This would be reported as a single metric.

**Comment by ChrsMark** [comment] 2024-10-23 12:02
SemConv PR for this: https://github.com/open-telemetry/semantic-conventions/pull/1507

**Comment by braydonk** [comment] 2024-10-23 14:23
I'd propose we call the scraper `system`. We haven't been calling it a rule before but the way the system semantic conventions have worked out mapped to our hostmetrics scrapers is that the namespace of the metric ends up being the name of the scraper. i.e. `system.memory.*` will be produced by `memoryscraper` and so on. So `system.uptime` being produced by `systemscraper` would follow the rule and future-proof us against potential future root `system` metrics (I can't think of any potential examples that might come up but this way we wouldn't be stuck if it happens).
@dmitryax what are your thoughts here?

**Comment by kevinnoel-be** [comment] 2024-10-23 16:08
Duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31627 ?

**Closed** 2024-10-29 06:52 UTC
Labels: enhancement, receiver/hostmetrics
