### ISSUE TITLE
Issue with routing processor

### ISSUE THREAD

**Issue by Apollorion** [open-telemetry/opentelemetry-collector-contrib#6920] opened 2021-12-20 20:55 UTC
**Describe the bug**
Processor says exporter is not found for `default_exporters`.

**Steps to reproduce**
Create an OpenTelemetryCollector resource with the following config:
```
receivers:
  otlp:
    protocols:
      grpc:
processors:
  routing:
    from_attribute: X-OTLP-Tenant
    default_exporters: [otlp/prod]
    table:
    - value: dev
      exporters: [otlp/dev]
exporters:
  otlp/prod:
    endpoint: internal.tracing.svc.cluster.local
  otlp/dev:
    endpoint: internal-dev.tracing.svc.cluster.local
service:
  pipelines:
    traces/otlp:
      receivers: [otlp]
      processors: [routing]
      exporters: [otlp/prod, otlp/dev]
```

**What did you expect to see?**
Successfully created container

**What did you see instead?**
Crashlooping container

```
Error: cannot start processors: error registering default exporter "otlp/prod": exporter not found
2021/12/20 19:28:34 collector server run finished with error: cannot start processors: error registering default exporter "otlp/prod": exporter not found
```

**What version did you use?**
0.40.0

**Environment**
EKS bottlerocket k8s 1.20

Also, I _believe_ the documented example for this processor is wrong. It shows `default_exporters` as a string, but I think it is supposed to be a list of strings. Based off [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/routingprocessor/config.go#L29).

**Comment by jpkrohling** [comment] 2021-12-21 09:14
I'll take a look at this.

**Comment by timberhill** [comment] 2022-01-14 10:31
Same issue here. This is also happening if you remove `default_exporters`, but the error then points to the top exporter in `table` (would be `otlp/dev` in this example).

**Comment by timberhill** [comment] 2022-01-14 10:58
For reference, here is the config we are testing with two Prometheus instances, hope this helps.

```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1
  prometheus/hc:
    endpoint: "0.0.0.0:8899"
    const_labels:
      label1: value2
  logging:

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  routing:
    default_exporters:
    - prometheus
    attribute_source: context
    from_attribute: X-Custom-Metrics-Header
    table:
    - value: business-critical
      exporters:
      - prometheus
    - value: high-cardinality
      exporters:
      - prometheus/hc
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch, routing]
      exporters: [logging, prometheus, prometheus/hc]
```

Log output, including the error:
```
2022-01-14T10:19:20.796Z	info	builder/exporters_builder.go:255	Exporter was built.	{"kind": "exporter", "name": "jaeger"}
2022-01-14T10:19:20.798Z	info	builder/exporters_builder.go:255	Exporter was built.	{"kind": "exporter", "name": "prometheus/hc"}
2022-01-14T10:19:20.799Z	info	builder/exporters_builder.go:255	Exporter was built.	{"kind": "exporter", "name": "logging"}
2022-01-14T10:19:20.799Z	info	builder/exporters_builder.go:255	Exporter was built.	{"kind": "exporter", "name": "prometheus"}
2022-01-14T10:19:20.799Z	info	builder/exporters_builder.go:255	Exporter was built.	{"kind": "exporter", "name": "zipkin"}
2022-01-14T10:19:20.800Z	info	routingprocessor@v0.42.0/processor.go:50	building processor	{"kind": "processor", "name": "routing"}
2022-01-14T10:19:20.800Z	info	builder/pipelines_builder.go:223	Pipeline was built.	{"name": "pipeline", "name": "metrics"}
2022-01-14T10:19:20.800Z	info	builder/pipelines_builder.go:223	Pipeline was built.	{"name": "pipeline", "name": "traces"}
2022-01-14T10:19:20.800Z	info	builder/receivers_builder.go:226	Receiver was built.	{"kind": "receiver", "name": "otlp", "datatype": "metrics"}
2022-01-14T10:19:20.800Z	info	builder/receivers_builder.go:226	Receiver was built.	{"kind": "receiver", "name": "otlp", "datatype": "traces"}
2022-01-14T10:19:20.800Z	info	service/service.go:82	Starting extensions...
2022-01-14T10:19:20.800Z	info	extensions/extensions.go:38	Extension is starting...	{"kind": "extension", "name": "pprof"}
2022-01-14T10:19:20.802Z	info	pprofextension@v0.42.0/pprofextension.go:78	Starting net/http/pprof server	{"kind": "extension", "name": "pprof", "config": {"TCPAddr":{"Endpoint":":1888"},"BlockProfileFraction":0,"MutexProfileFraction":0,"SaveToFile":""}}
2022-01-14T10:19:20.803Z	info	extensions/extensions.go:42	Extension started.	{"kind": "extension", "name": "pprof"}
2022-01-14T10:19:20.803Z	info	extensions/extensions.go:38	Extension is starting...	{"kind": "extension", "name": "zpages"}
2022-01-14T10:19:20.803Z	info	zpagesextension/zpagesextension.go:40	Register Host's zPages	{"kind": "extension", "name": "zpages"}
2022-01-14T10:19:20.804Z	info	zpagesextension/zpagesextension.go:53	Starting zPages extension	{"kind": "extension", "name": "zpages", "config": {"TCPAddr":{"Endpoint":":55679"}}}
2022-01-14T10:19:20.804Z	info	extensions/extensions.go:42	Extension started.	{"kind": "extension", "name": "zpages"}
2022-01-14T10:19:20.804Z	info	extensions/extensions.go:38	Extension is starting...	{"kind": "extension", "name": "health_check"}
2022-01-14T10:19:20.804Z	info	healthcheckextension@v0.42.0/healthcheckextension.go:44	Starting health_check extension	{"kind": "extension", "name": "health_check", "config": {"Port":0,"TCPAddr":{"Endpoint":"0.0.0.0:13133"},"Path":"/","CheckCollectorPipeline":{"Enabled":false,"Interval":"5m","ExporterFailureThreshold":5}}}
2022-01-14T10:19:20.804Z	info	extensions/extensions.go:42	Extension started.	{"kind": "extension", "name": "health_check"}
2022-01-14T10:19:20.804Z	info	service/service.go:87	Starting exporters...
2022-01-14T10:19:20.804Z	info	builder/exporters_builder.go:40	Exporter is starting...	{"kind": "exporter", "name": "zipkin"}
2022-01-14T10:19:20.806Z	info	builder/exporters_builder.go:48	Exporter started.	{"kind": "exporter", "name": "zipkin"}
2022-01-14T10:19:20.806Z	info	builder/exporters_builder.go:40	Exporter is starting...	{"kind": "exporter", "name": "jaeger"}
2022-01-14T10:19:20.810Z	info	jaegerexporter@v0.42.0/exporter.go:186	State of the connection with the Jaeger Collector backend	{"kind": "exporter", "name": "jaeger", "state": "IDLE"}
2022-01-14T10:19:20.810Z	info	builder/exporters_builder.go:48	Exporter started.	{"kind": "exporter", "name": "jaeger"}
2022-01-14T10:19:20.810Z	info	builder/exporters_builder.go:40	Exporter is starting...	{"kind": "exporter", "name": "prometheus/hc"}
2022-01-14T10:19:20.810Z	info	builder/exporters_builder.go:48	Exporter started.	{"kind": "exporter", "name": "prometheus/hc"}
2022-01-14T10:19:20.810Z	info	builder/exporters_builder.go:40	Exporter is starting...	{"kind": "exporter", "name": "logging"}
2022-01-14T10:19:20.810Z	info	builder/exporters_builder.go:48	Exporter started.	{"kind": "exporter", "name": "logging"}
2022-01-14T10:19:20.810Z	info	builder/exporters_builder.go:40	Exporter is starting...	{"kind": "exporter", "name": "prometheus"}
2022-01-14T10:19:20.811Z	info	builder/exporters_builder.go:48	Exporter started.	{"kind": "exporter", "name": "prometheus"}
2022-01-14T10:19:20.811Z	info	service/service.go:92	Starting processors...
2022-01-14T10:19:20.811Z	info	builder/pipelines_builder.go:54	Pipeline is starting...	{"name": "pipeline", "name": "metrics"}
Error: cannot start processors: error registering default exporter "prometheus": exporter not found
2022/01/14 10:19:20 collector server run finished with error: cannot start processors: error registering default exporter "prometheus": exporter not found
```

**Comment by jpkrohling** [comment] 2022-01-17 12:43
I haven't forgotten about this, hopefully I'll be able to get to it this week.

**Comment by jpkrohling** [comment] 2022-01-27 19:33
Was this fixed by this PR already? https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6984

I ran both examples from this issue against the current main branch and they both worked. I'm closing this, but feel free to reopen if this is not fixed in 0.43.0.

**Comment by timberhill** [comment] 2022-01-28 09:38
The PR seems to have only made changes to the readme.
There seem to be two separate issues here - one in the example and the other somewhere in the routing processor, so the error still appears :(

Did you run the [`config_metrics.yaml`](processor/routingprocessor/testdata/config_metrics.yaml) example to test it? It uses logging exporter there, would that be handled differently from metrics?

I can provide a minimum reproducible example if helpful at all.

**Comment by jpkrohling** [comment] 2022-01-28 13:25
That would be very helpful. I did run both examples from this issue against the current main branch, which is very similar to v0.43.0. If you could reproduce it with v0.43.0, it would help me a lot.

**Comment by timberhill** [comment] 2022-01-28 16:12
Thanks! The minimal-ish example with two prometheus instances is here: https://github.com/timberhill/otel-routing-demo. To figure it out, we started with [this demo](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples/demo) and (crudely) modified the server to emit a metrics with a label that determines which prometheus it is going to.

**Comment by jpkrohling** [comment] 2022-01-28 17:53
I got to reproduce it, thank you! The problem is that happening when there are two pipelines. In your case, you have one for traces and one for metrics. When removing the traces pipeline, it seems to work.

**Comment by jpkrohling** [comment] 2022-02-15 10:02
This should be part of 0.45.0, due either tomorrow or next week.

**Comment by RicardoLinck** [comment] 2022-02-17 12:28
I'm still experiencing a similar issue regarding this (after upgrading to `v0.45.0`). This time it is with an exporter that is not the default:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  routing/traces:
    from_attribute: "service.name"
    attribute_source: resource
    default_exporters:
    - logging
    table:
    - value: fake-server
      exporters: [file/analytics]
    - value: another-fake
      exporters: [file/operational]
  batch:

exporters:
  file/analytics:
    path: /data/analytics.json
  file/operational:
    path: /data/operational.json
  logging:
    logLevel: debug 

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, routing/traces]
      exporters: [logging, file/analytics, file/operational]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, file/operational]
```

These are the logs:
```
2022-02-17T12:19:59.802Z     info    service/service.go:92   Starting processors...
2022-02-17T12:19:59.802Z     info    builder/pipelines_builder.go:54 Pipeline is starting... {"name": "pipeline", "name": "metrics"}
2022-02-17T12:19:59.802Z     info    builder/pipelines_builder.go:65 Pipeline is started.    {"name": "pipeline", "name": "metrics"}
2022-02-17T12:19:59.802Z     info    builder/pipelines_builder.go:54 Pipeline is starting... {"name": "pipeline", "name": "traces"}
Error: cannot start processors: error registering route "fake-server" for exporter "file/analytics": exporter not found
2022/02/17 12:19:59 collector server run finished with error: cannot start processors: error registering route "fake-server" for exporter "file/analytics": exporter not found
```

If I change my metrics pipelines to include both exporters like this, it works:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  routing/traces:
    from_attribute: "service.name"
    attribute_source: resource
    default_exporters:
    - logging
    table:
    - value: fake-server
      exporters: [file/analytics]
    - value: another-fake
      exporters: [file/operational]
  batch:

exporters:
  file/analytics:
    path: /data/analytics.json
  file/operational:
    path: /data/operational.json
  logging:
    logLevel: debug 

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, routing/traces]
      exporters: [logging, file/analytics, file/operational]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, file/operational, file/analytics]
```

Logs:
```
2022-02-17T12:22:59.690Z     info    builder/exporters_builder.go:255        Exporter was built.     {"kind": "exporter", "name": "logging"}
2022-02-17T12:22:59.691Z     info    builder/exporters_builder.go:255        Exporter was built.     {"kind": "exporter", "name": "file/operational"}
2022-02-17T12:22:59.691Z     info    builder/exporters_builder.go:255        Exporter was built.     {"kind": "exporter", "name": "file/analytics"}
2022-02-17T12:22:59.691Z     info    routingprocessor@v0.45.0/processor.go:51        building processor      {"kind": "processor", "name": "routing/traces"}
2022-02-17T12:22:59.691Z     info    builder/pipelines_builder.go:223        Pipeline was built.     {"name": "pipeline", "name": "traces"}
2022-02-17T12:22:59.691Z     info    builder/pipelines_builder.go:223        Pipeline was built.     {"name": "pipeline", "name": "metrics"}
2022-02-17T12:22:59.691Z     info    builder/receivers_builder.go:226        Receiver was built.     {"kind": "receiver", "name": "otlp", "datatype": "traces"}
2022-02-17T12:22:59.691Z     info    builder/receivers_builder.go:226        Receiver was built.     {"kind": "receiver", "name": "otlp", "datatype": "metrics"}
2022-02-17T12:22:59.691Z     info    service/service.go:82   Starting extensions...
2022-02-17T12:22:59.691Z     info    service/service.go:87   Starting exporters...
2022-02-17T12:22:59.691Z     info    builder/exporters_builder.go:40 Exporter is starting... {"kind": "exporter", "name": "file/operational"}
2022-02-17T12:22:59.691Z     info    builder/exporters_builder.go:48 Exporter started.       {"kind": "exporter", "name": "file/operational"}
2022-02-17T12:22:59.691Z     info    builder/exporters_builder.go:40 Exporter is starting... {"kind": "exporter", "name": "file/analytics"}
2022-02-17T12:22:59.691Z     info    builder/exporters_builder.go:48 Exporter started.       {"kind": "exporter", "name": "file/analytics"}
2022-02-17T12:22:59.691Z     info    builder/exporters_builder.go:40 Exporter is starting... {"kind": "exporter", "name": "logging"}
2022-02-17T12:22:59.691Z     info    builder/exporters_builder.go:48 Exporter started.       {"kind": "exporter", "name": "logging"}
2022-02-17T12:22:59.691Z     info    service/service.go:92   Starting processors...
2022-02-17T12:22:59.691Z     info    builder/pipelines_builder.go:54 Pipeline is starting... {"name": "pipeline", "name": "traces"}
2022-02-17T12:22:59.691Z     info    builder/pipelines_builder.go:65 Pipeline is started.    {"name": "pipeline", "name": "traces"}
2022-02-17T12:22:59.691Z     info    builder/pipelines_builder.go:54 Pipeline is starting... {"name": "pipeline", "name": "metrics"}
2022-02-17T12:22:59.691Z     info    builder/pipelines_builder.go:65 Pipeline is started.    {"name": "pipeline", "name": "metrics"}
2022-02-17T12:22:59.691Z     info    service/service.go:97   Starting receivers...
2022-02-17T12:22:59.691Z     info    builder/receivers_builder.go:68 Receiver is starting... {"kind": "receiver", "name": "otlp"}
2022-02-17T12:22:59.691Z     info    otlpreceiver/otlp.go:69 Starting GRPC server on endpoint 0.0.0.0:4317   {"kind": "receiver", "name": "otlp"}
2022-02-17T12:22:59.692Z     info    otlpreceiver/otlp.go:87 Starting HTTP server on endpoint 0.0.0.0:4318   {"kind": "receiver", "name": "otlp"}
2022-02-17T12:22:59.692Z     info    otlpreceiver/otlp.go:147        Setting up a second HTTP listener on legacy endpoint 0.0.0.0:55681      {"kind": "receiver", "name": "otlp"}
2022-02-17T12:22:59.692Z     info    otlpreceiver/otlp.go:87 Starting HTTP server on endpoint 0.0.0.0:55681  {"kind": "receiver", "name": "otlp"}
2022-02-17T12:22:59.692Z     info    builder/receivers_builder.go:73 Receiver started.       {"kind": "receiver", "name": "otlp"}
2022-02-17T12:22:59.692Z     info    service/telemetry.go:95 Setting up own telemetry...
2022-02-17T12:22:59.693Z     info    service/telemetry.go:115        Serving Prometheus metrics      {"address": ":8888", "level": "basic", "service.instance.id": "eb433cc7-dc51-43ca-8455-fa8164649434", "service.version": "latest"}
2022-02-17T12:22:59.693Z     info    service/collector.go:229        Starting otelcol-contrib...     {"Version": "0.45.0", "NumCPU": 16}
2022-02-17T12:22:59.693Z     info    service/collector.go:124        Everything is ready. Begin running and processing data.
```

**Comment by jdgeisler** [comment] 2022-02-18 18:06
I am also running into this same error when trying to use an exporter thats not default. We have multiple pipelines and are only using the routing processor for one of them.

@jpkrohling would we be able to resolve this by expanding the error handling in your [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7423) to also ignore the `errExporterNotFound` error?

**Comment by jpkrohling** [comment] 2022-03-01 10:54
I'm sorry for taking so long to give some feedback, but you got the right spirit by sending a PR! Thank you for that, you are the hero!

**Closed** 2022-03-01 10:54 UTC
Labels: bug

**Comment by jdgeisler** [comment] 2022-03-01 14:34
No problem at all, it was my pleasure!
