### ISSUE TITLE
prometheus exporter not able to export delta histograms 

### ISSUE THREAD

**Issue by mageddo** [open-telemetry/opentelemetry-collector-contrib#27570] opened 2023-10-09 23:13 UTC
### Is your feature request related to a problem? Please describe.

Actually I didn't achieved how to export histograms using delta instead of cumulative because the metric is [just dropped][2] in this case.

[1]: https://github.com/open-telemetry/opentelemetry-go/issues/2868
[2]: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9387a2cd2c7072f39fecfaf3942e983e991fd6c8/exporter/prometheusexporter/accumulator.go#L229

### Describe the solution you'd like

I would be a good idea to support that kind of Aggregation Temporality as described [here][1]

### Describe alternatives you've considered

Use cumulative which is a much more complex solution as I need the amount in the delta of time, not the cumulative

**Comment by mx-psi** [comment] 2023-10-10 10:18
Duplicate of #19153, let's continue the discussion over there

**Closed by mx-psi** 2023-10-10 10:18 UTC
Labels: enhancement, needs triage
