### ISSUE TITLE
500 error when scraping metrics from otel-collector pod when loadbalancing exporter is used

### ISSUE THREAD

**Issue by juissi-t** [open-telemetry/opentelemetry-collector-contrib#30477] opened 2024-01-12 14:02 UTC
### Component(s)

exporter/loadbalancing

## Description

I enabled loadbalancing exporter on our collector pods. After a while (~1 hour), Prometheus fails to scrape metrics from the pods which have the exporter configured. Below is an error message from one pod.

```
* Connected to localhost (::1) port 8888
> GET /metrics HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/8.2.1
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Fri, 12 Jan 2024 13:41:47 GMT
< Content-Length: 401
< 
An error has occurred while serving metrics:

collected metric "otelcol_exporter_queue_size" { label:{name:"exporter"  value:"loadbalancing"}  label:{name:"service_instance_id"  value:"f3215806-0275-446f-acdc-32c306d25337"}  label:{name:"service_name"  value:"otelcol-contrib"}  label:{name:"service_version"  value:"0.92.0"}  gauge:{value:0}} was collected before with the same name and label values
```

## Steps to Reproduce

- Enable loadbalancing exporter.

## Expected Result

- Prometheus metrics work correctly

## Actual Result

- Prometheus metrics fail after a while

### Collector version

0.92.0

## Environment
OS: EKS 1.26 Bottlerocket

### OpenTelemetry Collector configuration

```yaml
exporters:
  debug: {}
  loadbalancing:
    protocol:
      otlp:
        sending_queue:
          queue_size: 10000
        tls:
          insecure: true
    resolver:
      k8s:
        service: opentelemetry-collector-sts.monitoring
  logging: {}
extensions:
  health_check: {}
processors:
  batch: {}
  k8sattributes:
    extract:
      labels:
      - from: pod
        key_regex: (.*)
        tag_name: $$1
      metadata:
      - k8s.namespace.name
      - k8s.deployment.name
      - k8s.statefulset.name
      - k8s.daemonset.name
      - k8s.cronjob.name
      - k8s.job.name
      - k8s.node.name
      - k8s.pod.name
      - k8s.pod.uid
      - k8s.pod.start_time
    filter:
      node_from_env_var: K8S_NODE_NAME
    passthrough: false
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: connection
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resource:
    attributes:
    - action: upsert
      key: cluster
      value: dev
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 10s
        static_configs:
        - targets:
          - ${env:MY_POD_IP}:8888
  zipkin:
    endpoint: 0.0.0.0:9411
service:
  extensions:
  - health_check
  pipelines:
    metrics:
      exporters:
      - loadbalancing
      processors:
      - k8sattributes
      - memory_limiter
      - resource
      - batch
      receivers:
      - otlp
    traces:
      exporters:
      - loadbalancing
      processors:
      - k8sattributes
      - memory_limiter
      - resource
      - batch
      receivers:
      - otlp
      - jaeger
  telemetry:
    metrics:
      address: 0.0.0.0:8888
```

**Comment by jpkrohling** [comment] 2024-01-29 13:46
I think this is more likely to be something with the Prometheus receiver/exporter than with the load balancing, given that this seems to be about the component's own metrics, rather than the load balanced telemetry.

**Comment by swar8080** [comment] 2024-01-29 20:22
Getting the same error with this loadbalancer configuration

```
    exporters:
      loadbalancing:
        protocol:
          otlp:
            sending_queue:
              queue_size: 10000
            tls:
              insecure: true
        resolver:
          k8s:
            service: abc-collector-headless.observability

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [otlp/forwarder, debug]
        traces:
          receivers: [otlp]
          exporters: [loadbalancing, debug]
```

**Comment by juissi-t** [comment] 2024-01-31 07:15
Linking a couple of similar sounding issues here:
* https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30697
* https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30835

**Comment by dashpole** [comment] 2024-01-31 19:20
From the collector config, it doesn't look like you are actually using the prometheus receiver or prometheus exporter in a pipeline?

**Comment by juissi-t** [comment] 2024-02-01 13:26
> From the collector config, it doesn't look like you are actually using the prometheus receiver or prometheus exporter in a pipeline?

No, I'm not. This can be reproduced easily without those, just by using the loadbalancing exporter.

**Comment by juissi-t** [comment] 2024-02-01 14:35
Trying to gather my thoughts a bit here, so please forgive me if you find this messy.

1. Loadbalancing exporter starts and registers a metric `otelcol_exporter_queue_size{exporter="loadbalancing",service_instance_id="8b8c3359-8b34-488b-9f22-8cfa8081db97",service_name="otelcol-contrib",service_version="0.92.0"}`.
   * What registers this metric? Is it the OTLP exporter?
2. When a load balanced endpoint changes, the metric seems to be duplicated and we get the error mentioned in the original report.
   * Is there now a second OTLP exporter process/thread/coroutine running?
3. When `sending_queue` is disabled, the error does not happen.
   * Does this imply that the problem is on the OTLP exporter side, and just the code registering this one metric related to the queue is somehow broken?
4. The problem does not happen with version 0.91.0, but it does with 0.92.0. What changed between those versions that might have caused this?

**Comment by Juliaj** [comment] 2024-02-01 18:49
@juissi-t , some information to your questions above
1. This metric is registered as part of retry queue, see code [here](https://github.com/open-telemetry/opentelemetry-collector/blob/5bcd109c718fc9f11f070ae66c79770629854872/exporter/exporterhelper/queue_sender.go#L36). 
2. This is a good hypothesis and needs more debugging to confirm.
3. I noticed this too. In my repro, if we use DNS resolver, this also doesn't repro. So a combo of k8s resolver + sending_queue makes this happen. 
4. This is a good find! I can spend time to look into this.

**Comment by Juliaj** [comment] 2024-02-02 07:51
With more debugging, the code from Otel-collector repo, query_sender.go [recordWithOtel](https://github.com/open-telemetry/opentelemetry-collector/blob/40c7db876f048a576bb6833984dd8f8f1b88ef7d/exporter/exporterhelper/queue_sender.go#L151-L157)  introduced in release `0.92.0` may be problematic.   

@dmitryax, would you be able to shed some light? 


```
func (qs *queueSender) recordWithOtel(meter otelmetric.Meter) error {
	var err, errs error

	attrs := otelmetric.WithAttributeSet(attribute.NewSet(attribute.String(obsmetrics.ExporterKey, qs.fullName)))

	qs.metricSize, err = meter.Int64ObservableGauge(
		obsmetrics.ExporterKey+"/queue_size",
		otelmetric.WithDescription("Current size of the retry queue (in batches)"),
		otelmetric.WithUnit("1"),
		otelmetric.WithInt64Callback(func(_ context.Context, o otelmetric.Int64Observer) error {
			o.Observe(int64(qs.queue.Size()), attrs)
			return nil
		}),
	)
```

**Comment by Juliaj** [comment] 2024-02-02 16:44
@jpkrohling , could you provide more insight on the connection of this to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16826 ?

**Comment by Juliaj** [comment] 2024-02-07 23:03
@juissi-t, would you be able to test the repro with the current commits from this repository in your environment ? I synced the recent commits from Otel collector Git repository and this repository to build an image. I am _not_ able to repro with the steps above. Just wondering whether you could help verify.

**Comment by juissi-t** [comment] 2024-02-08 06:43
> @juissi-t, would you be able to test the repro with the current commits from this repository in your environment ? I synced the recent commits from Otel collector Git repository and this repository to build an image. I am _not_ able to repro with the steps above. Just wondering whether you could help verify.

Yes, I can deploy the image to our development environment to check. Please let me know where I can get the image from.

**Comment by codeboten** [comment] 2024-02-08 19:44
@juissi-t can you confirm that this issue is not reproducible w/ v0.94.0 that was just released yesterday?

**Comment by Juliaj** [comment] 2024-02-13 03:43
@codeboten , @juissi-t , I verified that w/v0.94.0, this issue was not reproducible in our setup.

**Comment by jpkrohling** [comment] 2024-02-14 09:56
I'm closing, feel free to reopen if this is still an issue.

**Closed by jpkrohling** 2024-02-14 09:56 UTC
Labels: bug, waiting for author, exporter/loadbalancing
