### ISSUE TITLE
Pipelines: Step Cache Go takes too long

### ISSUE THREAD

**Issue by martin-majlis-s1** [open-telemetry/opentelemetry-collector-contrib#21506] opened 2023-05-05 10:03 UTC
### Describe the issue you're reporting

Workflow [build-and-test.yaml](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/workflows/build-and-test.yml#L21) has time limit 30 minutes. However step `Cache Go` is broken. It runs sometimes for over 20 minutes and then there is no time to finish the real steps.

Example: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4891517794/jobs/8732329218?pr=20733

```
/usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/go.mod: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/.github/PULL_REQUEST_TEMPLATE.md: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/.github/ISSUE_TEMPLATE/feature_request.md: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/.github/ISSUE_TEMPLATE/bug_report.md: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/CONTRIBUTING.md: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/klog_test.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/SECURITY_CONTACTS: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/examples/log_file/usage_log_file.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/examples/coexist_glog/coexist_glog.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/examples/set_output/usage_set_output.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/examples/klogr/main.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/code-of-conduct.md: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/klog.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/OWNERS: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/RELEASE.md: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/README.md: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/go.sum: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/.travis.yml: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/klog_file.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/klogr/README.md: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/klogr/klogr.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/klogr/klogr_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/integration_tests/klog_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/k8s.io/klog@v1.0.0/integration_tests/internal/main.go: Cannot open: File exists
```

Times shown in UI are misleading. Although when it's progress it shows times over 20 minutes, when it finishes there is reported time under 1 minutes.

<img width="1411" alt="Screenshot 2023-05-05 at 12 00 00" src="https://user-images.githubusercontent.com/122797378/236429207-ea62fafb-b942-4ecb-825d-bff12d6a870f.png">

**Comment by atoulme** [comment] 2023-05-06 03:37
I think this was a github actions issue. We can leave this open and collect other reports.

**Comment by atoulme** [comment] 2023-05-10 06:43
I've seen this a few times now, and am not sure what's happening with the cache.

**Comment by TylerHelmuth** [comment] 2023-05-10 13:13
I think there is definitely something up with the cache step right now. It does sometimes work, but it fails all the time.

**Comment by atoulme** [comment] 2023-05-11 07:17
<img width="1370" alt="Screenshot 2023-05-11 at 12 16 27 AM" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/16758/61ab6a04-e32a-478a-9cfd-1e103971f139">
I think we cache both with the setup-go and the go cache steps. I will try to remove caching in setup-go and see if it helps.

**Comment by mx-psi** [comment] 2023-05-11 08:21
Looks promising,

- On main CI for #21785 (merged before #21795), in the [exporter Go 1.20 unit tests the Setup Go step took 1m 26s](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4944852001/jobs/8840847650) and the total time for the workflow was 10m 58s.
- On main CI for #21269 (merged after #21795), in the [exporter Go 1.20 unit tests the Setup Go step took 1s](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4945482536/jobs/8842290144), and the total time for the workflow was 4m 37s.

I am not sure how reliable the individual time measurements on steps are, since they don't add up to the total in the case of #21785 (maybe it also counts "time to provision a Github Actions runner"?).

**Comment by mx-psi** [comment] 2023-05-11 13:58
Possibly relates to #10289 which was deemed to be an instance of actions/cache/issues/810. We may want to try https://github.com/actions/cache/issues/810#issuecomment-1222550359 if we haven't already

**Comment by TylerHelmuth** [comment] 2023-05-11 14:10
@mx-psi probably a good idea to use that timeout no matter what. We never want the time to restore the cache to even come close to the time it would take to run the steps without the cache.

**Comment by djaglowski** [comment] 2023-08-09 14:42
Looks like this issue (root cause https://github.com/actions/cache/issues/810) may have finally been fixed upstream in https://github.com/actions/cache/pull/1217. I don't see a new release just yet though.

**Closed** 2023-08-16 13:25 UTC
Labels: ci-cd
