### ISSUE TITLE
host metrics only sent once  googlecloudexporter

### ISSUE THREAD

**Issue by ljulliar** [open-telemetry/opentelemetry-collector-contrib#17900] opened 2023-01-21 18:09 UTC
### Component(s)

receiver/hostmetrics

## Description
When combining hostmetricsreceiver with googlecloud exporter metrics are  sent only once to Google Cloud Loggin

## Steps to Reproduce
- Compile and install the otelcol builder config below. Deploy to a Ubuntu server (in my case a bare metal server, not a containerized version running)
- Configure the receicing GCP projects
- launch otelcol service.

## Expected Result
Metrics should be sent every minute in my case. 

## Actual Result
They are only sent once at the end of the fist minute. In addition to that the JSON payload contains a descriptor for each metric but there is no value of the metric in any json payload

### Collector version

0.61.0

## Environment
OS: Ubuntu Xenial
Compiler(if manually compiled): go version go1.19.4 linux/amd64

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics:
    collection_interval: 1m
    root_path: /
    scrapers:
      memory:
      load:
        cpu_average: true
      disk:
        include:
          devices: [/dev/md1]
          match_type: strict
      network:
        include:
          interfaces: [enp1s0f0]
          match_type: strict

exporters:
  googlecloud:
    project: npt-monitoring
    retry_on_failure:
      enabled: false
    log:
      default_log_name: opentelemetry.io/bigfish-exported-log

processors:
  memory_limiter:
    check_interval: 2s
    limit_mib: 1000
    spike_limit_mib: 200
  batch:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
    timeout: 10s

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [googlecloud]
```

### Log output

```shell
First lot of metrics logged to Google Cloud Logging

  {
    "protoPayload": {
      "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
      "authenticationInfo": {
        "principalEmail": "xxxxxx@gmail.com",
        "principalSubject": "user:xxxxxx@gmail.com"
      },
      "requestMetadata": {
        "callerIp": "...",
        "callerSuppliedUserAgent": "opentelemetry-collector-contrib 1.0.0 grpc-go/1.49.0,gzip(gfe)",
        "requestAttributes": {
          "time": "2023-01-21T17:48:00.663769329Z",
          "auth": {}
        },
        "destinationAttributes": {}
      },
      "serviceName": "monitoring.googleapis.com",
      "methodName": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
      "authorizationInfo": [
        {
          "resource": "122765205262",
          "permission": "monitoring.metricDescriptors.create",
          "granted": true,
          "resourceAttributes": {}
        }
      ],
      "resourceName": "projects/npt-monitoring",
      "request": {
        "metricDescriptor": {
          "metricKind": "GAUGE",
          "type": "workload.googleapis.com/system.network.connections",
          "valueType": "INT64",
          "description": "The number of connections.",
          "displayName": "system.network.connections",
          "name": "system.network.connections",
          "unit": "{connections}"
        },
        "name": "projects/npt-monitoring",
        "@type": "type.googleapis.com/google.monitoring.v3.CreateMetricDescriptorRequest"
      },
      "response": {
        "valueType": "INT64",
        "type": "workload.googleapis.com/system.network.connections",
        "@type": "type.googleapis.com/google.api.MetricDescriptor",
        "displayName": "system.network.connections",
        "name": "projects/npt-monitoring/metricDescriptors/workload.googleapis.com/system.network.connections",
        "metricKind": "GAUGE",
        "unit": "{connections}",
        "description": "The number of connections."
      }
    },
    "insertId": "14ssjw1e6jnfp",
    "resource": {
      "type": "audited_resource",
      "labels": {
        "method": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
        "project_id": "npt-monitoring",
        "service": "monitoring.googleapis.com"
      }
    },
    "timestamp": "2023-01-21T17:48:00.658589206Z",
    "severity": "NOTICE",
    "logName": "projects/npt-monitoring/logs/cloudaudit.googleapis.com%2Factivity",
    "receiveTimestamp": "2023-01-21T17:48:00.876992852Z"
  }

  {
    "protoPayload": {
      "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
      "authenticationInfo": {
        "principalEmail": "xxxxxx@gmail.com",
        "principalSubject": "user:xxxxxx@gmail.com"
      },
      "requestMetadata": {
        "callerIp": "195.154.81.82",
        "callerSuppliedUserAgent": "opentelemetry-collector-contrib 1.0.0 grpc-go/1.49.0,gzip(gfe)",
        "requestAttributes": {
          "time": "2023-01-21T17:48:00.697255405Z",
          "auth": {}
        },
        "destinationAttributes": {}
      },
      "serviceName": "monitoring.googleapis.com",
      "methodName": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
      "authorizationInfo": [
        {
          "resource": "122765205262",
          "permission": "monitoring.metricDescriptors.create",
          "granted": true,
          "resourceAttributes": {}
        }
      ],
      "resourceName": "projects/npt-monitoring",
      "request": {
        "metricDescriptor": {
          "unit": "{packets}",
          "metricKind": "CUMULATIVE",
          "valueType": "INT64",
          "displayName": "system.network.dropped",
          "description": "The number of packets dropped. (Deprecated)",
          "name": "system.network.dropped",
          "type": "workload.googleapis.com/system.network.dropped"
        },
        "@type": "type.googleapis.com/google.monitoring.v3.CreateMetricDescriptorRequest",
        "name": "projects/npt-monitoring"
      },
      "response": {
        "@type": "type.googleapis.com/google.api.MetricDescriptor",
        "displayName": "system.network.dropped",
        "name": "projects/npt-monitoring/metricDescriptors/workload.googleapis.com/system.network.dropped",
        "valueType": "INT64",
        "type": "workload.googleapis.com/system.network.dropped",
        "unit": "{packets}",
        "metricKind": "CUMULATIVE",
        "description": "The number of packets dropped. (Deprecated)"
      }
    },
    "insertId": "144vuve6kuw5",
    "resource": {
      "type": "audited_resource",
      "labels": {
        "project_id": "npt-monitoring",
        "method": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
        "service": "monitoring.googleapis.com"
      }
    },
    "timestamp": "2023-01-21T17:48:00.690924349Z",
    "severity": "NOTICE",
    "logName": "projects/npt-monitoring/logs/cloudaudit.googleapis.com%2Factivity",
    "receiveTimestamp": "2023-01-21T17:48:00.922789191Z"
  }

  {
    "protoPayload": {
      "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
      "authenticationInfo": {
        "principalEmail": "xxxxxx@gmail.com",
        "principalSubject": "user:xxxxxx@gmail.com"
      },
      "requestMetadata": {
        "callerIp": "...",
        "callerSuppliedUserAgent": "opentelemetry-collector-contrib 1.0.0 grpc-go/1.49.0,gzip(gfe)",
        "requestAttributes": {
          "time": "2023-01-21T17:48:00.727501108Z",
          "auth": {}
        },
        "destinationAttributes": {}
      },
      "serviceName": "monitoring.googleapis.com",
      "methodName": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
      "authorizationInfo": [
        {
          "resource": "122765205262",
          "permission": "monitoring.metricDescriptors.create",
          "granted": true,
          "resourceAttributes": {}
        }
      ],
      "resourceName": "projects/npt-monitoring",
      "request": {
        "name": "projects/npt-monitoring",
        "@type": "type.googleapis.com/google.monitoring.v3.CreateMetricDescriptorRequest",
        "metricDescriptor": {
          "name": "system.network.errors",
          "metricKind": "CUMULATIVE",
          "unit": "{errors}",
          "description": "The number of errors encountered. (Deprecated)",
          "displayName": "system.network.errors",
          "valueType": "INT64",
          "type": "workload.googleapis.com/system.network.errors"
        }
      },
      "response": {
        "type": "workload.googleapis.com/system.network.errors",
        "displayName": "system.network.errors",
        "metricKind": "CUMULATIVE",
        "name": "projects/npt-monitoring/metricDescriptors/workload.googleapis.com/system.network.errors",
        "description": "The number of errors encountered. (Deprecated)",
        "valueType": "INT64",
        "unit": "{errors}",
        "@type": "type.googleapis.com/google.api.MetricDescriptor"
      }
    },
    "insertId": "ivur3be6k8kj",
    "resource": {
      "type": "audited_resource",
      "labels": {
        "method": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
        "service": "monitoring.googleapis.com",
        "project_id": "npt-monitoring"
      }
    },
    "timestamp": "2023-01-21T17:48:00.722613595Z",
    "severity": "NOTICE",
    "logName": "projects/npt-monitoring/logs/cloudaudit.googleapis.com%2Factivity",
    "receiveTimestamp": "2023-01-21T17:48:01.416194098Z"
  }

  {
    "protoPayload": {
      "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
      "authenticationInfo": {
        "principalEmail": "xxxxxx@gmail.com",
        "principalSubject": "user:xxxxxx@gmail.com"
      },
      "requestMetadata": {
        "callerIp": "195.154.81.82",
        "callerSuppliedUserAgent": "opentelemetry-collector-contrib 1.0.0 grpc-go/1.49.0,gzip(gfe)",
        "requestAttributes": {
          "time": "2023-01-21T17:48:00.753492980Z",
          "auth": {}
        },
        "destinationAttributes": {}
      },
      "serviceName": "monitoring.googleapis.com",
      "methodName": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
      "authorizationInfo": [
        {
          "resource": "122765205262",
          "permission": "monitoring.metricDescriptors.create",
          "granted": true,
          "resourceAttributes": {}
        }
      ],
      "resourceName": "projects/npt-monitoring",
      "request": {
        "@type": "type.googleapis.com/google.monitoring.v3.CreateMetricDescriptorRequest",
        "metricDescriptor": {
          "metricKind": "CUMULATIVE",
          "name": "system.network.io",
          "displayName": "system.network.io",
          "type": "workload.googleapis.com/system.network.io",
          "valueType": "INT64",
          "unit": "By",
          "description": "The number of bytes transmitted and received. (Deprecated)"
        },
        "name": "projects/npt-monitoring"
      },
      "response": {
        "valueType": "INT64",
        "type": "workload.googleapis.com/system.network.io",
        "metricKind": "CUMULATIVE",
        "unit": "By",
        "name": "projects/npt-monitoring/metricDescriptors/workload.googleapis.com/system.network.io",
        "displayName": "system.network.io",
        "@type": "type.googleapis.com/google.api.MetricDescriptor",
        "description": "The number of bytes transmitted and received. (Deprecated)"
      }
    },
    "insertId": "14ipxlre6jzhv",
    "resource": {
      "type": "audited_resource",
      "labels": {
        "method": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
        "service": "monitoring.googleapis.com",
        "project_id": "npt-monitoring"
      }
    },
    "timestamp": "2023-01-21T17:48:00.748202499Z",
    "severity": "NOTICE",
    "logName": "projects/npt-monitoring/logs/cloudaudit.googleapis.com%2Factivity",
    "receiveTimestamp": "2023-01-21T17:48:01.426972031Z"
  }

  {
    "protoPayload": {
      "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
      "authenticationInfo": {
        "principalEmail": "xxxxxx@gmail.com",
        "principalSubject": "user:xxxxxx@gmail.com"
      },
      "requestMetadata": {
        "callerIp": "...",
        "callerSuppliedUserAgent": "opentelemetry-collector-contrib 1.0.0 grpc-go/1.49.0,gzip(gfe)",
        "requestAttributes": {
          "time": "2023-01-21T17:48:00.781372088Z",
          "auth": {}
        },
        "destinationAttributes": {}
      },
      "serviceName": "monitoring.googleapis.com",
      "methodName": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
      "authorizationInfo": [
        {
          "resource": "122765205262",
          "permission": "monitoring.metricDescriptors.create",
          "granted": true,
          "resourceAttributes": {}
        }
      ],
      "resourceName": "projects/npt-monitoring",
      "request": {
        "@type": "type.googleapis.com/google.monitoring.v3.CreateMetricDescriptorRequest",
        "metricDescriptor": {
          "description": "The number of packets transferred. (Deprecated)",
          "metricKind": "CUMULATIVE",
          "valueType": "INT64",
          "displayName": "system.network.packets",
          "type": "workload.googleapis.com/system.network.packets",
          "name": "system.network.packets",
          "unit": "{packets}"
        },
        "name": "projects/npt-monitoring"
      },
      "response": {
        "unit": "{packets}",
        "valueType": "INT64",
        "displayName": "system.network.packets",
        "name": "projects/npt-monitoring/metricDescriptors/workload.googleapis.com/system.network.packets",
        "metricKind": "CUMULATIVE",
        "@type": "type.googleapis.com/google.api.MetricDescriptor",
        "type": "workload.googleapis.com/system.network.packets",
        "description": "The number of packets transferred. (Deprecated)"
      }
    },
    "insertId": "1xd77x5e6jpgq",
    "resource": {
      "type": "audited_resource",
      "labels": {
        "project_id": "npt-monitoring",
        "service": "monitoring.googleapis.com",
        "method": "google.monitoring.v3.MetricService.CreateMetricDescriptor"
      }
    },
    "timestamp": "2023-01-21T17:48:00.776791231Z",
    "severity": "NOTICE",
    "logName": "projects/npt-monitoring/logs/cloudaudit.googleapis.com%2Factivity",
    "receiveTimestamp": "2023-01-21T17:48:01.721272008Z"
  }

  {
    "protoPayload": {
      "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
      "authenticationInfo": {
        "principalEmail": "xxxxxx@gmail.com",
        "principalSubject": "user:xxxxxx@gmail.com"
      },
      "requestMetadata": {
        "callerIp": "....",
        "callerSuppliedUserAgent": "opentelemetry-collector-contrib 1.0.0 grpc-go/1.49.0,gzip(gfe)",
        "requestAttributes": {
          "time": "2023-01-21T17:48:00.829648478Z",
          "auth": {}
        },
        "destinationAttributes": {}
      },
      "serviceName": "monitoring.googleapis.com",
      "methodName": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
      "authorizationInfo": [
        {
          "resource": "122765205262",
          "permission": "monitoring.metricDescriptors.create",
          "granted": true,
          "resourceAttributes": {}
        }
      ],
      "resourceName": "projects/npt-monitoring",
      "request": {
        "name": "projects/npt-monitoring",
        "@type": "type.googleapis.com/google.monitoring.v3.CreateMetricDescriptorRequest",
        "metricDescriptor": {
          "valueType": "DOUBLE",
          "type": "workload.googleapis.com/system.cpu.load_average.15m",
          "unit": "1",
          "description": "Average CPU Load over 15 minutes.",
          "displayName": "system.cpu.load_average.15m",
          "name": "system.cpu.load_average.15m",
          "metricKind": "GAUGE"
        }
      },
      "response": {
        "displayName": "system.cpu.load_average.15m",
        "metricKind": "GAUGE",
        "@type": "type.googleapis.com/google.api.MetricDescriptor",
        "unit": "1",
        "valueType": "DOUBLE",
        "description": "Average CPU Load over 15 minutes.",
        "name": "projects/npt-monitoring/metricDescriptors/workload.googleapis.com/system.cpu.load_average.15m",
        "type": "workload.googleapis.com/system.cpu.load_average.15m"
      }
    },
    "insertId": "13yn1ree6iyag",
    "resource": {
      "type": "audited_resource",
      "labels": {
        "service": "monitoring.googleapis.com",
        "project_id": "npt-monitoring",
        "method": "google.monitoring.v3.MetricService.CreateMetricDescriptor"
      }
    },
    "timestamp": "2023-01-21T17:48:00.825146839Z",
    "severity": "NOTICE",
    "logName": "projects/npt-monitoring/logs/cloudaudit.googleapis.com%2Factivity",
    "receiveTimestamp": "2023-01-21T17:48:00.979356547Z"
  }

  {
    "protoPayload": {
      "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
      "authenticationInfo": {
        "principalEmail": "xxxxxx@gmail.com",
        "principalSubject": "user:xxxxxx@gmail.com"
      },
      "requestMetadata": {
        "callerIp": "....",
        "callerSuppliedUserAgent": "opentelemetry-collector-contrib 1.0.0 grpc-go/1.49.0,gzip(gfe)",
        "requestAttributes": {
          "time": "2023-01-21T17:48:00.855064040Z",
          "auth": {}
        },
        "destinationAttributes": {}
      },
      "serviceName": "monitoring.googleapis.com",
      "methodName": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
      "authorizationInfo": [
        {
          "resource": "122765205262",
          "permission": "monitoring.metricDescriptors.create",
          "granted": true,
          "resourceAttributes": {}
        }
      ],
      "resourceName": "projects/npt-monitoring",
      "request": {
        "metricDescriptor": {
          "displayName": "system.cpu.load_average.1m",
          "description": "Average CPU Load over 1 minute.",
          "metricKind": "GAUGE",
          "unit": "1",
          "valueType": "DOUBLE",
          "name": "system.cpu.load_average.1m",
          "type": "workload.googleapis.com/system.cpu.load_average.1m"
        },
        "name": "projects/npt-monitoring",
        "@type": "type.googleapis.com/google.monitoring.v3.CreateMetricDescriptorRequest"
      },
      "response": {
        "displayName": "system.cpu.load_average.1m",
        "unit": "1",
        "type": "workload.googleapis.com/system.cpu.load_average.1m",
        "@type": "type.googleapis.com/google.api.MetricDescriptor",
        "valueType": "DOUBLE",
        "name": "projects/npt-monitoring/metricDescriptors/workload.googleapis.com/system.cpu.load_average.1m",
        "metricKind": "GAUGE",
        "description": "Average CPU Load over 1 minute."
      }
    },
    "insertId": "1i4bdige6jqtw",
    "resource": {
      "type": "audited_resource",
      "labels": {
        "service": "monitoring.googleapis.com",
        "project_id": "npt-monitoring",
        "method": "google.monitoring.v3.MetricService.CreateMetricDescriptor"
      }
    },
    "timestamp": "2023-01-21T17:48:00.851419659Z",
    "severity": "NOTICE",
    "logName": "projects/npt-monitoring/logs/cloudaudit.googleapis.com%2Factivity",
    "receiveTimestamp": "2023-01-21T17:48:00.998095021Z"
  }

  {
    "protoPayload": {
      "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
      "authenticationInfo": {
        "principalEmail": "xxxxxx@gmail.com",
        "principalSubject": "user:xxxxxx@gmail.com"
      },
      "requestMetadata": {
        "callerIp": "....",
        "callerSuppliedUserAgent": "opentelemetry-collector-contrib 1.0.0 grpc-go/1.49.0,gzip(gfe)",
        "requestAttributes": {
          "time": "2023-01-21T17:48:00.885628370Z",
          "auth": {}
        },
        "destinationAttributes": {}
      },
      "serviceName": "monitoring.googleapis.com",
      "methodName": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
      "authorizationInfo": [
        {
          "resource": "122765205262",
          "permission": "monitoring.metricDescriptors.create",
          "granted": true,
          "resourceAttributes": {}
        }
      ],
      "resourceName": "projects/npt-monitoring",
      "request": {
        "name": "projects/npt-monitoring",
        "metricDescriptor": {
          "valueType": "DOUBLE",
          "type": "workload.googleapis.com/system.cpu.load_average.5m",
          "displayName": "system.cpu.load_average.5m",
          "metricKind": "GAUGE",
          "name": "system.cpu.load_average.5m",
          "unit": "1",
          "description": "Average CPU Load over 5 minutes."
        },
        "@type": "type.googleapis.com/google.monitoring.v3.CreateMetricDescriptorRequest"
      },
      "response": {
        "description": "Average CPU Load over 5 minutes.",
        "valueType": "DOUBLE",
        "type": "workload.googleapis.com/system.cpu.load_average.5m",
        "@type": "type.googleapis.com/google.api.MetricDescriptor",
        "unit": "1",
        "name": "projects/npt-monitoring/metricDescriptors/workload.googleapis.com/system.cpu.load_average.5m",
        "displayName": "system.cpu.load_average.5m",
        "metricKind": "GAUGE"
      }
    },
    "insertId": "fjz4jue6ko7o",
    "resource": {
      "type": "audited_resource",
      "labels": {
        "project_id": "npt-monitoring",
        "service": "monitoring.googleapis.com",
        "method": "google.monitoring.v3.MetricService.CreateMetricDescriptor"
      }
    },
    "timestamp": "2023-01-21T17:48:00.880967778Z",
    "severity": "NOTICE",
    "logName": "projects/npt-monitoring/logs/cloudaudit.googleapis.com%2Factivity",
    "receiveTimestamp": "2023-01-21T17:48:01.774187200Z"
  }

  {
    "protoPayload": {
      "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
      "authenticationInfo": {
        "principalEmail": "xxxxxx@gmail.com",
        "principalSubject": "user:xxxxxx@gmail.com"
      },
      "requestMetadata": {
        "callerIp": "...",
        "callerSuppliedUserAgent": "opentelemetry-collector-contrib 1.0.0 grpc-go/1.49.0,gzip(gfe)",
        "requestAttributes": {
          "time": "2023-01-21T17:48:00.911267811Z",
          "auth": {}
        },
        "destinationAttributes": {}
      },
      "serviceName": "monitoring.googleapis.com",
      "methodName": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
      "authorizationInfo": [
        {
          "resource": "122765205262",
          "permission": "monitoring.metricDescriptors.create",
          "granted": true,
          "resourceAttributes": {}
        }
      ],
      "resourceName": "projects/npt-monitoring",
      "request": {
        "metricDescriptor": {
          "name": "system.memory.usage",
          "valueType": "INT64",
          "description": "Bytes of memory in use.",
          "displayName": "system.memory.usage",
          "type": "workload.googleapis.com/system.memory.usage",
          "unit": "By",
          "metricKind": "GAUGE"
        },
        "name": "projects/npt-monitoring",
        "@type": "type.googleapis.com/google.monitoring.v3.CreateMetricDescriptorRequest"
      },
      "response": {
        "unit": "By",
        "metricKind": "GAUGE",
        "type": "workload.googleapis.com/system.memory.usage",
        "description": "Bytes of memory in use.",
        "@type": "type.googleapis.com/google.api.MetricDescriptor",
        "displayName": "system.memory.usage",
        "name": "projects/npt-monitoring/metricDescriptors/workload.googleapis.com/system.memory.usage",
        "valueType": "INT64"
      }
    },
    "insertId": "1wt9iwhe6jrxz",
    "resource": {
      "type": "audited_resource",
      "labels": {
        "method": "google.monitoring.v3.MetricService.CreateMetricDescriptor",
        "service": "monitoring.googleapis.com",
        "project_id": "npt-monitoring"
      }
    },
    "timestamp": "2023-01-21T17:48:00.906435969Z",
    "severity": "NOTICE",
    "logName": "projects/npt-monitoring/logs/cloudaudit.googleapis.com%2Factivity",
    "receiveTimestamp": "2023-01-21T17:48:01.741183778Z"
  }

```

### Additional context

I'm using 0.61.0 because this is the most recent version that compiles with googlecloudexporter
I don't know for sure if the problem is coming from  the hostmetricsreceiver or the googlecloudexporter

**Comment by dashpole** [comment] 2023-01-23 14:43
@ljulliar this is expected behavior.   The googlecloud exporter for metrics sends to google cloud monitoring, not google cloud logging, in-case that was the source of the confusion.  More details below.

When the googlecloud exporter wants to write a metric, it has to make two calls: CreateMetricDescriptor and CreateTimeSeries.  CreateMetricDescriptor defines the "descriptor", or metadata of the metric.  It includes things like description, units, and display name.  CreateTimeSeries contains the actual metric information, like the value of the points, and metric labels.

CreateMetricDescriptor is only called once for each metric because we don't expect the unit, or description to change throughout the life of a metric. CreateTimeSeries is called whenever we have new data to send.

The above are audit logs for the `CreateMetricDescriptor` request.  That log is written by the cloud monitoring API, not by the collector.  Because of the high volume of `CreateTimeSeries` requests (I assume), there are no audit logs for `CreateTimeSeries`.  You should be able to verify in cloud monitoring's metric explorer that your metrics are successfully being delivered continuously.

You can also check which calls are being made to the monitoring API following https://cloud.google.com/apis/docs/monitoring.

I'm going to close this for now, but feel free to reopen if you have more questions.

**Comment by ljulliar** [comment] 2023-01-24 13:57
@dashpole indeed that was the problem. While reading the documentation I didn't see that in the Configuration reference it says "metric (optional): Configuration for sending metrics to Cloud Monitoring".
May I suggest that the explanation you gave in this ticket be placed in the main documentation page because it is not obvious at first that there is split between Cloud Monitoring and Cloud Logging.

Thank you for your help.

**Comment by dashpole** [comment] 2023-01-24 15:52
I should be clearer:

The googlecloud exporter supports sending metrics to cloud monitoring, logs to cloud logging, and traces to cloud trace.

To determine which you send telemetry to, you use it in a different pipeline.  You used a "metrics" pipeline, so you used the metric exporter, which sends to cloud monitoring.  If you used the "logs" pipeline, it would have sent to cloud logging, but wouldn't work with the hostmetrics receiver.

**Comment by dashpole** [comment] 2023-01-24 15:52
I'll update the readme

**Closed** 2023-01-24 17:32 UTC
Labels: bug, receiver/hostmetrics, exporter/googlecloud, needs triage
