### ISSUE TITLE
Spec file and SRC RPM availability 

### ISSUE THREAD

**Issue by BHiltonOfInterop** [open-telemetry/opentelemetry-collector-contrib#27637] opened 2023-10-11 20:47 UTC
### Is your feature request related to a problem? Please describe.

The RPM installation instructions provided are good enough for development and testing. However, many organizations, including ours, have a standard practice of hosting third-party RPMs locally via our own repository systems. This practice facilitates version control throughout the organization and ensures clients install the correct version.

We utilize the Koji/pungi repository system, which, unfortunately, is incompatible with the current naming convention of your RPM, resulting in importation issues. 

I attempted to adapt those AWS items for the current version of OpenTelemetry, but the disparate directory layouts and file differences complicated the process. We would greatly appreciate it if OpenTelemetry could incorporate a spec file and create_rpm script to make the integration with repository systems like Koji/pungi seamless.

### Describe the solution you'd like

I noticed that the AWS-branched version of the collector provides a spec file and create_rpm script. A similar feature from OpenTelemetry would be highly beneficial. This would allow anyone using the rpm solution to make naming or version changes as required.

### Describe alternatives you've considered

For now, we will likely pull the rpm directly while attempting to create the script and spec requested.

**Comment by crobert-1** [comment] 2023-10-31 18:12
Hello @BHiltonOfInterop, sorry for the delayed response. Would you be able to provide more of a description for your workflow of how you go about downloading and using the supplied RPM? I just want to make sure I understand the scenario here. 

Out of ignorance, if the issue is **only** the name of the rpm file, is there a reason it can't simply be renamed between downloading and uploading?

_Adding a link to the `create_rpm` [script for future reference.](https://github.com/aws-observability/aws-otel-collector/blob/main/tools/packaging/linux/create_rpm.sh)_

**Comment by crobert-1** [comment] 2023-12-18 16:39
@BHiltonOfInterop I'm going to close the issue for now, but please feel free to give more information when possible. Also, I believe the [collector releases repository](https://github.com/open-telemetry/opentelemetry-collector-releases) would be better suited for this issue going forward.

**Closed by crobert-1** 2023-12-18 16:39 UTC
Labels: enhancement, waiting for author, packaging, needs triage
