### ISSUE TITLE
Add Timezone Info in Docker Image

### ISSUE THREAD

**Issue by joker-star-l** [open-telemetry/opentelemetry-collector-contrib#35901] opened 2024-10-21 18:07 UTC
### Component(s)

exporter/doris

### Describe the issue you're reporting

The doris exporter needs timezone info to handle different timezone. But it is not in the current docker image. Can I add this to the dockerfile?

![docker](https://github.com/user-attachments/assets/0881f7a5-8c8b-4ad8-b791-cde8bcd319a4)

**Comment by mx-psi** [comment] 2024-10-22 16:10
Duplicate of open-telemetry/opentelemetry-collector/issues/9991, if you file a PR on opentelemetry-collector-releases modifying this https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/Dockerfile and the rest of the Dockerfiles I think we can reopen the discussion

**Comment by joker-star-l** [comment] 2024-10-23 06:32
> Duplicate of [open-telemetry/opentelemetry-collector/issues/9991](https://github.com/open-telemetry/opentelemetry-collector/issues/9991), if you file a PR on opentelemetry-collector-releases modifying this https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/Dockerfile and the rest of the Dockerfiles I think we can reopen the discussion

Thank you!. I have read the issues you mentioned. As these said, tzdata changes frequently, maybe I can solve this problem by specifying in the doris exporter documentation that the host tzdata should be mounted when using docker.

**Comment by mx-psi** [comment] 2024-10-23 08:05
I am personally not against having a copy on the Docker image and allowing the user to override it in case it is outdated

**Comment by mx-psi** [comment] 2024-11-12 21:17
I am going to close this as a duplicate of open-telemetry/opentelemetry-collector/issues/9991, let's continue the conversation there!

**Closed by mx-psi** 2024-11-12 21:17 UTC
