### ISSUE TITLE
[azuremonitorexporter] Seems to not respect semantic convention on http field for mapping

### ISSUE THREAD

**Issue by aygalinc** [open-telemetry/opentelemetry-collector-contrib#31255] opened 2024-02-14 13:20 UTC
### Component(s)

exporter/azuremonitor

### What happened?

Hello ! 
When I read the documentation about azuremonitor, it states that to compute response code for appInsight it took http.response_status or status_code. 
Or Latest Semantic convention says that field that contains http status is http.response.status_code should be used so the mapping is really weird in our system. 

### Collector version

latest

**Comment by JorTurFer** [comment] 2024-02-15 09:18
We are affected too by this

**Comment by aygalinc** [comment] 2024-02-15 13:21
@pcwiese : 
Maybe i 'm wrong because i clearly have no experience in Go, i just download vscode for this and browse project and dependencies but for me it seems that the library that is genrated upon the semantic convention specification is not aligned with the latest version of the spec: https://pkg.go.dev/go.opentelemetry.io/collector/semconv@v0.94.1/v1.6.1 . 
 
 It clearly not integrate all breaking change on http introduce in version 1.21.0 dure to alignement with ECS naming.

**Comment by aygalinc** [comment] 2024-02-15 13:21
Seems the same for all other exporter if they rely on the same package no ?

**Comment by JorTurFer** [comment] 2024-02-15 13:24
The problem is that v1.21 doesn't contain the new value either:  https://pkg.go.dev/go.opentelemetry.io/collector/semconv@v0.94.1/v1.21.0 despite it's documented in the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/schemas/1.21.0

**Comment by aygalinc** [comment] 2024-02-15 13:37
Yep i check all the version and for me the code generation seems broken. But as i said i m not a go expert so i do not know if i look the right set of package module.
And i m also surprised that the module end at version 1.22.0 because they have release 2 news versions of the semantic spec

**Comment by joegoldman2** [comment] 2024-02-27 23:01
Duplicate of #29687?

**Comment by aygalinc** [comment] 2024-02-28 09:37
Yep the root casue is the same

**Comment by crobert-1** [comment] 2024-02-28 22:44
I'm going to close in favor of #29687, but let me know if this should remain open.

**Closed by crobert-1** 2024-02-28 22:44 UTC
Labels: bug, exporter/azuremonitor, needs triage
