### ISSUE TITLE
Data dog open telemetry exporter not sending traces and logs to data dog

### ISSUE THREAD

**Issue by muneernet** [open-telemetry/opentelemetry-collector-contrib#3524] opened 2021-05-25 16:54 UTC
Hi Team,

I Have used the attached configuration 
[config.yaml.txt](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/6540993/config.yaml.txt)
  Am using a console application and adding the instrumentation 

Program.cs
========
using log4net;
using log4net.Config;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Datadog.Trace;
namespace SampleDataDog
{

    class Program
    {
        public static ILog logger = LogManager.GetLogger(typeof(Program));
        private static TraceSource _source = new TraceSource("TraceLog");
        static void Main(string[] args)
        {

            Console.WriteLine("Trace and Logging Started...!");
            XmlConfigurator.Configure();
            using (var scope =
                  Tracer.Instance.StartActive("Tracing.Start"))
            {
                try
                {
                    LogicalThreadContext.Properties["dd.trace_id"] = CorrelationIdentifier.TraceId.ToString();
                    scope.Span.SetTag("userId", "muneer");
                    scope.Span.SetTag("trace_id", scope.Span.TraceId.ToString());
                    logger.Debug("Date +"+DateTime.Now.ToString()+ "TraceId " + scope.Span.TraceId.ToString() + " New Logging message from console..!");
                    int a = 1;
                    int c = a / 0;
                }
                catch (Exception ex)
                {
                    logger.Error("Exception Occured : " + ex.Message + " and the trace Id is " + scope.Span.TraceId.ToString() + " for user "
                        + scope.Span.GetTag("userId").ToString());
                    scope.Span.SetException(ex);
                    scope.Span.SetTag("error.msg", ex.Message);
                    scope.Span.SetTag("error.stack", ex.ToString());
                    scope.Span.SetTag("error.type", ex.GetType().ToString());
                }
                finally
                {
                    LogicalThreadContext.Properties.Remove("dd.trace_id");
                }
            }
            Console.WriteLine("Press any key to stop Tracing and Logging...!");
            Console.ReadLine();
            Console.WriteLine("Program is shutting down...!");
        }
    }
}

And config file 
==========

<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<configSections>
		<section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net" />
	</configSections>
	<log4net>
		<root>
			<level value="DEBUG" />
			<appender-ref ref="JsonFileAppender" />
		</root>
		<appender name="JsonFileAppender" type="log4net.Appender.FileAppender">
			<threshold value="DEBUG" />
			<file value="application-logs.json" />
			<appendToFile value="true" />
			<layout type="log4net.Layout.SerializedLayout, log4net.Ext.Json">
				<conversionPattern value="%date{yyyy-MM-dd HH:mm:ss.SSS} %level [%thread] %logger %method:%line - %message%n" />
				<decorator type="log4net.Layout.Decorators.StandardTypesDecorator, log4net.Ext.Json" />
				<default />
				
				<remove value="ndc" />
				<remove value="message" />
				
				<member value="message:messageobject" />
				<member value="properties" />
				
			</layout>
		</appender>
	</log4net>

	
	<system.diagnostics>
		<sources>
			<source name="TraceLog" switchValue="All">
				<listeners>
					<add name="configConsoleListener" type="System.Diagnostics.SourceSwitch" />
				</listeners>
			</source>
		</sources>
	</system.diagnostics>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="log4net" publicKeyToken="669e0ddf0bb1aa2a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.12.0" newVersion="2.0.12.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

Tried all the values but am not able to see logs or traces on the data dog back end .

**Comment by mx-psi** [comment] 2021-05-26 07:23
@ericmustin since this is related to traces can you take a look?

**Comment by ericmustin** [comment] 2021-05-28 16:09
Hello, this appears to be a duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3656#issuecomment-849574898 but my comments on there apply here. can we close this?

**Closed** 2021-05-29 11:50 UTC
Labels: bug
