### ISSUE TITLE
Data race in groupbytraceprocessor

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#3184] opened 2021-04-20 20:55 UTC
```
==================
WARNING: DATA RACE
Read at 0x00c000420780 by goroutine 48:
  runtime.mapaccess2()
      /usr/local/go/src/runtime/map.go:452 +0x0
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*ringBuffer).contains()
      /home/circleci/project/processor/groupbytraceprocessor/ring_buffer.go:56 +0x132
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*groupByTraceProcessor).processBatch()
      /home/circleci/project/processor/groupbytraceprocessor/processor.go:126 +0x89
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*groupByTraceProcessor).processResourceSpans()
      /home/circleci/project/processor/groupbytraceprocessor/processor.go:117 +0x104
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.TestTracesAreDispatchedInIndividualBatches()
      /home/circleci/project/processor/groupbytraceprocessor/processor_test.go:476 +0x80d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202

Previous write at 0x00c000420780 by goroutine 57:
  runtime.mapdelete()
      /usr/local/go/src/runtime/map.go:685 +0x0
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*ringBuffer).delete()
      /home/circleci/project/processor/groupbytraceprocessor/ring_buffer.go:66 +0x150
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*groupByTraceProcessor).onTraceExpired()
      /home/circleci/project/processor/groupbytraceprocessor/processor.go:187 +0x324
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*groupByTraceProcessor).onTraceExpired-fm()
      /home/circleci/project/processor/groupbytraceprocessor/processor.go:172 +0x55
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*eventMachine).handleEvent.func2()
      /home/circleci/project/processor/groupbytraceprocessor/event.go:151 +0x8f
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.doWithTimeout.func1()
      /home/circleci/project/processor/groupbytraceprocessor/event.go:269 +0x4e

Goroutine 48 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1168 +0x5bb
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1439 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1437 +0x612
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1345 +0x3b3
  main.main()
      _testmain.go:179 +0x356

Goroutine 57 (finished) created at:
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.doWithTimeout()
      /home/circleci/project/processor/groupbytraceprocessor/event.go:268 +0xa4
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*eventMachine).handleEventWithObservability()
      /home/circleci/project/processor/groupbytraceprocessor/event.go:248 +0x9e
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*eventMachine).handleEvent()
      /home/circleci/project/processor/groupbytraceprocessor/event.go:150 +0x404
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*eventMachine).start()
      /home/circleci/project/processor/groupbytraceprocessor/event.go:111 +0xc4
==================
==================
WARNING: DATA RACE
Write at 0x00c000170228 by goroutine 48:
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*ringBuffer).put()
      /home/circleci/project/processor/groupbytraceprocessor/ring_buffer.go:50 +0x2e4
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*groupByTraceProcessor).processBatch()
      /home/circleci/project/processor/groupbytraceprocessor/processor.go:140 +0x35c
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*groupByTraceProcessor).processResourceSpans()
      /home/circleci/project/processor/groupbytraceprocessor/processor.go:117 +0x104
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.TestTracesAreDispatchedInIndividualBatches()
      /home/circleci/project/processor/groupbytraceprocessor/processor_test.go:476 +0x80d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202

Previous read at 0x00c000170228 by goroutine 57:
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*ringBuffer).delete()
      /home/circleci/project/processor/groupbytraceprocessor/ring_buffer.go:61 +0xd2
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*groupByTraceProcessor).onTraceExpired()
      /home/circleci/project/processor/groupbytraceprocessor/processor.go:187 +0x324
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*groupByTraceProcessor).onTraceExpired-fm()
      /home/circleci/project/processor/groupbytraceprocessor/processor.go:172 +0x55
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*eventMachine).handleEvent.func2()
      /home/circleci/project/processor/groupbytraceprocessor/event.go:151 +0x8f
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.doWithTimeout.func1()
      /home/circleci/project/processor/groupbytraceprocessor/event.go:269 +0x4e

Goroutine 48 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1168 +0x5bb
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1439 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1437 +0x612
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1345 +0x3b3
  main.main()
      _testmain.go:179 +0x356

Goroutine 57 (finished) created at:
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.doWithTimeout()
      /home/circleci/project/processor/groupbytraceprocessor/event.go:268 +0xa4
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*eventMachine).handleEventWithObservability()
      /home/circleci/project/processor/groupbytraceprocessor/event.go:248 +0x9e
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*eventMachine).handleEvent()
      /home/circleci/project/processor/groupbytraceprocessor/event.go:150 +0x404
  github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*eventMachine).start()
      /home/circleci/project/processor/groupbytraceprocessor/event.go:111 +0xc4
==================
2021-04-20T20:42:43.193Z	DEBUG	groupbytraceprocessor/processor.go:254	creating trace at the storage	{"traceID": "02030405000000000000000000000000"}
2021-04-20T20:42:43.193Z	DEBUG	groupbytraceprocessor/processor.go:159	scheduled to release trace	{"duration": "1ns"}
2021-04-20T20:42:43.193Z	DEBUG	groupbytraceprocessor/processor.go:173	processing expired	{"traceID": "02030405000000000000000000000000"}
2021-04-20T20:42:43.193Z	DEBUG	groupbytraceprocessor/processor.go:190	marking the trace as released	{"traceID": "02030405000000000000000000000000"}
2021-04-20T20:42:43.194Z	DEBUG	groupbytraceprocessor/event.go:258	event finished	{"event": "onTraceExpired"}
2021-04-20T20:42:43.194Z	DEBUG	groupbytraceprocessor/processor.go:209	trace marked as released	{"traceID": "02030405000000000000000000000000"}
2021-04-20T20:42:43.194Z	DEBUG	groupbytraceprocessor/event.go:258	event finished	{"event": "onTraceReleased"}
2021-04-20T20:42:43.194Z	INFO	groupbytraceprocessor/event.go:207	shutting down the event manager	{"pending-events": 0}
2021-04-20T20:42:43.194Z	DEBUG	groupbytraceprocessor/event.go:258	event finished	{"event": "onTraceRemoved"}
--- FAIL: TestTracesAreDispatchedInIndividualBatches (0.01s)
    testing.go:1038: race detected during execution of test
2021-04-20T20:42:43.196Z	DEBUG	groupbytraceprocessor/processor.go:254	creating trace at the storage	{"traceID": "01020304000000000000000000000000"}
2021-04-20T20:42:43.196Z	WARN	groupbytraceprocessor/processor.go:118	failed to process batch	{"error": "couldn't add spans to new trace: some unexpected error", "traceID": "01020304000000000000000000000000"}
github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*groupByTraceProcessor).processResourceSpans
	/home/circleci/project/processor/groupbytraceprocessor/processor.go:118
github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.TestErrorOnProcessResourceSpansContinuesProcessing
	/home/circleci/project/processor/groupbytraceprocessor/processor_test.go:612
testing.tRunner
	/usr/local/go/src/testing/testing.go:1123
FAIL
coverage: 98.1% of statements
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor	0.435s
FAIL
make[2]: *** [../../Makefile.Common:48: do-unit-tests-with-cover] Error 1
make[2]: Leaving directory '/home/circleci/project/processor/groupbytraceprocessor'
make[1]: *** [Makefile:82: for-all] Error 2
make[1]: Leaving directory '/home/circleci/project'
make: *** [Makefile:48: unit-tests-with-cover] Error 2```

**Comment by jpkrohling** [comment] 2021-07-13 09:46
Closing, as this seems to be fixed already. I don't remember seeing a CI failure for a long time, and I couldn't reproduce it locally:

```
$ go test -race -count 1000 .
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor	470.193s
```

**Closed by jpkrohling** 2021-07-13 09:46 UTC
Labels: bug
