### ISSUE TITLE
spanmetricsprocessor doesn't prune histograms when metric cache is pruned

### ISSUE THREAD

**Issue by nijave** [open-telemetry/opentelemetry-collector-contrib#27080] opened 2023-09-22 17:50 UTC
### Component(s)

processor/spanmetrics

## Description
span metrics processor doesn't drop old histograms
Graphs in https://github.com/grafana/agent/issues/5271

## Steps to Reproduce
leave the collector running a while, watch exported metric count drop indefinitely

## Expected Result
metric series should be pruned if they haven't been updated a while

## Actual Result
metric series dimension cache is pruned but histograms are not
 

### Collector version

v0.80.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
Configured is automatically generated by Grafana Agent. See https://github.com/grafana/agent/blob/main/pkg/traces/config.go#L647
```

### Log output

```shell
N/A
```

### Additional context

It looks like `histograms` map should have been pruned/LRU'd in addition to `metricsKeyToDimensions` https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2179

I think this is the same/similar but it's closed so I figured I'd collect everything into a bug report https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17306#issuecomment-1731714770

**Comment by nijave** [comment] 2023-09-23 01:13
Took a crack at a PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27083

**Comment by mfilipe** [comment] 2023-09-25 20:55
Hello @nijave, I can confirm the issue in my environment:

<img width="1012" alt="Screenshot 2023-09-25 at 17 48 46" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/8762/5abd4601-a921-46d9-af40-c4a8bb005431">


How you can see, the metrics exposed in `/metrics` only grow over the time. 

There are two details about your issue that doesn't match with the environment that I have: [spanmetricsconnector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector) and [v0.85.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.85.0). Could you consider using those on your work? `spanmetricsprocessor` is deprecated.

**Comment by mfilipe** [comment] 2023-09-25 21:08
My current config:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    metric_expiration: 60s
connectors:
  spanmetrics:
    histogram:
      unit: "ms"
      explicit:
        buckets: []
    metrics_flush_interval: 15s
    dimensions:
      - name: build_name
      - name: build_number
    exclude_dimensions:
      - span.kind
    dimensions_cache_size: 100
processors:
  batch:
  attributes/spanmetrics:
    actions:
      - action: extract
        key: host.name
        pattern: ^(?P<kubernetes_cluster>.+)-jenkins-(?P<organization>tantofaz|whatever-org)-(?P<build_name>.+)-(?P<build_number>[0-9]+)(?P<build_id>(?:-[^-]+){2}|--.*?)$
  filter/spanmetrics:
    error_mode: ignore
    metrics:
      metric:
        - 'resource.attributes["service.name"] != "jenkins"'
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes/spanmetrics, batch]
      exporters: [spanmetrics]
    metrics:
      receivers: [spanmetrics]
      processors: [filter/spanmetrics]
      exporters: [prometheus]
```

**Comment by mfilipe** [comment] 2023-09-29 14:02
This issue should be considerable **critical**, once `/metrics` grows in a way that makes the metric backend be unstable with the time to scrape the metrics. Basically, `/metrics` starts with a few kilobytes and, after a few days, it goes to hundreds of megabytes, making the backend unstable. The environment where I have the problem is common: `spanmetrics` connector saving the metrics in `Prometheus` with many repositories generating metrics. 

Based on [this article](https://grafana.com/blog/2023/09/26/opentelemetry-metrics-a-guide-to-delta-vs.-cumulative-temporality-trade-offs/#backend-considerations), Prometheus only supports cumulative metrics, so I cannot use delta metrics to avoid the issue.

If there is a workaround for the issue, please let me know, AFAIK the workaround doesn't exist, making this issue **critical**.

**Comment by crobert-1** [comment] 2023-10-12 18:53
@nijave From #27083 and your results shared [here](https://github.com/grafana/agent/issues/5271#issuecomment-1750639260), it looks like this has been fixed. Is that correct? If so we can close this issue.

**Closed** 2023-10-13 01:35 UTC
Labels: bug, priority:p1, processor/spanmetrics
