### ISSUE TITLE
[cmd/telemetrygen] Duration flag is not respected when tls handshake fails

### ISSUE THREAD

**Issue by AlexDCraig** [open-telemetry/opentelemetry-collector-contrib#31401] opened 2024-02-23 23:27 UTC
### Component(s)

cmd/telemetrygen

## Description

If you use the duration flag but point to an endpoint that will fail tls handshake failure, the command will run indefinitely and not respect the duration flag.

## Steps to Reproduce

````bash
telemetrygen metrics \
--otlp-endpoint [my-favorite-otel-endpoint]:443 \
--duration 5s
````

## Expected Result

The command exits in failure after 5s

## Actual Result

Command runs forever

### Collector version

v0.95.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment] 2024-02-28 19:15
I was able to reproduce using both logs and traces, but logs fails right away when it can't connect.

I believe this is because the GRPC connections for metrics and traces are [configured to block](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b10659afc4f55b3d6a15e2b873e4854e66477600/cmd/telemetrygen/internal/metrics/exporter.go#L22) until the connection is successful. The documentation for the `WithBlock` method explicitly states using this feature is not recommended. This functionality was added here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27007.

Since this is a tool used for testing, it may be best to simply fail when a connection cannot be made, rather than blocking until it's successful. Unless the code owners disagree, I think the `WithBlock` option can be removed.

**Comment by mx-psi** [comment] 2024-02-29 12:50
@crobert-1 I think the option was already there before the PR you mention, it was just moved to the current file from a different place. I am fine removing `WithBlock` but would be good to dig where and why we added the option in the first place.

**Comment by crobert-1** [comment] 2024-02-29 16:47
Good catch @mx-psi, I missed that. It looks like [`WithBlock` was added in metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17898) some time ago, and was re-using a lot of the traces logic. [`WithBlock` was added to traces](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16358) as a part of moving to telemetrygen from tracegen. `WithBlock` was added to [tracegen with the initial commit](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/956), but I'm not seeing any comments related to why the option was originally added. 

It looks like tracegen was [brought over](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/955) from the same concept within Jaeger, but the Jaeger implementation only added GRPC exporting less than a year ago, and they don't use `WithBlock`, so it looks like this was original to the collector's tracegen functionality.

@jpkrohling Do you happen to remember why `WithBlock` was added for tracegen's grpc trace exporting functionality?

**Comment by jpkrohling** [comment] 2024-03-04 10:26
It's been a while... I don't remember the explicit reason, and I'd be fine removing as well.

**Comment by AlexDCraig** [comment] 2024-03-06 18:48
Thanks folks! I may put in a PR to remove that block if I free up. I use this tool for testing and added some logic to force quit the command if it hits x seconds which I'd like to remove and just rely on that duration flag

**Closed** 2024-03-08 00:02 UTC
Labels: bug, cmd/telemetrygen
