### ISSUE TITLE
Permission denied on mkdir /tmp

### ISSUE THREAD

**Issue by itsif** [open-telemetry/opentelemetry-collector-contrib#3702] opened 2021-06-04 09:52 UTC
**Steps to reproduce**
docker run --privileged -p 7276:7276 -p 8888:8888 -p 9943:9943 -p 55679:55679 -p 55680:55680 -p 9411:9411 -v $(pwd)/config.yaml:/etc/otel-contrib-collector/config.yaml --name logzio-collector otel/opentelemetry-collector-contrib:latest --config /etc/otel-contrib-collector/config.yaml

2021-06-04T09:29:49.778Z	info	service/application.go:277	Starting otelcontribcol...	{"Version": "v0.27.0", "NumCPU": 4}
2021-06-04T09:29:49.778Z	info	service/application.go:185	Setting up own telemetry...
2021-06-04T09:29:49.780Z	info	service/telemetry.go:98	Serving Prometheus metrics	{"address": ":8888", "level": 0, "service.instance.id": "8b7093cf-f4ef-4993-b139-fb5fabb18ebf"}
2021-06-04T09:29:49.780Z	info	service/application.go:220	Loading configuration...
2021-06-04T09:29:49.784Z	info	service/application.go:236	Applying configuration...
Error: cannot build pipelines: cannot build builtExporters: error creating logzio exporter: mkdir /tmp: permission denied
2021/06/04 09:29:49 application run finished with error: cannot build pipelines: cannot build builtExporters: error creating logzio exporter: mkdir /tmp: permission denied

Version: latest

receivers:
  opencensus:
  zipkin:
    endpoint: :9411
  jaeger:
    protocols:
      thrift_http:

exporters:
  logzio:
    account_token: "XXX"

processors:
  batch:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [opencensus, jaeger, zipkin]
      processors: [batch]
      exporters: [logzio]

**Environment**
OS: (mac os)

**Comment by yotamloe** [comment] 2021-06-08 12:50
Hey, @itsif we at logz.io are aware of this issue and working rapidly to solve it. In the meantime, you can use any other image with version <= 0.23. We are still investigating what is the root cause, the assumption is that it caused by changes in this [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2925/files).

**Comment by jkowall** [comment] 2022-05-27 09:44
Please close this out, we have fixed it a long time ago :)

**Closed** 2022-05-27 13:56 UTC
Labels: bug
