### ISSUE TITLE
googlecloudexporter not compiling above v0.61.0

### ISSUE THREAD

**Issue by ljulliar** [open-telemetry/opentelemetry-collector-contrib#17899] opened 2023-01-21 17:36 UTC
### Component(s)

exporter/googlecloud

## Description
googlecloudexporter will not compile with revision higher than 0.61.0

## Steps to Reproduce
Use the local build process from https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample/tree/main/build/local
Adjust version in Makefile and in builder-config.yaml. Up to 0.61.0 the compilation will work 

## Expected Result
The custom version of otelcol should compile

## Actual Result
If you use any version higher than 0.61.0 you'll always obtain the same error and the compilation will stop (see below)

### Collector version

0.63.0+

## Environment
OS: Debian 12
Compiler(if manually compiled):  go version go1.19.4 linux/amd64

### OpenTelemetry Collector configuration

```yaml
receivers:
  - import: go.opentelemetry.io/collector/receiver/otlpreceiver
    gomod: go.opentelemetry.io/collector v0.63.0
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.63.0

processors:
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.63.0
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor v0.63.0
  - import: go.opentelemetry.io/collector/processor/memorylimiterprocessor
    gomod: go.opentelemetry.io/collector v0.63.0
  - import: go.opentelemetry.io/collector/processor/batchprocessor
    gomod: go.opentelemetry.io/collector v0.63.0

exporters:
  - import: go.opentelemetry.io/collector/exporter/loggingexporter
    gomod: go.opentelemetry.io/collector v0.63.0
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter v0.63.0
```

### Log output

```shell
go: finding module for package go.opentelemetry.io/collector/config
go: finding module for package go.opentelemetry.io/collector/service/servicetest
go.opentelemetry.io/collector/cmd/builder imports
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter imports
	go.opentelemetry.io/collector/config: module go.opentelemetry.io/collector@latest found (v0.69.1), but does not contain package go.opentelemetry.io/collector/config
go.opentelemetry.io/collector/cmd/builder tested by
	go.opentelemetry.io/collector/cmd/builder.test imports
	go.opentelemetry.io/collector/config/configtest: module go.opentelemetry.io/collector@latest found (v0.69.1), but does not contain package go.opentelemetry.io/collector/config/configtest
go.opentelemetry.io/collector/cmd/builder imports
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter tested by
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter.test imports
	go.opentelemetry.io/collector/service/servicetest: module go.opentelemetry.io/collector@latest found (v0.69.1), but does not contain package go.opentelemetry.io/collector/service/servicetest
```
```


### Additional context

_No response_

**Comment by damemi** [comment] 2023-01-23 14:24
It looks like the configtest package was removed in v0.65.0 from the collector: https://github.com/open-telemetry/opentelemetry-collector/pull/6542

In this case, the collector builder seems to be trying to import from latest (v0.69.1) even though you have v0.63.0 specified, so that's the conflict. I'm not sure why that is, but I'll take a deeper look and try reproducing

**Comment by damemi** [comment] 2023-01-23 16:32
@ljulliar in your builder config, the loggingexporter import is wrong for v0.63.0. When I update to the following, it works:
```yaml
receivers:
  - import: go.opentelemetry.io/collector/receiver/otlpreceiver
    gomod: go.opentelemetry.io/collector v0.63.0
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.63.0

processors:
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.63.0
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor v0.63.0
  - import: go.opentelemetry.io/collector/processor/memorylimiterprocessor
    gomod: go.opentelemetry.io/collector v0.63.0
  - import: go.opentelemetry.io/collector/processor/batchprocessor
    gomod: go.opentelemetry.io/collector v0.63.0

exporters:
  - import: go.opentelemetry.io/collector/exporter/loggingexporter
    gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.63.0
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter v0.63.0
```

**Comment by jessberg** [comment] 2023-01-23 22:45
I'm having the same issue - why exactly does specifying the specific exporter help? It seems like they should be importing the same thing because it's the same version number.

**Comment by damemi** [comment] 2023-01-24 14:20
@jessberg around that version, the default upstream components started moving to their own Go modules (https://github.com/open-telemetry/opentelemetry-collector/issues/5992). In v0.63.0, only the logging exporter was affected out of the ones in this config. If you try to build a collector using the latest version, you would need to make a similar change for otlpreceiver, memorylimiterprocessor, and batchprocessor too.

I'll update our samples repo to reflect these changes in the latest versions, but otherwise I think we can close this issue.

**Comment by jessberg** [comment] 2023-01-24 15:30
Makes sense; thanks so much!

**Comment by damemi** [comment] 2023-01-26 14:54
@dashpole can you close this? Think we resolved it, thanks

**Closed** 2023-01-26 15:15 UTC
Labels: bug, exporter/googlecloud

**Comment by ljulliar** [comment] 2023-01-27 14:03
@dashpole 
I double checked on my side and it does work now.
However there is now a warning issued by the builder about deprecated arguments
```
$ make build
go install go.opentelemetry.io/collector/cmd/builder@v0.70.0
mkdir -p bin
builder --config=builder-config-izbk.yaml --name=otelcol-custom --output-path=bin/.
Flag --name has been deprecated, use config distribution::name
Flag --output-path has been deprecated, use config distribution::output_path
```
It can be fixed by removing the command line arguments in the Makefile and adding the following section in the builder-config.yaml
```
dist:
  name: otelcol-custom
  output_path: ./bin
```

**Comment by damemi** [comment] 2023-01-27 14:31
Thanks @ljulliar, we'll fix that in our scripts for the sample. For the future you can feel free to open issues directly in https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample for problems with the GCP examples
