### ISSUE TITLE
Dependabot builds fails on main

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#20869] opened 2023-04-12 07:35 UTC
### What happened?

https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/12682119904

```
Your .github/dependabot.yml contained invalid details
Dependabot encountered the following error when parsing your .github/dependabot.yml:

The property '#/updates' had more items than the allowed 200
Please update the config file to conform with Dependabot's specification.
```

### Collector version

latest

**Comment by mx-psi** [comment] 2023-04-12 10:47
This is a duplicate of #19410

**Closed by mx-psi** 2023-04-12 10:47 UTC
Labels: bug
