### ISSUE TITLE
[processor/transformprocessor] Unexpected behaviour when setting resource attributes

### ISSUE THREAD

**Issue by tarokkk** [open-telemetry/opentelemetry-collector-contrib#36360] opened 2024-11-13 21:18 UTC
### Component(s)

processor/transform

## Description
Only the last event record change will be persistent when modifying a `resource` attribute on a log record.

## Steps to Reproduce

Set up a file log receiver and use a transport processor in the pipeline like this:
```
      transform/example:
        log_statements:
          - conditions: null
            context: log
            statements:
              - set(resource.attributes["vhost"],attributes["example"])
```

The file log receiver "sometimes" emits the logs in "batches" with the same resource "header"

## Expected Result

```
log1 Resource{"vhost": "xxx"}, Log{"example": "xxx"}
log2 Resource{"vhost": "yyy"}, Log{"example": "yyy"}
```

## Actual Result

```
log1 Resource{"vhost": "yyy"}, Log{"example": "xxx"}
log2 Resource{"vhost": "yyy"}, Log{"example": "yyy"}
```

I assume that the setter does not clone the resource & scope part on modification which makes the individual log records to overwrite each resource context.

### Collector version

0.104.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by TylerHelmuth** [comment] 2024-11-13 21:42
This looks like a duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32080. Check if https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/transformprocessor/README.md#transformflattenlogs solves your issue. Please ping me if you think this is different.

**Closed by TylerHelmuth** 2024-11-13 21:42 UTC
Labels: bug, processor/transform, needs triage
