### ISSUE TITLE
Datadog exporter constantly producing error log

### ISSUE THREAD

**Issue by dustyhorizon** [open-telemetry/opentelemetry-collector-contrib#2353] opened 2021-02-15 06:19 UTC
**Describe the bug**
Datadog exporter is constantly complaining the the context has expired.

However, traces seem to appear on datadog just fine so I am not too sure what is the issue here.

**Steps to reproduce**
Use datadog exporter

**What did you expect to see?**
No errors.

**What did you see instead?**
```
otel_collector_1                    | 2021-02-15T06:15:32.480Z  info    datadogexporter/traces_exporter.go:162  failed to send traces   {"component_kind": "exporter", "component_type": "datadog", "component_name": "datadog", "error": "failed to send trace payload to trace edge: Post \"https://trace.agent.datadoghq.com/api/v0.2/traces\": context deadline exceeded"}
```

**What version did you use?**
Version: `v.0.20.0`

**Comment by ericmustin** [comment] 2021-02-16 07:04
@dustyhorizon 👋 hey there. that's no good. We've seen a few reports of this so would love to get more info here and resolve for you. Since i'm likely going to need you to add the `logging` exporter to your traces pipeline and set `logLevel` to debug, it's possible that information could include some PII, so would it be possible to gather those logs and include it when opening a support ticket with support@datadoghq.com, referencing this issue (and please feel free to mention that I asked you to do so, hi again btw hope all is well!). We will make sure to update this issue with findings from the investigation so anyone else in the community can be made aware.

additionally on the above support ticket, if possible, could you detail how you are deploying the collector in your environment and the circumstances in which the error msg first occurred. for ex, if k8s, as Daemonset or as both Daemonset and standalone service? Additionally if you have a copy of your manifest (if using k8s) and collector config yaml that would be helpful so we can attempt to reproduce on our end.

Please feel free to reach out on slack or gitter as well, i am based in EST

**Comment by ericmustin** [comment] 2021-02-22 14:09
@dustyhorizon 👋 Hey there just following up, hope all is well. Were you able to create a support ticket or review the questions I had above? If you did make a ticket, just let me know the id, i can make sure it gets escalated to me directly.

**Comment by ericmustin** [comment] 2021-03-12 19:32
@dustyhorizon one more ping here, any chance you've been able to review the above?

**Comment by tonglil** [comment] 2021-03-16 20:06
We noticed this issue today when running the collector locally.

Will try to gather some data and post back.

**Comment by ericmustin** [comment] 2021-03-16 20:11
@tonglil thanks Tony, that would be super appreciated. If there is the potential for sensitive PII in any info please feel free to share via a support ticket w/ support@datadoghq.com, and mention this issue+me on the ticket, then share the ticket number here ( im also on the cncf slack).

**Comment by seanyu4296** [comment] 2021-05-28 09:50
i also face this right now

**Comment by cvestre-cisco** [comment] 2021-08-28 22:17
+1 on this. Using the collector in `v0.33.0`.

Traces are definitely making it to DD.

``` 2021-08-28T22:02:47.397Z    info    datadogexporter@v0.0.0-00010101000000-000000000000/traces_exporter.go:148    failed to send traces    {"kind": "exporter",  │
│ "name": "datadog", "error": "failed to send trace payload to trace edge: Post \"https://trace.agent.datadoghq.com/api/v0.2/traces\": dial tcp [2600:1f18:24e6:b │
│ 02:4070:273d:4fb6:5375[]:443: connect: network is unreachable"}                                                                                                 │
│ 2021-08-28T22:02:47.401Z    info    datadogexporter@v0.0.0-00010101000000-000000000000/traces_exporter.go:156    failed to send trace stats    {"kind": "export │
│ er", "name": "datadog", "error": "failed to send stats payload to trace edge: Post \"https://trace.agent.datadoghq.com/api/v0.2/stats\": dial tcp [2600:1f18:24 │
│ 6:b901:4982:ea87:c04b:bf8[]:443: connect: network is unreachable"} 
```

**Comment by StreetStrider** [comment] 2021-09-02 13:24
Hello. I had been seeing this error as well. I can't confirm that due to this error my traces are actually was sent to the datadog, I can't see them there either. The [image I was using](https://hub.docker.com/r/otel/opentelemetry-collector-contrib-dev) had been updated recently and now I see no errors, however, the traces still don't show in the datadog UI.

I will investigate what may be wrong on the side of my datadog account, however, I would like to try to look for errors on the container side as well. Can you give me some hints on how can I debug container aside from container debug output + logging exporter? I see my traces in the output. I've tried docker exec bash/sh into container with no luck.

**Comment by ericmustin** [comment] 2021-09-02 15:50
`network unreachable` is an indication that there's a network issue not specific to datadog. That being said `Support@datadoghq.com` is the best place to go for triaging this issue if it continues to pop up, as we'd need to collect your configuration info and may need to work with your organisation to diagnose/troubleshoot.

**Comment by StreetStrider** [comment] 2021-09-02 15:52
@ericmustin my error is not network unreachable. My error is as the topicstarter, so I posted here.
```
datadogexporter@v0.0.0-00010101000000-000000000000/traces_exporter.go:148	failed to send traces	{"kind": "exporter", "name": "datadog", "error": "failed to send trace payload to trace edge: Post \"https://trace.agent.datadoghq.com/api/v0.2/traces\": context deadline exceeded"}
```

**Comment by ericmustin** [comment] 2021-09-02 16:21
@StreetStrider gotcha ty for clarifying. support email linked above is still the appropriate avenue here.

**Comment by jfmyers9** [comment] 2021-09-16 21:34
Want to confirm that I am also seeing this issue on `v0.35.0`. I've gone ahead and opened a support ticket, but if we've found any solution, it would be good to publicize it here.

**Comment by mx-psi** [comment] 2021-11-04 11:38
Hi all, we recently added support for modifying the timeout on our exporter processing, as part of our support for [`exporterhelper` settings](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/exporterhelper#configuration). I would recommend increasing the `timeout` value from the default of 5 seconds to something like 30 seconds (that would be, setting `timeout: 30s` in the Datadog exporter configuration) to see if this decreases the amount of error logs. 

It would be helpful for us if you test this and share the results back to us, thanks!

**Comment by mx-psi** [comment] 2022-03-09 11:44
I am closing this since we believe it to be fixed by the change above and there have been no new reports for a while. If you still see this issue, increase the value of `timeout` to a higher value. If the issue persists, please comment here so that we can reopen the issue. Thanks!

**Closed by mx-psi** 2022-03-09 11:44 UTC
Labels: bug, comp:datadog, data:traces
