### ISSUE TITLE
OCB with otlpreceiver and jaeger 

### ISSUE THREAD

**Issue by Gauravmeenu** [open-telemetry/opentelemetry-collector-contrib#17188] opened 2022-12-21 09:08 UTC
### Describe the issue you're reporting

Whenever I'm compiling or creating a custom collector distribution with manifest.yaml file mentioning exporter (jaeger v0.68.0) and receiver (otlp v0.68.0), then my terminal pop-up the error like this 

Error: failed to compile the OpenTelemetry Collector distribution: exit status 2. Output:
# go.opentelemetry.io/collector/receiver/otlpreceiver/internal/metrics
..\..\..\pkg\mod\go.opentelemetry.io\collector\receiver\otlpreceiver@v0.64.1\internal\metrics\otlp.go:41:22: undefined: obsreport.MustNewReceiver    
# go.opentelemetry.io/collector/receiver/otlpreceiver/internal/logs
..\..\..\pkg\mod\go.opentelemetry.io\collector\receiver\otlpreceiver@v0.64.1\internal\logs\otlp.go:41:22: undefined: obsreport.MustNewReceiver       
# go.opentelemetry.io/collector/receiver/otlpreceiver/internal/trace
..\..\..\pkg\mod\go.opentelemetry.io\collector\receiver\otlpreceiver@v0.64.1\internal\trace\otlp.go:41:22: undefined: obsreport.MustNewReceiver

 anyone could help me in this kind of error.

**Comment by frzifus** [comment] 2022-12-22 14:20
Hi @Gauravmeenu

> ......\pkg\mod\go.opentelemetry.io\collector\receiver\otlpreceiver@**v0.64.1**\internal\trace\otlp.go:41:22: undefined: obsreport.MustNewReceiver

Seems there is somewhere a reference to an older otlp version. See @**v0.64.1**.

I could reproduce your error by using a log exporter with the version **v0.64.0**. 

```bash
$ cat > otelcol-builder.yaml <<EOF
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.64.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.68.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.68.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.68.0
EOF

$ builder --config=otelcol-builder.yaml --output-path=.         
Flag --output-path has been deprecated, use config distribution::output_path
2022-12-22T15:15:43.895+0100	INFO	internal/command.go:125	OpenTelemetry Collector Builder	{"version": "dev", "date": "unknown"}
2022-12-22T15:15:43.895+0100	INFO	internal/command.go:158	Using config file	{"path": "otelcol-builder.yaml"}
2022-12-22T15:15:43.895+0100	INFO	builder/config.go:107	Using go	{"go-executable": "/usr/local/go/bin/go"}
2022-12-22T15:15:43.896+0100	INFO	builder/main.go:76	Sources created	{"path": "."}
2022-12-22T15:15:47.487+0100	INFO	builder/main.go:118	Getting go modules
2022-12-22T15:15:47.809+0100	INFO	builder/main.go:87	Compiling
Error: failed to compile the OpenTelemetry Collector distribution: exit status 2. Output:
# go.opentelemetry.io/collector/exporter/loggingexporter/internal/otlptext
../../../golang_workspace/pkg/mod/go.opentelemetry.io/collector/exporter/loggingexporter@v0.64.0/internal/otlptext/databuffer.go:55:2: m.Sort() (no value) used as value or type
../../../golang_workspace/pkg/mod/go.opentelemetry.io/collector/exporter/loggingexporter@v0.64.0/internal/otlptext/databuffer.go:261:50: l.TraceID().HexString undefined (type pcommon.TraceID has no field or method HexString)
../../../golang_workspace/pkg/mod/go.opentelemetry.io/collector/exporter/loggingexporter@v0.64.0/internal/otlptext/databuffer.go:262:43: l.SpanID().HexString undefined (type pcommon.SpanID has no field or method HexString)
../../../golang_workspace/pkg/mod/go.opentelemetry.io/collector/exporter/loggingexporter@v0.64.0/internal/otlptext/logs.go:54:47: lr.TraceID().HexString undefined (type pcommon.TraceID has no field or method HexString)
../../../golang_workspace/pkg/mod/go.opentelemetry.io/collector/exporter/loggingexporter@v0.64.0/internal/otlptext/logs.go:55:45: lr.SpanID().HexString undefined (type pcommon.SpanID has no field or method HexString)
../../../golang_workspace/pkg/mod/go.opentelemetry.io/collector/exporter/loggingexporter@v0.64.0/internal/otlptext/traces.go:48:44: span.TraceID().HexString undefined (type pcommon.TraceID has no field or method HexString)
../../../golang_workspace/pkg/mod/go.opentelemetry.io/collector/exporter/loggingexporter@v0.64.0/internal/otlptext/traces.go:49:50: span.ParentSpanID().HexString undefined (type pcommon.SpanID has no field or method HexString)
../../../golang_workspace/pkg/mod/go.opentelemetry.io/collector/exporter/loggingexporter@v0.64.0/internal/otlptext/traces.go:50:37: span.SpanID().HexString undefined (type pcommon.SpanID has no field or method HexString)
```

Changing it to **v0.68.0** too, fixed the issue.

---

Does that help? Or could you otherwise share your `manifest.yaml`?

**Comment by mx-psi** [comment] 2022-12-22 14:50
I think this is a duplicate of open-telemetry/opentelemetry-collector/issues/6841

**Comment by Gauravmeenu** [comment] 2022-12-23 05:08
Yeah you are right @mx-psi I already got the solution but thank you so much @frzifus for replying me back.

**Closed** 2022-12-23 07:59 UTC
Labels: needs triage
