### ISSUE TITLE
Use log file as receiver of trace pipeline

### ISSUE THREAD

**Issue by databhor** [open-telemetry/opentelemetry-collector-contrib#25150] opened 2023-08-10 19:21 UTC
### Component(s)

receiver/filelog

### Describe the issue you're reporting

Can I use log file as receiver of trace pipeline?
We wantted to output trace content to stdout in Java app pod, and expect otel collector can read this file locally from folder _/var/log/containers/_ where k8s saves the console prints.
The purpose is to avoid loss of trace when otel collector is temperarily unavailable. Log file provides persistence of trace data after all.
I saw the error from otel collector 
> failed to create "filelog" receiver for data type "traces": telemetry type is not supported

So is there any way to achieve this? Thanks :)

**Comment by djaglowski** [comment] 2023-08-11 18:14
The filelog receiver can only interpret logs from files.

I see a few potential solutions here, which may new development:
1. The `file` receiver is supposed to read files that contain any data type, but the format must be exactly as it expects.
2. The `filelog` receiver could read the spans _as logs_, and then a logs->traces connector could convert each log as a span. The connector could potentially be configurable to allow for flexibility in the data format.

I'll close this issue for now but feel free to open another if you find the file receiver does not work as intended, or if you would like to propose a connector.

**Closed by djaglowski** 2023-08-11 18:14 UTC
Labels: receiver/filelog, needs triage
