### ISSUE TITLE
[pkg/ottl] Add a function for concatenating lists

### ISSUE THREAD

**Issue by lopes-felipe** [open-telemetry/opentelemetry-collector-contrib#32266] opened 2024-04-09 15:25 UTC
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

OTTL has no way to concatenate two (or more) lists into a single one, requiring to do some not-so-great workarounds with `concat()` and `split()`, and others.

### Describe the solution you'd like

Add a new OTTL function that receives two lists and returns a new one containing all the items from both.

### Describe alternatives you've considered

`split(concat([concat(a, ","), concat(b, ",")], ","), ",")`

### Additional context

Use case: dynamically define the list of labels to be provided for the `keep_keys` from two sources.

**Comment by TylerHelmuth** [comment] 2024-04-10 20:49
This a duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32141. I am closing this issue in favor of the other.  @lopes-felipe please ping me if you feel the feature you're requesting is different.

**Closed by TylerHelmuth** 2024-04-10 20:49 UTC
Labels: enhancement, pkg/ottl, needs triage
