### ISSUE TITLE
[datadogexporter] `.count` and `.sum` metrics not being exported for Summary type

### ISSUE THREAD

**Issue by sirianni** [open-telemetry/opentelemetry-collector-contrib#6485] opened 2021-12-02 00:36 UTC
**Describe the bug**
For a `Summary` metric `foo`, I only see the `foo.quantile` metric in datadog.  I do not see the `foo.count` and `foo.sum` metrics.

**Steps to reproduce**
Send a `Summary` metric to the OTel Collector configured with the Datadog exporter.

**What did you expect to see?**
I expected to see the following metrics:
* `foo.sum`
* `foo.count`
* `foo.quantile` 

**What did you see instead?**
Only `foo.quantile`

**What version did you use?**
Version: `v0.39.0`

**What config did you use?**
```yaml
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
    timeout: 10s
    send_batch_max_size: 50
    send_batch_size: 50

exporters:
  logging:
    logLevel: info
  datadog:
    env: "${DD_ENV}"
    api:
      key: "${DD_APIKEY}"

service:
  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - datadog
```

**Environment**
OS: Linux

**Additional context**
I stepped through the code https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/internal/translator/metrics_translator.go#L363-L377 and it appears that `t.prevPts.Diff()` is returning `ok = false` for both the count and sum, causing `consumer.ConsumeTimeSeries` not to be called.  I haven't been able to root cause why this is the case.

**Comment by KSerrania** [comment] 2021-12-02 11:20
Hi @sirianni,

Thanks for raising this issue!

To help us investigate, could you share the code you used to generate the summary metrics, as well as the output of the logging exporter? If possible, could you also enable the [file exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/fileexporter) and send us its output?

I've tried reproducing your issue using the following app (with the Go SDK) to generate summary metrics, but haven't managed to reproduce what you're seeing yet:
<details>

<summary>App code</summary>

```
package main

import (
	"context"
	"log"
	"time"

	"google.golang.org/grpc"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/global"
	controller "go.opentelemetry.io/otel/sdk/metric/controller/basic"
	processor "go.opentelemetry.io/otel/sdk/metric/processor/basic"
	"go.opentelemetry.io/otel/sdk/metric/selector/simple"
)

// Initializes an OTLP exporter, and configures the corresponding trace and
// metric providers.
func initProvider() func() {
	ctx := context.Background()

	exp, err := otlpmetricgrpc.New(
		ctx,
		otlpmetricgrpc.WithInsecure(),
		otlpmetricgrpc.WithEndpoint("otel-collector:30080"),
		otlpmetricgrpc.WithDialOption(grpc.WithBlock()),
	)
	handleErr(err, "failed to create exporter")

	cont := controller.New(
		processor.New(
			simple.NewWithInexpensiveDistribution(),
			exp,
		),
		controller.WithExporter(exp),
		controller.WithCollectPeriod(2*time.Second),
	)

	global.SetMeterProvider(cont.MeterProvider())
	handleErr(cont.Start(context.Background()), "failed to start controller")

	return func() {
		// Push any last metric events to the exporter.
		handleErr(cont.Stop(context.Background()), "failed to stop controller")
	}
}

func main() {
	log.Printf("Waiting for connection...")

	shutdown := initProvider()
	defer shutdown()

	meter := global.Meter("test-meter")

	commonLabels := []attribute.KeyValue{
		attribute.String("label", "value"),
	}

	ioReadBytes := metric.Must(meter).
		NewInt64Histogram(
			"io.read.bytes",
			metric.WithDescription("IO read bytes"),
		).Bind(commonLabels...)
	defer ioReadBytes.Unbind()

	for i := 0; i < 10; i++ {
		ioReadBytes.Record(context.Background(), int64(i))

		<-time.After(time.Second)
	}

	log.Printf("Done!")
}

func handleErr(err error, message string) {
	if err != nil {
		log.Fatalf("%s: %v", message, err)
	}
}
```
</details>

<details>

<summary>Collector config</summary>

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:30080"

exporters:
  file/metrics:
    path: /etc/otel/metrics.dat
  datadog:
    api:
      key: <api key>

service:
  telemetry:
    logs:
      level: warn

  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [datadog, file/metrics]
```
</details>

My main guesses for now are either:
- something weird around the timestamps of the summary metrics (that's the main reason why a point would be considered invalid by `t.prevPts.Diff()`)
- not enough metrics sent (the count and sum metrics are cumulative metrics, we don't send the first point - you need to send at least two points to be able to see something).

**Comment by sirianni** [comment] 2021-12-02 19:27
Hi @KSerrania thanks for the quick response!

I think the issue may be that we are configuring the OTLP exporter in our application with `DELTA` temporality
```java
public class DeltaViewConfigurer implements SdkMeterProviderConfigurer {

  @Override
  public void configure(SdkMeterProviderBuilder sdkMeterProviderBuilder) {
    InstrumentSelector instrumentSelector = InstrumentSelector.builder()
        .setInstrumentType(InstrumentType.COUNTER)
        .build();

    sdkMeterProviderBuilder.registerView(
        instrumentSelector,
        View.builder()
            .setAggregatorFactory(AggregatorFactory.sum(AggregationTemporality.DELTA))
            .build()
    );
  }
}
```

That said, we've set the instrument selector to `InstrumentType.COUNTER` so it shouldn't affect `Summary` (or `ValueRecorder`) instruments.

My guess is that this appears to be causing the `count` and `sum` fields in the Summary to be sent as deltas from our app and not monotonically increasing counters.  Perhaps this is a bug in the Java SDK .  On the OTLP side I see that `Histogram` has an `AggregationTemporality` field, but `Summary` does not :thinking: .  

```golang
				case pdata.MetricDataTypeHistogram:
					switch md.Histogram().AggregationTemporality() {
```

Here are the data points.  You can see that the `count` and `sum` fields are not monotonically increasing at the OTLP level.

First data point `2021-12-02 19:16:06`
```
Metric #0
Descriptor:
     -> Name: io.confluent.metrics_api.export.samples
     -> Description: 
     -> Unit: 1
     -> DataType: Summary
SummaryDataPoints #0
Data point attributes:
     -> metric: STRING(confluent_kafka_server_sent_records)
StartTimestamp: 2021-12-02 19:16:06.026611419 +0000 UTC
Timestamp: 2021-12-02 19:16:46.31890528 +0000 UTC
Count: 2
Sum: 52.000000
QuantileValue #0: Quantile 0.000000, Value 9.000000
QuantileValue #1: Quantile 1.000000, Value 43.000000
```

Second data point `2021-12-02 19:16:46`
```
Metric #0
Descriptor:
     -> Name: io.confluent.metrics_api.export.samples
     -> Description: 
     -> Unit: 1
     -> DataType: Summary
SummaryDataPoints #0
Data point attributes:
     -> metric: STRING(confluent_kafka_server_sent_records)
StartTimestamp: 2021-12-02 19:16:46.31890528 +0000 UTC
Timestamp: 2021-12-02 19:17:26.318699617 +0000 UTC
Count: 3
Sum: 95.000000
QuantileValue #0: Quantile 0.000000, Value 9.000000
QuantileValue #1: Quantile 1.000000, Value 43.000000
```

Third data point `2021-12-02 19:17:26`
```
Metric #0
Descriptor:
     -> Name: io.confluent.metrics_api.export.samples
     -> Description: 
     -> Unit: 1
     -> DataType: Summary
SummaryDataPoints #0
Data point attributes:
     -> metric: STRING(confluent_kafka_server_sent_records)
StartTimestamp: 2021-12-02 19:17:26.318699617 +0000 UTC
Timestamp: 2021-12-02 19:17:46.318791812 +0000 UTC
Count: 3
Sum: 61.000000
QuantileValue #0: Quantile 0.000000, Value 9.000000
QuantileValue #1: Quantile 1.000000, Value 43.000000
```

**Comment by KSerrania** [comment] 2021-12-07 13:33
Hey again @sirianni,

As you mentioned, Summary points do not have any aggregation temporality, so we consider Summary counts and sums to be cumulative in the Datadog exporter.

However, in the points that you are sending, the `StartTimestamp` changes every time, which triggers a reset in our cumulative points cache: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/34a38f6a52af70f7de946738eda21ca6a1b2c452/exporter/datadogexporter/internal/translator/ttlcache.go#L70-L82
as a changing `StartTimestamp` for cumulative series indicates a reset. And since we don't send the first point of a cumulative series, that results in no `sum` nor `count` points being sent at all.

It seems like the reason I haven't been able to reproduce this on my end (using my example in the above comment) is that the Go SDK is sending the Summary count and sum as cumulative counters, with the same `StartTimestamp` every time (which matches what we expect in the exporter):

<details>

<summary>Go SDK Summary example logs</summary>

``` 
2021-12-07T13:18:38.021Z    INFO    loggingexporter/logging_exporter.go:54  MetricsExporter {"#metrics": 1}
2021-12-07T13:18:38.022Z    DEBUG   loggingexporter/logging_exporter.go:64  ResourceMetrics #0

Resource labels:
     -> service.name: STRING(unknown_service:main)
     -> telemetry.sdk.language: STRING(go)
     -> telemetry.sdk.name: STRING(opentelemetry)
     -> telemetry.sdk.version: STRING(1.2.0)
InstrumentationLibraryMetrics #0
InstrumentationLibrary test-meter 
Metric #0
Descriptor:
     -> Name: io.read.bytes
     -> Description: IO read bytes
     -> Unit: 
     -> DataType: Summary
SummaryDataPoints #0
Data point attributes:
     -> label: STRING(value)
StartTimestamp: 2021-12-07 13:18:34.0190324 +0000 UTC
Timestamp: 2021-12-07 13:18:36.0203199 +0000 UTC
Count: 3
Sum: 3.000000
QuantileValue #0: Quantile 0.000000, Value 0.000000
QuantileValue #1: Quantile 1.000000, Value 2.000000

2021-12-07T13:18:38.021Z    INFO    loggingexporter/logging_exporter.go:54  MetricsExporter {"#metrics": 1}
2021-12-07T13:18:38.022Z    DEBUG   loggingexporter/logging_exporter.go:64  ResourceMetrics #0
Resource labels:
     -> service.name: STRING(unknown_service:main)
     -> telemetry.sdk.language: STRING(go)
     -> telemetry.sdk.name: STRING(opentelemetry)
     -> telemetry.sdk.version: STRING(1.2.0)
InstrumentationLibraryMetrics #0
InstrumentationLibrary test-meter 
Metric #0
Descriptor:
     -> Name: io.read.bytes
     -> Description: IO read bytes
     -> Unit: 
     -> DataType: Summary
SummaryDataPoints #0
Data point attributes:
     -> label: STRING(value)
StartTimestamp: 2021-12-07 13:18:34.0190324 +0000 UTC
Timestamp: 2021-12-07 13:18:38.0195007 +0000 UTC
Count: 4
Sum: 6.000000
QuantileValue #0: Quantile 0.000000, Value 0.000000
QuantileValue #1: Quantile 1.000000, Value 3.000000

2021-12-07T13:18:40.021Z    INFO    loggingexporter/logging_exporter.go:54  MetricsExporter {"#metrics": 1}
2021-12-07T13:18:40.022Z    DEBUG   loggingexporter/logging_exporter.go:64  ResourceMetrics #0
Resource labels:
     -> service.name: STRING(unknown_service:main)
     -> telemetry.sdk.language: STRING(go)
     -> telemetry.sdk.name: STRING(opentelemetry)
     -> telemetry.sdk.version: STRING(1.2.0)
InstrumentationLibraryMetrics #0
InstrumentationLibrary test-meter 
Metric #0
Descriptor:
     -> Name: io.read.bytes
     -> Description: IO read bytes
     -> Unit: 
     -> DataType: Summary
SummaryDataPoints #0
Data point attributes:
     -> label: STRING(value)
StartTimestamp: 2021-12-07 13:18:34.0190324 +0000 UTC
Timestamp: 2021-12-07 13:18:40.0207233 +0000 UTC
Count: 6
Sum: 15.000000
QuantileValue #0: Quantile 0.000000, Value 0.000000
QuantileValue #1: Quantile 1.000000, Value 5.000000

2021-12-07T13:18:42.022Z    INFO    loggingexporter/logging_exporter.go:54  MetricsExporter {"#metrics": 1}
2021-12-07T13:18:42.022Z    DEBUG   loggingexporter/logging_exporter.go:64  ResourceMetrics #0
Resource labels:
     -> service.name: STRING(unknown_service:main)
     -> telemetry.sdk.language: STRING(go)
     -> telemetry.sdk.name: STRING(opentelemetry)
     -> telemetry.sdk.version: STRING(1.2.0)
InstrumentationLibraryMetrics #0
InstrumentationLibrary test-meter 
Metric #0
Descriptor:
     -> Name: io.read.bytes
     -> Description: IO read bytes
     -> Unit: 
     -> DataType: Summary
SummaryDataPoints #0
Data point attributes:
     -> label: STRING(value)
StartTimestamp: 2021-12-07 13:18:34.0190324 +0000 UTC
Timestamp: 2021-12-07 13:18:42.0214763 +0000 UTC
Count: 8
Sum: 28.000000
QuantileValue #0: Quantile 0.000000, Value 0.000000
QuantileValue #1: Quantile 1.000000, Value 7.000000

2021-12-07T13:18:44.022Z    INFO    loggingexporter/logging_exporter.go:54  MetricsExporter {"#metrics": 1}
2021-12-07T13:18:44.022Z    DEBUG   loggingexporter/logging_exporter.go:64  ResourceMetrics #0
Resource labels:
     -> service.name: STRING(unknown_service:main)
     -> telemetry.sdk.language: STRING(go)
     -> telemetry.sdk.name: STRING(opentelemetry)
     -> telemetry.sdk.version: STRING(1.2.0)
InstrumentationLibraryMetrics #0
InstrumentationLibrary test-meter 
Metric #0
Descriptor:
     -> Name: io.read.bytes
     -> Description: IO read bytes
     -> Unit: 
     -> DataType: Summary
SummaryDataPoints #0
Data point attributes:
     -> label: STRING(value)
StartTimestamp: 2021-12-07 13:18:34.0190324 +0000 UTC
Timestamp: 2021-12-07 13:18:44.0213268 +0000 UTC
Count: 10
Sum: 45.000000
QuantileValue #0: Quantile 0.000000, Value 0.000000
QuantileValue #1: Quantile 1.000000, Value 9.000000
```

</details>

I also tried searching for other similar cases, and found this one in the `statsdreceiver`: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5742, which seems to confirm that Summary count and sum should be cumulative.

> Also mentioned in #5667, the Summary point issued by statsdreceiver uses delta temporality. This is not specified, and delta temporality will never be specified for Summary points.


Which instrument of the Java SDK are you using to send Summaries?

**Comment by sirianni** [comment] 2021-12-07 13:50
> in the points that you are sending, the StartTimestamp changes every time

This supports the suspicion that the points are being sent as deltas.  If it 

> Which instrument of the Java SDK are you using to send Summaries?

Hi @KSerrania .  I am using a `LongValueRecorder`.  We are still on a somewhat old version of the Java SDK.  It's possible there is a bug in the OTLP exporter for how summaries are exported.

**Comment by KSerrania** [comment] 2022-02-03 10:27
We're going to close this issue. We believe the issue comes from the old `LongValueRecorder` java instrument not sending summary counters and timestamps that match the spec, causing our exporter to reset the counters after each point it receives. The `LongValueRecorder` instrument has been removed in the `1.5.0` release of the java SDK, so this issue shouldn't happen on the latest java SDK version.

Feel free to reopen this if you see this happen again on the latest opentelemetry-java version.

**Closed** 2022-02-03 10:31 UTC
Labels: bug, comp:datadog, data:metrics
