### ISSUE TITLE
docker_stats receiver issue | RHEL 8.9

### ISSUE THREAD

**Issue by abhi60444** [open-telemetry/opentelemetry-collector-contrib#34320] opened 2024-07-30 13:07 UTC
Hi Team,

We are using docker_stats receiver to scrape docker containers metrics but we are getting below error specific with RHEL 8.9 O.S version . We had also tried with RHEL 9.3 and Oracle Linux 8.5 OS version in test environment but didn't see these error there so kindly help/guide us to resolve this issue as we can't upgrade all the OS version as it's high in count. Thanks

**Error Logs:**
```
2024-07-22T15:04:05.308Z	error	docker@v0.96.0/docker.go:193	Could not parse docker containerStats for container id	{"kind": "receiver", "name": "docker_stats", "data_type": "metrics", "id": "3260ab7726466faf12684aca01d1d9f54ec66499843d12c61706e5d0c2dba332", "error": "context canceled"}
[github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker](http://github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker).(*Client).toStatsJSON
	[github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.96.0/docker.go:193](http://github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.96.0/docker.go:193)
[github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker](http://github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker).(*Client).FetchContainerStatsAsJSON
	[github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.96.0/docker.go:143](http://github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.96.0/docker.go:143)
[github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver](http://github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver).(*metricsReceiver).scrapeV2.func1
	[github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver@v0.96.0/receiver.go:81](http://github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver@v0.96.0/receiver.go:81)
2024-07-22T15:04:05.309Z	error	scraperhelper/scrapercontroller.go:197	Error scraping metrics	{"kind": "receiver", "name": "docker_stats", "data_type": "metrics", "error": "context canceled", "scraper": "docker_stats"}
[go.opentelemetry.io/collector/receiver/scraperhelper](http://go.opentelemetry.io/collector/receiver/scraperhelper).(*controller).scrapeMetricsAndReport
	[go.opentelemetry.io/collector/receiver@v0.96.0/scraperhelper/scrapercontroller.go:197](http://go.opentelemetry.io/collector/receiver@v0.96.0/scraperhelper/scrapercontroller.go:197)
[go.opentelemetry.io/collector/receiver/scraperhelper](http://go.opentelemetry.io/collector/receiver/scraperhelper).(*controller).startScraping.func1
[go.opentelemetry.io/collector/receiver@v0.96.0/scraperhelper/scrapercontroller.go:173](http://go.opentelemetry.io/collector/receiver@v0.96.0/scraperhelper/scrapercontroller.go:173)
```

**Comment by codeboten** [comment] 2024-07-30 14:45
Thanks for reporting @abhi60444, I've transferred the issue and updated the description to make reading the logs a bit easier

**Comment by atoulme** [comment] 2024-08-01 08:34
Please try with the latest release.

**Comment by julianocosta89** [comment] 2024-08-01 11:12
@atoulme I'm not running on RHEL, but I have a similar case here: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34194

I've just tested with `0.106.0` and the issue persists.

**Comment by mx-psi** [comment] 2024-08-02 13:20
I am going to close this as a duplicate of #34194, let's continue the convo there

**Closed by mx-psi** 2024-08-02 13:20 UTC
Labels: receiver/dockerstats, needs triage
