### ISSUE TITLE
Logs can't export to Loki

### ISSUE THREAD

**Issue by wadexu007** [open-telemetry/opentelemetry-collector-contrib#16836] opened 2022-12-10 01:17 UTC
### Component(s)

exporter/loki

## Description
Loki Exporter seems not work. Logs can't export to Loki in Grafana Cloud.

## Steps to Reproduce
Below is k8s manifests, kubectl apply it to cluster.

## Expected Result
I can explore logs in Grafana Loki.

## Actual Result
No any logs export to Loki. 

Check pod logs,  It looks like not much is happening in the otel collector pod from those logs after the exporter processes start. 

### Collector version

0.66.0

## Environment
Google Kubernetes Engine 1.22

### OpenTelemetry Collector configuration

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-agent
  labels:
    app: opentelemetry
    component: otel-collector
  namespace: demo
data:
  otel-collector-agent: |
    receivers:
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        start_at: beginning
        include_file_path: true
        include_file_name: true

    exporters:
      logging:
        verbosity: detailed
      loki:
        endpoint: https://xxx:xxxxxx@logs-prod3.grafana.net/loki/api/v1/push
    service:
      pipelines:
        logs:
          receivers: [filelog]
          exporters: [loki, logging]
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector-agent
  labels:
    app: opentelemetry
    component: otel-collector
  namespace: demo
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
        
    spec:  
      # serviceAccountName: otel-collector
      containers:
        - name: otel-collector
          command:
            - "/otelcol-contrib"
            - "--config=/conf/otel-collector-agent.yaml"
          image: "otel/opentelemetry-collector-contrib:0.66.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: otlp
              containerPort: 4317
              protocol: TCP
              hostPort: 4317
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
              hostPort: 4318
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP

          resources:
            limits:
              cpu: 256m
              memory: 512Mi
          volumeMounts:
            - mountPath: /conf
              name: otel-collector-conf-vol
            - mountPath: /var/log/pods
              name: varlogpods
              readOnly: true
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
      volumes:
        - name: otel-collector-conf-vol
          configMap:
            name: otel-collector-agent
            items:
              - key: otel-collector-agent
                path: otel-collector-agent.yaml
        - hostPath:
            path: /var/log/pods
          name: varlogpods
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
      hostNetwork: false
```

### Log output

```shell
2022/12/09 02:49:10 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/12/09 02:49:10 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
2022-12-09T02:49:10.632Z    info    service/telemetry.go:110    Setting up own telemetry...
2022-12-09T02:49:10.632Z    info    service/telemetry.go:140    Serving Prometheus metrics  {"address": ":8888", "level": "basic"}
2022-12-09T02:49:10.632Z    info    lokiexporter@v0.64.0/next_exporter.go:43    using the new Loki exporter {"kind": "exporter", "data_type": "logs", "name": "loki"}
2022-12-09T02:49:10.717Z    info    service/service.go:89   Starting otelcol-contrib... {"Version": "0.64.1", "NumCPU": 8}
2022-12-09T02:49:10.717Z    info    extensions/extensions.go:41 Starting extensions...
2022-12-09T02:49:10.717Z    info    pipelines/pipelines.go:74   Starting exporters...
2022-12-09T02:49:10.717Z    info    pipelines/pipelines.go:78   Exporter is starting... {"kind": "exporter", "data_type": "logs", "name": "loki"}
2022-12-09T02:49:10.717Z    info    pipelines/pipelines.go:82   Exporter started.   {"kind": "exporter", "data_type": "logs", "name": "loki"}
2022-12-09T02:49:10.717Z    info    pipelines/pipelines.go:86   Starting processors...
2022-12-09T02:49:10.717Z    info    pipelines/pipelines.go:98   Starting receivers...
2022-12-09T02:49:10.717Z    info    pipelines/pipelines.go:102  Receiver is starting... {"kind": "receiver", "name": "filelog", "pipeline": "logs"}
2022-12-09T02:49:10.717Z    info    adapter/receiver.go:55  Starting stanza receiver    {"kind": "receiver", "name": "filelog", "pipeline": "logs"}
2022-12-09T02:49:10.718Z    info    pipelines/pipelines.go:106  Receiver started.   {"kind": "receiver", "name": "filelog", "pipeline": "logs"}
2022-12-09T02:49:10.718Z    info    service/service.go:106  Everything is ready. Begin running and processing data.
2022-12-09T02:49:10.920Z    info    fileconsumer/file.go:159    Started watching file   {"kind": "receiver", "name": "filelog", "pipeline": "logs", "component": "fileconsumer", "path": "/hostfs/var/log/pods/agents_grafana-agent-logs-cloud-94c88_4ca3b7b0-a1e2-4e9d-a0b7-f6b75953e156/grafana-agent-logs-cloud/0.log"}
```

**Comment by fatsheep9146** [comment] 2022-12-10 02:53
logging:
    loglevel: debug

@wadexu007 can you set logging config to this and check the log again?

**Comment by wadexu007** [comment] 2022-12-12 01:30
@fatsheep9146 Hello, 

When I set log level debug (deprecated) or below new flag.  I got same logs as above, not seen any debug logs.
```
exporters:
  logging:
    verbosity: detailed
```

**Comment by mar4uk** [comment] 2022-12-12 09:51
@wadexu007 did you add a logging exporter to the pipeline?
```
service:
      pipelines:
        logs:
          receivers: [filelog]
          exporters: [logging, loki]
```

**Comment by wadexu007** [comment] 2022-12-12 09:55
@mar4uk  Yes, sure
<img width="252" alt="image" src="https://user-images.githubusercontent.com/48537883/207015812-94a5cf6a-fadb-441c-978f-9ea6a9110db4.png">

**Comment by mar4uk** [comment] 2022-12-12 11:59
That's strange that there are no log entries in the output after adding logging exporter to the pipeline. It means that there are no log entries coming at all. 
That makes me think the problem is not in loki exporter.
Probably no logs were written to the file `/hostfs/var/log/pods/agents_grafana-agent-logs-cloud-94c88_4ca3b7b0-a1e2-4e9d-a0b7-f6b75953e156/grafana-agent-logs-cloud/0.log`

**Comment by fatsheep9146** [comment] 2022-12-12 14:10
could you see this file `/hostfs/var/log/pods/agents_grafana-agent-logs-cloud-94c88_4ca3b7b0-a1e2-4e9d-a0b7-f6b75953e156/grafana-agent-logs-cloud/0.log` contain any logs? 
If there exists log, could you see the latest log entry of this file?

**Comment by wadexu007** [comment] 2022-12-13 05:53
@mar4uk @fatsheep9146 Yes. I can see latest log entry of this file. 

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/48537883/207236538-911a56ff-c844-45c4-90ee-6168b7509268.png">

Also, it probably a problem related to filelog receiver, from above screenshot, you can see i have lots of pods, but otel collector logs only watch one pod. 
```
Started watching file   {"kind": "receiver", "name": "filelog", "pipeline": "logs", "component": "fileconsumer", "path": "/hostfs/var/log/pods/agents_grafana-agent-logs-cloud-94c88_4ca3b7b0-a1e2-4e9d-a0b7-f6b75953e156/grafana-agent-logs-cloud/0.log"}
```

**Comment by fatsheep9146** [comment] 2022-12-13 06:56
Yes, I also noticed that on my local test environment, I also found if you recreate a pod after the collector pod start up, the newly recreated pod's log will also be watched by filelog receiver. So I doubt this may be related to the way of volume mounts. I will keep digging this. @wadexu007

**Comment by jpkrohling** [comment] 2023-01-20 12:50
@wadexu007, could you please share the metrics available as part of the collector's own /metrics endpoint? It should clearly tell whether log entries were received by the collector.

**Comment by ahmedwonolo** [comment] 2023-01-23 23:14
I see similar issue.
If it helps here's `/metrics` output (grep'ed for `loki`).

```
otelcol_exporter_enqueue_failed_log_records{exporter="loki/local",service_instance_id="12f32886-ee36-4605-b318-3b17bfd8157d",service_name="otelcol-contrib",service_version="0.69.0"} 0
otelcol_exporter_enqueue_failed_metric_points{exporter="loki/local",service_instance_id="12f32886-ee36-4605-b318-3b17bfd8157d",service_name="otelcol-contrib",service_version="0.69.0"} 0
otelcol_exporter_enqueue_failed_spans{exporter="loki/local",service_instance_id="12f32886-ee36-4605-b318-3b17bfd8157d",service_name="otelcol-contrib",service_version="0.69.0"} 0
otelcol_exporter_queue_capacity{exporter="loki/local",service_instance_id="12f32886-ee36-4605-b318-3b17bfd8157d",service_name="otelcol-contrib",service_version="0.69.0"} 5000
otelcol_exporter_queue_size{exporter="loki/local",service_instance_id="12f32886-ee36-4605-b318-3b17bfd8157d",service_name="otelcol-contrib",service_version="0.69.0"} 0
```

**Comment by jpkrohling** [comment] 2023-01-24 19:59
@mar4uk, are you able to look into this?

**Comment by ahmedwonolo** [comment] 2023-01-27 22:40
my issue turned out to be permission issue. I have otel contrib collector running as a service on the machine. Looks like it comes with its own user which isn't a root user. I had `filelog` reading from locations where otel-collector wouldn't be able to reach due to permission lock down.

**Comment by jpkrohling** [comment] 2023-01-30 16:09
Reopening, I thought the last comment fixed the original problem, but there's no confirmation this is the case.

**Comment by mar4uk** [comment] 2023-01-31 11:41
Just ran the Kubernetes cluster locally and applied the manifest from the description, just changed the version of the collector to 0.70.0
And I can see logs from the pod in Grafana Cloud Loki:

<img width="1457" alt="Screenshot 2023-01-31 at 11 40 20" src="https://user-images.githubusercontent.com/2266206/215750283-c2e31c31-8d68-4563-afc3-67c9a7a7d8c5.png">

@wadexu007 could you please try to use the newer collector version? Is the problem still persist?

**Comment by medival** [comment] 2023-02-01 04:23
Now, I can see logs from k8s in the loki

![Screenshot from 2023-02-01 11-21-08](https://user-images.githubusercontent.com/24785432/215946526-2d010dc3-b0a9-443d-a9c4-8e86b642e922.png)

**Comment by jpkrohling** [comment] 2023-02-01 11:50
It looks like this might be fixed in recent versions of the collector. I'm closing, but feel free to reopen if you are still having issues.

**Closed by jpkrohling** 2023-02-01 11:50 UTC
Labels: bug, needs triage

**Comment by hzhhong** [comment] 2023-08-16 08:00
Reopening, unable to collect logs from symbolic link file
collector version: 0.82.0
container runtime: docker

1. config file
``` yaml
    receivers:
      filelog:
        exclude:
        - /var/log/pods/kube-system_*/*/*.log
        include:
        - /var/log/test/*.log
        include_file_name: false
        include_file_path: true
        start_at: beginning

    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      logging:
        verbosity: detailed
      loki/loki:
        endpoint: http://loki.monitoring:3100/loki/api/v1/push
        default_labels_enabled:
          exporter: true
          job: true
          instance: true
          level: true

    service:
      pipelines:
        logs:
          receivers: [filelog]
          exporters: [logging, loki/loki]
```

2. add symbolic link file
```
ln -s /var/lib/docker/containers/8xx/8xx-json.log 0.log
```
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/83079531/e169e264-dc14-4151-9d48-91b13a9e986b)

3. collector log output:
```
023-08-16T07:51:50.089Z        info    service/telemetry.go:84 Setting up own telemetry...
2023-08-16T07:51:50.090Z        info    service/telemetry.go:201        Serving Prometheus metrics      {"address": ":8888", "level": "Basic"}
2023-08-16T07:51:50.090Z        info    exporter@v0.82.0/exporter.go:275        Development component. May change in the future.        {"kind": "exporter", "data_type": "logs", "name": "logging"}
2023-08-16T07:51:50.090Z        info    lokiexporter@v0.82.0/exporter.go:41     using the new Loki exporter     {"kind": "exporter", "data_type": "logs", "name": "loki/loki"}
2023-08-16T07:51:50.093Z        info    service/service.go:132  Starting otelcol-contrib...     {"Version": "0.82.0", "NumCPU": 16}
2023-08-16T07:51:50.093Z        info    extensions/extensions.go:30     Starting extensions...
2023-08-16T07:51:50.093Z        info    adapter/receiver.go:45  Starting stanza receiver        {"kind": "receiver", "name": "filelog", "data_type": "logs"}
2023-08-16T07:51:50.093Z        info    service/service.go:149  Everything is ready. Begin running and processing data.
2023-08-16T07:51:50.294Z        info    fileconsumer/file.go:203        Started watching file   {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "/var/log/test/0.log"}
```

**Comment by RRKesamreddy** [comment] 2023-09-19 04:48
service:
      pipelines:
        logs:
          receivers: [filelog]
          exporters: [logging, loki]                                                                                                                                                           but in the screenshot
 exporter shows OTLP  in the grafana ui

**Comment by RRKesamreddy** [comment] 2023-09-19 04:50
with latest version 0.84.0  i could not able to  push  to loki .here i am using journadlogreceiver to loki
