### ISSUE TITLE
[exporter/loki] Make it easier to map OpenTelemetry Severity to Loki level label

### ISSUE THREAD

**Issue by kago-dk** [open-telemetry/opentelemetry-collector-contrib#14313] opened 2022-09-19 20:43 UTC
### Is your feature request related to a problem? Please describe.

Currently, the log level is tracked as SeverityText (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md) in v0.60.0, while the same information is tracked in the level label in Loki (https://grafana.com/docs/grafana/latest/explore/logs-integration/). It would be optimal if we could avoid tracking the log level as both "SeverityText" and "level" in the OTEL Collector to make Loki work and support mapping between "SeverityText" and "level" in the Loki Exporter configuration.

*Example*
<img width="1025" alt="NoLevel_Body_Purple" src="https://user-images.githubusercontent.com/49529296/191111206-c1541e86-8502-4648-b15f-11b49e5c7608.png">
If the level is not set, Loki presents the log line as purple because the body text includes the word "Alert"

<img width="1177" alt="AttributeLevel_Body_Purple" src="https://user-images.githubusercontent.com/49529296/191111399-ed3b2265-3c50-4e41-aebb-c3cbdc7fd5b5.png">
If the level is set but not part of loki.attribute.labels, then Loki presents the logline as purple because the body text includes the word "Alert"

```
  attributes/logs:
    actions:
    - action: insert
      key: loki.attribute.labels
      value: net_sock_peer_addr
```
<img width="1071" alt="Level_Green" src="https://user-images.githubusercontent.com/49529296/191111722-d823d974-bb5f-483f-867b-82d5976ba667.png">
If the level is set and part of loki.attribute.labels, then Loki presents the logline as green because Loki uses the log level from the level label.

```
  attributes/logs:
    actions:
    - action: insert
      key: loki.attribute.labels
      value: net_sock_peer_addr,level
```

 

### Describe the solution you'd like

Support mapping between "SeverityText" and "level" in the Loki Exporter configuration in the OTEL Collector, so the user is not forced into Loki-specific transformation in the OTEL Collector. Ideally, it should happen automatically since the purpose of the fields is the same on both sides.

**Comment by jpkrohling** [comment] 2022-09-26 20:30
Sounds reasonable to me! Would you like to open a PR for that?

**Comment by kago-dk** [comment] 2022-09-26 20:49
@jpkrohling I do not have the skills to do it.

**Comment by jtama** [comment] 2022-09-27 08:41
I don't know if the issue is related but the opentelemtry documentation states : 

> SeverityText | The severity text (also known as log level).

What actually happens is that severityText contains the original value. If I have the following config : 
```yaml
      - type: regex_parser
        id: extract-nginx-log #Goto end
        parse_from: body
        regex: '(?P<statuscode>\d{3}) .*'
        severity:
          parse_from: attributes.statuscode
          mapping:
            error: "5xx"
            warn: "4xx"
            info: "3xx"
            debug: "2xx"
```
And the following log :
`201 Content created`

The log entry will have "201" as `severityText` and "9" as `severity`. I would expect the `severityText` to be `info`...

**Comment by jtama** [comment] 2022-09-27 08:58
Could be done in `help/severity.go` :
```go
func (m severityMap) find(value interface{}) (entry.Severity, string, error) {
	switch v := value.(type) {
	case int:
		strV := strconv.Itoa(v)
		if severity, ok := m[strV]; ok {
			return severity, severity.String(), nil
		}
		return entry.Default, strV, nil
	case float64:
		if v != float64(int(v)) {
			return entry.Default, "", fmt.Errorf("type %T cannot be a severity unless it is a whole number", v)
		}
		strV := strconv.Itoa(int(v))
		if severity, ok := m[strV]; ok {
			return severity, severity.String(), nil
		}
		return entry.Default, strV, nil
	case string:
		if severity, ok := m[strings.ToLower(v)]; ok {
			return severity, severity.String(), nil
		}
		return entry.Default, v, nil
	case []byte:
		if severity, ok := m[strings.ToLower(string(v))]; ok {
			return severity, severity.String(), nil
		}
		return entry.Default, string(v), nil
	default:
		return entry.Default, "", fmt.Errorf("type %T cannot be a severity", v)
	}
}
```

Don't know if it make sens for anyone else.

**Comment by jpkrohling** [comment] 2022-09-27 17:10
> I do not have the skills to do it.

Don't worry, thanks for the issue anyway. I'll assign this to me and take a look soon.

**Comment by jtama** [comment] 2022-09-28 07:48
Nevermind my previous comment. SeverityText should be the original one. 
https://github.com/open-telemetry/opentelemetry-collector/blob/1c217b366fbdb209044d8f4c3fece079ae23bd3b/pdata/internal/data/protogen/logs/v1/logs.pb.go#L371-L372).

**Closed** 2022-11-09 19:07 UTC
Labels: enhancement, priority:p2, exporter/loki
