### ISSUE TITLE
[receiver/filelog] Set instrumentation scope name and version 

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#31737] opened 2024-03-13 20:45 UTC
### Component(s)

receiver/filelog

### Is your feature request related to a problem? Please describe.

I noticed today that the filelog receiver does not set an instrumentation scope name or version on the logs its scrapes. 

### Describe the solution you'd like

In my mind it would be appropriate for `otelcol/filelogreceiver` (following the mdatagen pattern) to be the name and the collector build version to be the version.

### Describe alternatives you've considered

I recognize this may be on purpose since the log being scraped might provide a scope name/version based on the instrumentation that wrote the log.

### Additional context

I noticed missing scope name/version in filelog receiver first, but basically all our receivers that are not using mdatagen but should have these fields are missing them.  I'm opening this specific issue first, but it would probably be good to update scope name/version for all applicable receivers.

**Comment by djaglowski** [comment] 2024-03-20 12:34
I am not convinced this is the desired functionality. The scope is meant to indicate the logger which emitted the log, not the machinery that read it from where it was emitted. This distinction is described in the semantic conventions [here](https://github.com/open-telemetry/semantic-conventions/blob/80a2d1a8f70c96c51e541827c7548ba42bb77876/docs/general/logs.md#log-media).

Additionally, the pkg/stanza operators include a scope name parser, which is intended to allow users to isolate the actual scope from logs, when present. (Though #23387 indicates this does not work as intended yet pending analysis of performance implications.)

**Comment by TylerHelmuth** [comment] 2024-03-20 16:50
> The scope is meant to indicate the logger which emitted the log, not the machinery that read it from where it was emitted. This distinction is described in the semantic conventions [here](https://github.com/open-telemetry/semantic-conventions/blob/80a2d1a8f70c96c51e541827c7548ba42bb77876/docs/general/logs.md#log-media).

Ok cool, I figured this was a possible outcome of the issue. 

If the stance is that the the scope name/version should be settable from the log then I agree we should move forward with https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23387 and close this issue.

**Comment by djaglowski** [comment] 2024-03-26 17:55
Closing in favor of #23387

**Closed by djaglowski** 2024-03-26 17:55 UTC
Labels: enhancement, receiver/filelog
