### ISSUE TITLE
Stability tests failed in branch master for commit a00790dc6f9a15929459fbf5b88c644ba6a1f03a

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-collector-contrib#354] opened 2020-06-23 22:48 UTC
Link to failed job: https://circleci.com/gh/open-telemetry/opentelemetry-collector-contrib/4730.

**Comment by tigrannajaryan** [comment] 2020-06-29 18:24
Duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/369 ?

**Closed** 2020-07-07 17:34 UTC
