### ISSUE TITLE
exporter/datadogexporter: nil panic when metrics API request can not be built

### ISSUE THREAD

**Issue by gbbr** [open-telemetry/opentelemetry-collector-contrib#19158] opened 2023-03-01 12:59 UTC
### Component(s)

exporter/datadog

### What happened?

When the [metrics API](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.70.0/exporter/datadogexporter/metrics_exporter.go#L228) submission client can not build the request, it [returns a nil](https://github.com/DataDog/datadog-api-client-go/blob/v2.9.0/api/datadogV1/api_metrics.go#L645) HTTP response. This results in a panic when [verifying](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.70.0/exporter/datadogexporter/internal/clientutil/error_converter.go#L32) if it is a retryable error.

### Collector version

v0.70.0

**Comment by mx-psi** [comment] 2023-03-01 14:16
Based on the conversation on the linked PR, I think this is a duplicate of #18099

**Closed by mx-psi** 2023-03-01 14:16 UTC
Labels: bug, needs triage
