### ISSUE TITLE
otel/opentelemetry-collector-contrib:0.41.0 missing in dockerhub

### ISSUE THREAD

**Issue by Apollorion** [open-telemetry/opentelemetry-collector-contrib#6919] opened 2021-12-20 20:34 UTC
https://hub.docker.com/r/otel/opentelemetry-collector-contrib/tags
There is no 0.41.0 tag, although it's been released on this repo.

**Comment by mx-psi** [comment] 2021-12-21 09:03
This is a duplicate of #6714, let's continue the discussion there

**Closed by mx-psi** 2021-12-21 09:03 UTC
Labels: bug
